-- 설비정지 / 관리자호출 1단계 스키마
-- 대상: JSHANES
-- 설명:
--   EQUIP_STOP_EVENTS  설비정지 이벤트(정지 등록 → 사유 확정 → 해제 → 유실시간 확정)
--   EQUIP_CALL_EVENTS  관리자호출 이력(호출 → 응대)
--   COM_CODES          EQUIP_STOP_REASON / EQUIP_CALL_TYPE 코드 seed
-- 시각은 모두 서버 SYSTIMESTAMP 기준이다. 클라이언트 시계를 신뢰하지 않는다.
-- --execute-file 은 / 한 줄로 블록을 나눈다.

BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE EQUIP_STOP_EVENTS (
    STOP_ID          NUMBER          NOT NULL,
    COMPANY          VARCHAR2(50)    NOT NULL,
    PLANT_CD         VARCHAR2(50)    NOT NULL,
    EQUIP_CODE       VARCHAR2(50)    NOT NULL,
    JOB_ORDER_NO     VARCHAR2(50),
    STOP_REASON      VARCHAR2(50),
    STOP_REMARK      VARCHAR2(500),
    STATUS           VARCHAR2(20)    DEFAULT 'OPEN' NOT NULL,
    STARTED_AT       TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STARTED_BY       VARCHAR2(50),
    RELEASED_AT      TIMESTAMP,
    RELEASED_BY      VARCHAR2(50),
    RELEASE_REMARK   VARCHAR2(500),
    LOSS_SECONDS     NUMBER,
    PREV_EQUIP_STATUS VARCHAR2(20),
    CREATED_BY       VARCHAR2(50),
    UPDATED_BY       VARCHAR2(50),
    CREATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT       TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EQUIP_STOP_EVENTS PRIMARY KEY (STOP_ID),
    CONSTRAINT CK_EQUIP_STOP_STATUS CHECK (STATUS IN ('OPEN','CLOSED'))
  )~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~COMMENT ON TABLE EQUIP_STOP_EVENTS IS '설비정지 이벤트. 키오스크에서 등록하고 해제 시 유실시간(LOSS_SECONDS)을 서버가 확정한다'~';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN EQUIP_STOP_EVENTS.STOP_REASON IS '정지사유. COM_CODES(EQUIP_STOP_REASON). NULL=사유미정(해제 전 확정 필요)'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN EQUIP_STOP_EVENTS.STATUS IS 'OPEN=정지중, CLOSED=해제완료'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN EQUIP_STOP_EVENTS.LOSS_SECONDS IS '유실시간(초). 해제 시 RELEASED_AT-STARTED_AT 로 서버가 계산해 고정한다'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN EQUIP_STOP_EVENTS.PREV_EQUIP_STATUS IS '정지 직전 EQUIP_MASTERS.STATUS. 해제 시 이 값으로 되돌린다'~';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 설비당 진행중(OPEN) 정지는 1건만 허용한다. CLOSED 행은 NULL 이 되어 인덱스에 들어가지 않는다.
BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UX_EQUIP_STOP_OPEN ON EQUIP_STOP_EVENTS (
    CASE WHEN STATUS = 'OPEN' THEN COMPANY END,
    CASE WHEN STATUS = 'OPEN' THEN PLANT_CD END,
    CASE WHEN STATUS = 'OPEN' THEN EQUIP_CODE END
  )~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX IX_EQUIP_STOP_EQUIP ON EQUIP_STOP_EVENTS (COMPANY, PLANT_CD, EQUIP_CODE, STARTED_AT)~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX IX_EQUIP_STOP_ORDER ON EQUIP_STOP_EVENTS (COMPANY, PLANT_CD, JOB_ORDER_NO)~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE SEQUENCE SEQ_EQUIP_STOP_EVENTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE TABLE EQUIP_CALL_EVENTS (
    CALL_ID        NUMBER          NOT NULL,
    COMPANY        VARCHAR2(50)    NOT NULL,
    PLANT_CD       VARCHAR2(50)    NOT NULL,
    EQUIP_CODE     VARCHAR2(50)    NOT NULL,
    JOB_ORDER_NO   VARCHAR2(50),
    CALL_TYPE      VARCHAR2(50)    NOT NULL,
    CALL_REMARK    VARCHAR2(500),
    STATUS         VARCHAR2(20)    DEFAULT 'OPEN' NOT NULL,
    CALLED_AT      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CALLED_BY      VARCHAR2(50),
    ACKED_AT       TIMESTAMP,
    ACKED_BY       VARCHAR2(50),
    ACK_REMARK     VARCHAR2(500),
    CREATED_BY     VARCHAR2(50),
    UPDATED_BY     VARCHAR2(50),
    CREATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_EQUIP_CALL_EVENTS PRIMARY KEY (CALL_ID),
    CONSTRAINT CK_EQUIP_CALL_STATUS CHECK (STATUS IN ('OPEN','ACKED'))
  )~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~COMMENT ON TABLE EQUIP_CALL_EVENTS IS '관리자호출 이력. 호출(OPEN) 후 담당자가 도착해 응대하면 ACKED'~';
  EXECUTE IMMEDIATE q'~COMMENT ON COLUMN EQUIP_CALL_EVENTS.CALL_TYPE IS '호출유형. COM_CODES(EQUIP_CALL_TYPE)'~';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- 설비당 진행중(OPEN) 호출은 1건만 허용한다.
BEGIN
  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UX_EQUIP_CALL_OPEN ON EQUIP_CALL_EVENTS (
    CASE WHEN STATUS = 'OPEN' THEN COMPANY END,
    CASE WHEN STATUS = 'OPEN' THEN PLANT_CD END,
    CASE WHEN STATUS = 'OPEN' THEN EQUIP_CODE END
  )~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE INDEX IX_EQUIP_CALL_EQUIP ON EQUIP_CALL_EVENTS (COMPANY, PLANT_CD, EQUIP_CODE, CALLED_AT)~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE q'~CREATE SEQUENCE SEQ_EQUIP_CALL_EVENTS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE~';
EXCEPTION
  WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

-- ── 공통코드 seed ─────────────────────────────────────────────
-- ATTR1 = 손실분류(PLANNED/SETUP/FAILURE/MANAGEMENT/SPEED/QUALITY) — 가동률 산출 도입 시 사용할 자리만 채워둔다.
-- ATTR2 = 통제가능여부(Y/N)
MERGE INTO COM_CODES t
USING (
  SELECT 'EQUIP_STOP_REASON' GROUP_CODE, 'FAILURE'   DETAIL_CODE, '설비고장'   CODE_NAME, 1 SORT_ORDER, 'FAILURE'    ATTR1, 'Y' ATTR2 FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'JAM',        '부품걸림',        2, 'FAILURE',    'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'MAT_SHORT',  '자재결품',        3, 'MANAGEMENT', 'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'MODEL_CHG',  '모델교체',        4, 'SETUP',      'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'SETUP',      '작업준비',        5, 'SETUP',      'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'QUALITY',    '품질이상',        6, 'QUALITY',    'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'NO_WORKER',  '작업자부재',      7, 'MANAGEMENT', 'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'POWER',      '정전',            8, 'FAILURE',    'N' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'MAINT',      '예방정비',        9, 'PLANNED',    'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_STOP_REASON', 'ETC',        '기타',           99, 'MANAGEMENT', 'Y' FROM DUAL UNION ALL
  SELECT 'EQUIP_CALL_TYPE',   'EQUIP',      '설비이상',        1, NULL,         NULL FROM DUAL UNION ALL
  SELECT 'EQUIP_CALL_TYPE',   'QUALITY',    '품질문의',        2, NULL,         NULL FROM DUAL UNION ALL
  SELECT 'EQUIP_CALL_TYPE',   'MATERIAL',   '자재요청',        3, NULL,         NULL FROM DUAL UNION ALL
  SELECT 'EQUIP_CALL_TYPE',   'ETC',        '기타',           99, NULL,         NULL FROM DUAL
) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = '40' AND t.PLANT_CD = '1000')
WHEN MATCHED THEN UPDATE SET
  t.CODE_NAME = s.CODE_NAME,
  t.SORT_ORDER = s.SORT_ORDER,
  t.ATTR1 = s.ATTR1,
  t.ATTR2 = s.ATTR2,
  t.USE_YN = 'Y',
  t.UPDATED_AT = SYSTIMESTAMP,
  t.UPDATED_BY = 'system'
WHEN NOT MATCHED THEN INSERT (
  GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, ATTR1, ATTR2,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', s.ATTR1, s.ATTR2,
  '40', '1000', 'system', 'system', SYSTIMESTAMP, SYSTIMESTAMP
)
/

COMMIT
/
