-- BOM_MASTERS PK 변경: (COMPANY, PLANT_CD, PARENT, CHILD, REVISION) → (COMPANY, PLANT_CD, PARENT, CHILD, VALID_FROM)
-- 배경: BOM 중복/버전 기준을 적용일자(VALID_FROM)로 통일. 리비전은 일반 속성으로 유지.
-- 사전 실측(2026-07-03): 총 40행, VALID_FROM NULL 0건, 새 키 기준 중복 0건, 참조 FK 없음, 의존 PL/SQL 없음.
ALTER TABLE BOM_MASTERS DROP CONSTRAINT PK_BOM_MASTERS
/
ALTER TABLE BOM_MASTERS MODIFY (VALID_FROM DATE NOT NULL)
/
ALTER TABLE BOM_MASTERS ADD CONSTRAINT PK_BOM_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, PARENT_ITEM_CODE, CHILD_ITEM_CODE, VALID_FROM)
/
