-- 2026-09-15 통전검사(도통검사기) 양불마스터 한도견본 시드
-- 한도견본은 품목 기준이라, 통전검사 대상 품목마다 양품(LIMIT_OK) / 불량(LIMIT_NG) 1쌍을 등록한다.
-- AID_CODE 가 곧 바코드다. 실물 견본에 이 코드를 라벨로 붙이고 검사 화면에서 스캔한다.
-- REQUIRED_YN='Y' 이므로 해당 품목 통전검사는 대조를 끝내야 합격/불합격 등록이 가능하다.
-- 앞서 넣은 임시 견본 2건(LS-OK-0001, LS-NG-0001)은 명명규칙 통일을 위해 제거한다(대조 기록 0건 확인).
DELETE FROM INSPECT_AIDS WHERE COMPANY='40' AND PLANT_CD='1000' AND AID_CODE IN ('LS-OK-0001','LS-NG-0001')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601', 'LIMIT_OK', '[양품] MAG_EAD65942601', 'MAG_EAD65942601', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601', 'LIMIT_NG', '[불량] MAG_EAD65942601 도통불량', 'MAG_EAD65942601', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-ABL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-ABL001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ABL001', 'MAG_EAD65942601-ABL001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-ABL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-ABL001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ABL001 도통불량', 'MAG_EAD65942601-ABL001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-ABN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-ABN001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ABN001', 'MAG_EAD65942601-ABN001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-ABN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-ABN001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ABN001 도통불량', 'MAG_EAD65942601-ABN001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-AGN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-AGN001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AGN001', 'MAG_EAD65942601-AGN001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-AGN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-AGN001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AGN001 도통불량', 'MAG_EAD65942601-AGN001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-AGY001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-AGY001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AGY001', 'MAG_EAD65942601-AGY001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-AGY001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-AGY001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AGY001 도통불량', 'MAG_EAD65942601-AGY001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-ARD001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-ARD001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ARD001', 'MAG_EAD65942601-ARD001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-ARD001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-ARD001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ARD001 도통불량', 'MAG_EAD65942601-ARD001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-MAG_EAD65942601-AYL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-MAG_EAD65942601-AYL001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AYL001', 'MAG_EAD65942601-AYL001', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-MAG_EAD65942601-AYL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-MAG_EAD65942601-AYL001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AYL001 도통불량', 'MAG_EAD65942601-AYL001', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800', 'LIMIT_OK', '[양품] N91H00-X9800', 'N91H00-X9800', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800', 'LIMIT_NG', '[불량] N91H00-X9800 도통불량', 'N91H00-X9800', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-C1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-C1', 'LIMIT_OK', '[양품] N91H00-X9800-C1', 'N91H00-X9800-C1', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-C1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-C1', 'LIMIT_NG', '[불량] N91H00-X9800-C1 도통불량', 'N91H00-X9800-C1', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-C1-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-C1-A', 'LIMIT_OK', '[양품] N91H00-X9800-C1-A', 'N91H00-X9800-C1-A', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-C1-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-C1-A', 'LIMIT_NG', '[불량] N91H00-X9800-C1-A 도통불량', 'N91H00-X9800-C1-A', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-C2' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-C2', 'LIMIT_OK', '[양품] N91H00-X9800-C2', 'N91H00-X9800-C2', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-C2' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-C2', 'LIMIT_NG', '[불량] N91H00-X9800-C2 도통불량', 'N91H00-X9800-C2', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-C2-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-C2-A', 'LIMIT_OK', '[양품] N91H00-X9800-C2-A', 'N91H00-X9800-C2-A', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-C2-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-C2-A', 'LIMIT_NG', '[불량] N91H00-X9800-C2-A 도통불량', 'N91H00-X9800-C2-A', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-R' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-R', 'LIMIT_OK', '[양품] N91H00-X9800-R', 'N91H00-X9800-R', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-R' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-R', 'LIMIT_NG', '[불량] N91H00-X9800-R 도통불량', 'N91H00-X9800-R', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-R-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-R-S', 'LIMIT_OK', '[양품] N91H00-X9800-R-S', 'N91H00-X9800-R-S', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-R-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-R-S', 'LIMIT_NG', '[불량] N91H00-X9800-R-S 도통불량', 'N91H00-X9800-R-S', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-S', 'LIMIT_OK', '[양품] N91H00-X9800-S', 'N91H00-X9800-S', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-S', 'LIMIT_NG', '[불량] N91H00-X9800-S 도통불량', 'N91H00-X9800-S', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-S-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-S-A', 'LIMIT_OK', '[양품] N91H00-X9800-S-A', 'N91H00-X9800-S-A', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-S-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-S-A', 'LIMIT_NG', '[불량] N91H00-X9800-S-A 도통불량', 'N91H00-X9800-S-A', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-S-AB' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-S-AB', 'LIMIT_OK', '[양품] N91H00-X9800-S-AB', 'N91H00-X9800-S-AB', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-S-AB' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-S-AB', 'LIMIT_NG', '[불량] N91H00-X9800-S-AB 도통불량', 'N91H00-X9800-S-AB', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800-S-ABC' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800-S-ABC', 'LIMIT_OK', '[양품] N91H00-X9800-S-ABC', 'N91H00-X9800-S-ABC', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800-S-ABC' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800-S-ABC', 'LIMIT_NG', '[불량] N91H00-X9800-S-ABC 도통불량', 'N91H00-X9800-S-ABC', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-N91H00-X9800_1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-N91H00-X9800_1', 'LIMIT_OK', '[양품] N91H00-X9800_1', 'N91H00-X9800_1', 'CONTINUITY', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-N91H00-X9800_1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-N91H00-X9800_1', 'LIMIT_NG', '[불량] N91H00-X9800_1 도통불량', 'N91H00-X9800_1', 'CONTINUITY', 'Y', 2, 'FUNC', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'admin', SYSTIMESTAMP, '도통 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
