-- 2026-09-15 양불마스터 대조 검증용 한도견본 시드
-- 범위를 좁히려고 특정 품목(N91H00-X9800-S-AB)·통전검사에만 배정한다.
-- 실물 견본에는 AID_CODE 를 바코드 라벨로 부착한다(전용 바코드 컬럼 없음).
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-0001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-0001', 'LIMIT_OK', '양품 한도견본 #1', 'N91H00-X9800-S-AB', 'CONTINUITY', 'Y', 1, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-0001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-0001', 'LIMIT_NG', '불량 한도견본 #1 (단선)', 'N91H00-X9800-S-AB', 'CONTINUITY', 'Y', 2, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '통전검사 스테이션', 'SEED', 'SEED')
/
