-- 2026-09-15 단자검사(TERMINAL) 양불마스터 한도견본 시드
-- 통전검사 시드(2026-09-15-inspect-aid-seed-continuity-all.sql)와 같은 구조, INSPECT_TYPE 만 TERMINAL.
-- AID_CODE 가 곧 바코드다. 통전용과 구분되도록 접두사에 T 를 넣는다(LS-OK-T-<품목>, LS-NG-T-<품목>).
-- 불량 견본 대표 불량코드는 단자/압착 전용 코드가 없어 ASM(조립불량)을 쓴다.
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601', 'LIMIT_OK', '[양품] MAG_EAD65942601 단자', 'MAG_EAD65942601', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601', 'LIMIT_NG', '[불량] MAG_EAD65942601 단자불량', 'MAG_EAD65942601', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-ABL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-ABL001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ABL001 단자', 'MAG_EAD65942601-ABL001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-ABL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-ABL001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ABL001 단자불량', 'MAG_EAD65942601-ABL001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-ABN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-ABN001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ABN001 단자', 'MAG_EAD65942601-ABN001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-ABN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-ABN001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ABN001 단자불량', 'MAG_EAD65942601-ABN001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-AGN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-AGN001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AGN001 단자', 'MAG_EAD65942601-AGN001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-AGN001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-AGN001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AGN001 단자불량', 'MAG_EAD65942601-AGN001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-AGY001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-AGY001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AGY001 단자', 'MAG_EAD65942601-AGY001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-AGY001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-AGY001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AGY001 단자불량', 'MAG_EAD65942601-AGY001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-ARD001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-ARD001', 'LIMIT_OK', '[양품] MAG_EAD65942601-ARD001 단자', 'MAG_EAD65942601-ARD001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-ARD001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-ARD001', 'LIMIT_NG', '[불량] MAG_EAD65942601-ARD001 단자불량', 'MAG_EAD65942601-ARD001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-MAG_EAD65942601-AYL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-MAG_EAD65942601-AYL001', 'LIMIT_OK', '[양품] MAG_EAD65942601-AYL001 단자', 'MAG_EAD65942601-AYL001', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-MAG_EAD65942601-AYL001' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-MAG_EAD65942601-AYL001', 'LIMIT_NG', '[불량] MAG_EAD65942601-AYL001 단자불량', 'MAG_EAD65942601-AYL001', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800', 'LIMIT_OK', '[양품] N91H00-X9800 단자', 'N91H00-X9800', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800', 'LIMIT_NG', '[불량] N91H00-X9800 단자불량', 'N91H00-X9800', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-C1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-C1', 'LIMIT_OK', '[양품] N91H00-X9800-C1 단자', 'N91H00-X9800-C1', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-C1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-C1', 'LIMIT_NG', '[불량] N91H00-X9800-C1 단자불량', 'N91H00-X9800-C1', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-C1-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-C1-A', 'LIMIT_OK', '[양품] N91H00-X9800-C1-A 단자', 'N91H00-X9800-C1-A', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-C1-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-C1-A', 'LIMIT_NG', '[불량] N91H00-X9800-C1-A 단자불량', 'N91H00-X9800-C1-A', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-C2' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-C2', 'LIMIT_OK', '[양품] N91H00-X9800-C2 단자', 'N91H00-X9800-C2', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-C2' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-C2', 'LIMIT_NG', '[불량] N91H00-X9800-C2 단자불량', 'N91H00-X9800-C2', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-C2-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-C2-A', 'LIMIT_OK', '[양품] N91H00-X9800-C2-A 단자', 'N91H00-X9800-C2-A', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-C2-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-C2-A', 'LIMIT_NG', '[불량] N91H00-X9800-C2-A 단자불량', 'N91H00-X9800-C2-A', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-R' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-R', 'LIMIT_OK', '[양품] N91H00-X9800-R 단자', 'N91H00-X9800-R', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-R' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-R', 'LIMIT_NG', '[불량] N91H00-X9800-R 단자불량', 'N91H00-X9800-R', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-R-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-R-S', 'LIMIT_OK', '[양품] N91H00-X9800-R-S 단자', 'N91H00-X9800-R-S', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-R-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-R-S', 'LIMIT_NG', '[불량] N91H00-X9800-R-S 단자불량', 'N91H00-X9800-R-S', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-S', 'LIMIT_OK', '[양품] N91H00-X9800-S 단자', 'N91H00-X9800-S', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-S' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-S', 'LIMIT_NG', '[불량] N91H00-X9800-S 단자불량', 'N91H00-X9800-S', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-S-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-S-A', 'LIMIT_OK', '[양품] N91H00-X9800-S-A 단자', 'N91H00-X9800-S-A', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-S-A' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-S-A', 'LIMIT_NG', '[불량] N91H00-X9800-S-A 단자불량', 'N91H00-X9800-S-A', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-S-AB' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-S-AB', 'LIMIT_OK', '[양품] N91H00-X9800-S-AB 단자', 'N91H00-X9800-S-AB', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-S-AB' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-S-AB', 'LIMIT_NG', '[불량] N91H00-X9800-S-AB 단자불량', 'N91H00-X9800-S-AB', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800-S-ABC' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800-S-ABC', 'LIMIT_OK', '[양품] N91H00-X9800-S-ABC 단자', 'N91H00-X9800-S-ABC', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800-S-ABC' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800-S-ABC', 'LIMIT_NG', '[불량] N91H00-X9800-S-ABC 단자불량', 'N91H00-X9800-S-ABC', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-OK-T-N91H00-X9800_1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-OK-T-N91H00-X9800_1', 'LIMIT_OK', '[양품] N91H00-X9800_1 단자', 'N91H00-X9800_1', 'TERMINAL', 'Y', 1, NULL, TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 정상품 한도견본 — 검사기 결과가 합격이어야 정상', 'SEED', 'SEED')
/
MERGE INTO INSPECT_AIDS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD, 'LS-NG-T-N91H00-X9800_1' AID_CODE FROM DUAL) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.AID_CODE = s.AID_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, AID_CODE, AID_TYPE, AID_NAME, ITEM_CODE, INSPECT_TYPE, REQUIRED_YN, SORT_ORDER, DEFECT_CODE, VALID_FROM, VALID_TO, STATUS, USE_YN, LOCATION, APPROVED_BY, APPROVED_AT, REMARK, CREATED_BY, UPDATED_BY)
VALUES ('40', '1000', 'LS-NG-T-N91H00-X9800_1', 'LIMIT_NG', '[불량] N91H00-X9800_1 단자불량', 'N91H00-X9800_1', 'TERMINAL', 'Y', 2, 'ASM', TRUNC(SYSDATE), ADD_MONTHS(TRUNC(SYSDATE), 12), 'ACTIVE', 'Y', '단자검사 스테이션', 'admin', SYSTIMESTAMP, '단자 불량 한도견본 — 검사기 결과가 불합격이어야 정상', 'SEED', 'SEED')
/
