-- 2026-09-15 통전·단자검사 양불마스터 대조
-- 1) INSPECT_AIDS 확장 (검사유형 / 대조필수 / 표시순서)
-- 2) INSPECT_SAMPLE_CHECKS / INSPECT_SAMPLE_CHECK_ITEMS 신설
-- 3) 채번 SEQ + SEQ_RULES, 공통코드 INSPECT_TYPE.TERMINAL
ALTER TABLE INSPECT_AIDS ADD (
  INSPECT_TYPE VARCHAR2(30),
  REQUIRED_YN  VARCHAR2(1) DEFAULT 'Y' NOT NULL,
  SORT_ORDER   NUMBER(5)   DEFAULT 0   NOT NULL
)
/
COMMENT ON COLUMN INSPECT_AIDS.INSPECT_TYPE IS '적용 검사유형 (COM_CODES INSPECT_TYPE: CONTINUITY 도통/TERMINAL 단자. NULL=전 검사유형 공통)'
/
COMMENT ON COLUMN INSPECT_AIDS.REQUIRED_YN IS '검사 전 대조 필수 여부 (Y=필수, N=참고용)'
/
COMMENT ON COLUMN INSPECT_AIDS.SORT_ORDER IS '대조 모달 표시 순서'
/
CREATE TABLE INSPECT_SAMPLE_CHECKS (
  COMPANY        VARCHAR2(50)  NOT NULL,
  PLANT_CD       VARCHAR2(50)  NOT NULL,
  CHECK_NO       VARCHAR2(30)  NOT NULL,
  ORDER_NO       VARCHAR2(50)  NOT NULL,
  INSPECT_TYPE   VARCHAR2(30)  NOT NULL,
  EQUIP_CODE     VARCHAR2(50)  NOT NULL,
  ITEM_CODE      VARCHAR2(50),
  WORK_DATE      DATE          NOT NULL,
  SHIFT_CODE     VARCHAR2(20)  DEFAULT 'NONE' NOT NULL,
  OVERALL_RESULT VARCHAR2(10)  NOT NULL,
  CHECKER_ID     VARCHAR2(50),
  CHECKED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  REMARK         VARCHAR2(500),
  CREATED_BY     VARCHAR2(50),
  UPDATED_BY     VARCHAR2(50),
  CREATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_INSPECT_SAMPLE_CHECKS PRIMARY KEY (COMPANY, PLANT_CD, CHECK_NO)
)
/
CREATE INDEX IX_ISC_KEY ON INSPECT_SAMPLE_CHECKS
  (COMPANY, PLANT_CD, ORDER_NO, INSPECT_TYPE, EQUIP_CODE, WORK_DATE, SHIFT_CODE, CHECKED_AT DESC)
/
COMMENT ON TABLE INSPECT_SAMPLE_CHECKS IS '양불마스터(한도견본) 대조 헤더 — 통전·단자검사 시작 전 검사기 유효성 확인 기록'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECKS.CHECK_NO IS '대조번호 (PKG_SEQ_GENERATOR docType SMP_CHK)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECKS.OVERALL_RESULT IS '종합판정 (PASS=필수 견본 전부 OK, NG=1건 이상 불일치)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECKS.WORK_DATE IS '조업일 (설비점검 조업일 window 기준)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECKS.SHIFT_CODE IS '교대코드 (SHIFT_PATTERNS.SHIFT_CODE, 미판별 시 NONE)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECKS.CHECKER_ID IS '대조 판정자 = 검사기 대표 작업자 (로그인 계정은 CREATED_BY)'
/
CREATE TABLE INSPECT_SAMPLE_CHECK_ITEMS (
  COMPANY         VARCHAR2(50) NOT NULL,
  PLANT_CD        VARCHAR2(50) NOT NULL,
  CHECK_NO        VARCHAR2(30) NOT NULL,
  SEQ_NO          NUMBER(5)    NOT NULL,
  AID_CODE        VARCHAR2(50) NOT NULL,
  AID_TYPE        VARCHAR2(30) NOT NULL,
  EXPECTED_RESULT VARCHAR2(10) NOT NULL,
  ACTUAL_RESULT   VARCHAR2(10) NOT NULL,
  RESULT          VARCHAR2(10) NOT NULL,
  SCANNED_AT      TIMESTAMP,
  REMARK          VARCHAR2(500),
  CREATED_BY      VARCHAR2(50),
  CREATED_AT      TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_INSPECT_SAMPLE_CHECK_ITEMS PRIMARY KEY (COMPANY, PLANT_CD, CHECK_NO, SEQ_NO)
)
/
COMMENT ON TABLE INSPECT_SAMPLE_CHECK_ITEMS IS '양불마스터 대조 샘플별 결과 — 기대결과와 검사기 실제결과 비교'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.AID_CODE IS '한도견본 코드 (INSPECT_AIDS.AID_CODE, 바코드 스캔값)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.EXPECTED_RESULT IS '기대 결과 (LIMIT_OK=PASS, LIMIT_NG=FAIL)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.ACTUAL_RESULT IS '검사기 실제 결과 (PASS/FAIL, 작업자 입력)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.RESULT IS '판정 (OK=기대와 일치, NG=불일치) — 서버가 산출'
/
CREATE SEQUENCE SEQ_SMP_CHK START WITH 1 INCREMENT BY 1 NOCACHE
/
MERGE INTO SEQ_RULES t
USING (SELECT 'SMP_CHK' DOC_TYPE, '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
ON (t.DOC_TYPE = s.DOC_TYPE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN INSERT (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, SEPARATOR, DESCRIPTION, USE_YN, COMPANY, PLANT_CD)
VALUES ('SMP_CHK', 'SMC', 'SEQ_SMP_CHK', 4, 'YYYYMMDD', '-', '양불마스터 대조번호', 'Y', '40', '1000')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_TYPE' GROUP_CODE, 'TERMINAL' DETAIL_CODE, '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, CODE_DESC, SORT_ORDER, USE_YN, COMPANY, PLANT_CD)
VALUES ('INSPECT_TYPE', 'TERMINAL', '단자', '단자검사', 7, 'Y', '40', '1000')
/
