import type { ReactNode } from 'react';

export default function DocumentTable({ columns, rows, rowId = 'ROW_ID', focusRowId, empty, actions, onReorder }: {
  columns: readonly (readonly [string, string])[]; rows: Record<string, unknown>[]; rowId?: string; focusRowId?: number | null; empty: string;
  actions?: (row: Record<string, unknown>) => ReactNode;
  onReorder?: (sourceId: number, targetId: number) => void;
}) {
  return <div className="min-h-48 flex-1 overflow-auto rounded-lg border border-border bg-surface"><table className="min-w-max w-full border-collapse text-xs"><thead className="sticky top-0 z-10 bg-slate-800 text-white"><tr>{columns.map(([key, label]) => <th key={key} className="whitespace-nowrap border-r border-white/15 px-3 py-2 text-left font-semibold">{label}</th>)}{actions && <th className="px-3 py-2">작업</th>}</tr></thead><tbody>{rows.map((row, index) => { const id = Number(row[rowId] ?? row[rowId.toLowerCase()] ?? index); return <tr key={id} data-row-id={id} draggable={Boolean(onReorder)} onDragStart={(event)=>event.dataTransfer.setData('text/plain',String(id))} onDragOver={(event)=>onReorder && event.preventDefault()} onDrop={(event)=>{ event.preventDefault(); const sourceId=Number(event.dataTransfer.getData('text/plain')); if(sourceId && sourceId!==id) onReorder?.(sourceId,id); }} className={`${focusRowId === id ? 'bg-amber-200/40 ring-1 ring-inset ring-amber-500' : index % 2 ? 'bg-background/60' : 'bg-surface'} ${onReorder ? 'cursor-grab active:cursor-grabbing' : ''} hover:bg-primary/5`}>{columns.map(([key]) => <td key={key} className="max-w-[260px] border-b border-r border-border px-3 py-2 align-top whitespace-pre-wrap">{String(row[key] ?? row[key.toLowerCase()] ?? '-')}</td>)}{actions && <td className="border-b border-border px-2 py-1">{actions(row)}</td>}</tr>; })}{!rows.length && <tr><td colSpan={columns.length + (actions ? 1 : 0)} className="p-10 text-center text-sm text-text-muted">{empty}</td></tr>}</tbody></table></div>;
}
