-- E50 TUBE절단기·커넥터마킹기용 신규 공정 2건을 만들고 설비에 배정한다.
-- 공정 코드는 설비 코드 규칙(EQ-{공정}-{번호})을 따라 TUBCT / CNMRK 로 맞춘다.
-- 커넥터 마킹은 기존 PROCESS_TYPE 에 해당 유형이 없어 공통코드부터 추가한다.

-- 1) 공통코드: PROCESS_TYPE = MARKING(마킹)
INSERT INTO COM_CODES (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'PROCESS_TYPE', 'MARKING', '마킹', 10, 'Y', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM COM_CODES WHERE GROUP_CODE='PROCESS_TYPE' AND DETAIL_CODE='MARKING' AND COMPANY='40' AND PLANT_CD='1000'
 )
/

-- 2) 공정 마스터: TUBE 절단 (절단 / 열처리계열 / 공통라인)
INSERT INTO PROCESS_MASTERS (PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE, PROCESS_CATEGORY, LINE_TYPE, SORT_ORDER, USE_YN, REMARK, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'TUBCT', 'TUBE절단', 'CUTTING', 'HEAT', 'CM', 6500, 'Y', 'E50 TUBE절단기(EQ-TUBCT-01) 공정', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM PROCESS_MASTERS WHERE PROCESS_CODE='TUBCT' AND COMPANY='40' AND PLANT_CD='1000'
 )
/

-- 3) 공정 마스터: 커넥터 마킹 (마킹 / 조립계열 / 공통라인)
INSERT INTO PROCESS_MASTERS (PROCESS_CODE, PROCESS_NAME, PROCESS_TYPE, PROCESS_CATEGORY, LINE_TYPE, SORT_ORDER, USE_YN, REMARK, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'CNMRK', '커넥터마킹', 'MARKING', 'ASSEMBLY', 'CM', 6600, 'Y', '커넥터 마킹기(EQ-CNMRK-01) 공정', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM PROCESS_MASTERS WHERE PROCESS_CODE='CNMRK' AND COMPANY='40' AND PLANT_CD='1000'
 )
/

-- 4) 설비에 공정 배정
UPDATE EQUIP_MASTERS SET PROCESS_CODE='TUBCT', UPDATED_AT=SYSTIMESTAMP
 WHERE EQUIP_CODE='EQ-TUBCT-01' AND COMPANY='40' AND PLANT_CD='1000'
/
UPDATE EQUIP_MASTERS SET PROCESS_CODE='CNMRK', UPDATED_AT=SYSTIMESTAMP
 WHERE EQUIP_CODE='EQ-CNMRK-01' AND COMPANY='40' AND PLANT_CD='1000'
/
COMMIT
/
