-- 양불마스터 (LIMIT_SAMPLES / LIMIT_SAMPLE_IMAGES) — docs/specs/2026-09-16-limit-sample-master-design.md 3절
-- 대상: JSHANES company=40 plant=1000. 멱등(테이블/인덱스는 존재 확인 후 생성, 코드/메뉴는 MERGE).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 적용 후: ORACLE_SITE=JSHANES python tools/generate_db_schema_doc.py (ERD 갱신)

-- 1) 부모 테이블 (PK = COMPANY + PLANT_CD + SAMPLE_CODE)
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'LIMIT_SAMPLES';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE LIMIT_SAMPLES (
      COMPANY        VARCHAR2(50)   NOT NULL,
      PLANT_CD       VARCHAR2(50)   NOT NULL,
      SAMPLE_CODE    VARCHAR2(50)   NOT NULL,
      SAMPLE_TYPE    VARCHAR2(30)   NOT NULL,
      SAMPLE_NAME    VARCHAR2(200)  NOT NULL,
      ITEM_CODE      VARCHAR2(50),
      PROCESS_CODE   VARCHAR2(50),
      DEFECT_CODE    VARCHAR2(50),
      INSPECT_TYPE   VARCHAR2(30),
      LOCATION       VARCHAR2(200),
      VALID_FROM     DATE,
      VALID_TO       DATE,
      APPROVED_BY    VARCHAR2(50),
      APPROVED_AT    TIMESTAMP,
      STATUS         VARCHAR2(20)   DEFAULT ''ACTIVE'' NOT NULL,
      REQUIRED_YN    CHAR(1)        DEFAULT ''Y'' NOT NULL,
      SORT_ORDER     NUMBER         DEFAULT 0 NOT NULL,
      REMARK         VARCHAR2(500),
      USE_YN         CHAR(1)        DEFAULT ''Y'' NOT NULL,
      CREATED_BY     VARCHAR2(50),
      UPDATED_BY     VARCHAR2(50),
      CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_LIMIT_SAMPLES PRIMARY KEY (COMPANY, PLANT_CD, SAMPLE_CODE),
      CONSTRAINT CK_LIMIT_SAMPLES_TYPE CHECK (SAMPLE_TYPE IN (''OK'',''NG'')),
      CONSTRAINT CK_LIMIT_SAMPLES_STATUS CHECK (STATUS IN (''ACTIVE'',''EXPIRED'',''RETIRED'')),
      CONSTRAINT CK_LIMIT_SAMPLES_USE_YN CHECK (USE_YN IN (''Y'',''N'')),
      CONSTRAINT CK_LIMIT_SAMPLES_REQ_YN CHECK (REQUIRED_YN IN (''Y'',''N''))
    )';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IX_LIMIT_SAMPLES_LOOKUP';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_LIMIT_SAMPLES_LOOKUP ON LIMIT_SAMPLES (COMPANY, PLANT_CD, ITEM_CODE, INSPECT_TYPE, SAMPLE_TYPE)';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IX_LIMIT_SAMPLES_VALID';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_LIMIT_SAMPLES_VALID ON LIMIT_SAMPLES (COMPANY, PLANT_CD, VALID_TO)';
  END IF;
END;
/

-- 2) 사진 자식 테이블 (PK = COMPANY + PLANT_CD + SAMPLE_CODE + SEQ_NO)
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'LIMIT_SAMPLE_IMAGES';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE LIMIT_SAMPLE_IMAGES (
      COMPANY      VARCHAR2(50)   NOT NULL,
      PLANT_CD     VARCHAR2(50)   NOT NULL,
      SAMPLE_CODE  VARCHAR2(50)   NOT NULL,
      SEQ_NO       NUMBER         NOT NULL,
      IMAGE_URL    VARCHAR2(500)  NOT NULL,
      CAPTION      VARCHAR2(200),
      IS_PRIMARY   CHAR(1)        DEFAULT ''N'' NOT NULL,
      SORT_ORDER   NUMBER         DEFAULT 0 NOT NULL,
      CREATED_BY   VARCHAR2(50),
      CREATED_AT   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_LIMIT_SAMPLE_IMAGES PRIMARY KEY (COMPANY, PLANT_CD, SAMPLE_CODE, SEQ_NO),
      CONSTRAINT CK_LIMIT_SAMPLE_IMG_PRIMARY CHECK (IS_PRIMARY IN (''Y'',''N''))
    )';
  END IF;

  -- 견본당 대표 사진 1장을 DB가 강제한다 (IS_PRIMARY = 'N' 행은 NULL이 되어 유니크 대상에서 빠진다)
  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'UX_LIMIT_SAMPLE_IMAGES_PRIMARY';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX UX_LIMIT_SAMPLE_IMAGES_PRIMARY ON LIMIT_SAMPLE_IMAGES (
      CASE WHEN IS_PRIMARY = ''Y'' THEN COMPANY || ''|'' || PLANT_CD || ''|'' || SAMPLE_CODE END
    )';
  END IF;
END;
/

-- 3) 코멘트
COMMENT ON TABLE LIMIT_SAMPLES IS '양불마스터 (양품/불량 한도견본) — 검사 전 대조용 견본의 유효기간·승인·사진 관리'
/
COMMENT ON COLUMN LIMIT_SAMPLES.COMPANY IS '회사 코드'
/
COMMENT ON COLUMN LIMIT_SAMPLES.PLANT_CD IS '사업장 코드'
/
COMMENT ON COLUMN LIMIT_SAMPLES.SAMPLE_CODE IS '견본 코드 (사용자 입력, 실물에 바코드로 부착해 대조 시 스캔)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.SAMPLE_TYPE IS '견본 유형 (COM_CODES LIMIT_SAMPLE_TYPE: OK 양품견본 / NG 불량견본)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.SAMPLE_NAME IS '견본 명칭'
/
COMMENT ON COLUMN LIMIT_SAMPLES.ITEM_CODE IS '대상 품목코드 (ITEM_MASTERS.ITEM_CODE, NULL이면 공용 견본)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.PROCESS_CODE IS '적용 공정코드 (PROCESS_MASTERS.PROCESS_CODE, 선택)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.DEFECT_CODE IS '불량견본(NG)의 대표 불량코드 (DEFECT_CODE_MASTERS.DEFECT_CODE, 선택)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.INSPECT_TYPE IS '적용 검사유형 (COM_CODES INSPECT_TYPE, NULL이면 전 검사유형 공통)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.LOCATION IS '보관 위치'
/
COMMENT ON COLUMN LIMIT_SAMPLES.VALID_FROM IS '유효기간 시작일'
/
COMMENT ON COLUMN LIMIT_SAMPLES.VALID_TO IS '유효기간 종료일 (만료/임박 판정 기준)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.APPROVED_BY IS '승인자'
/
COMMENT ON COLUMN LIMIT_SAMPLES.APPROVED_AT IS '승인일시'
/
COMMENT ON COLUMN LIMIT_SAMPLES.STATUS IS '상태 (COM_CODES LIMIT_SAMPLE_STATUS: ACTIVE 사용중 / EXPIRED 만료 / RETIRED 폐기)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.REQUIRED_YN IS '검사 시작 전 대조 필수 여부 (Y=필수, N=참고용)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.SORT_ORDER IS '대조 모달 표시 순서'
/
COMMENT ON COLUMN LIMIT_SAMPLES.REMARK IS '비고'
/
COMMENT ON COLUMN LIMIT_SAMPLES.USE_YN IS '사용여부 (Y/N)'
/
COMMENT ON COLUMN LIMIT_SAMPLES.CREATED_BY IS '생성자'
/
COMMENT ON COLUMN LIMIT_SAMPLES.UPDATED_BY IS '수정자'
/
COMMENT ON COLUMN LIMIT_SAMPLES.CREATED_AT IS '생성일시'
/
COMMENT ON COLUMN LIMIT_SAMPLES.UPDATED_AT IS '수정일시'
/

COMMENT ON TABLE LIMIT_SAMPLE_IMAGES IS '양불마스터 견본 사진 — 한 견본에 각도별·불량부위별 여러 장. 대표 1장(IS_PRIMARY=Y)이 그리드·대조 모달 썸네일'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.COMPANY IS '회사 코드'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.PLANT_CD IS '사업장 코드'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.SAMPLE_CODE IS '견본 코드 (LIMIT_SAMPLES.SAMPLE_CODE)'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.SEQ_NO IS '사진 순번 (견본 내 MAX+1)'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.IMAGE_URL IS '사진 경로 (/uploads/limit-samples/...)'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.CAPTION IS '사진 설명 (촬영 각도, 불량 부위 등)'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.IS_PRIMARY IS '대표 사진 여부 (Y는 견본당 1건, UX_LIMIT_SAMPLE_IMAGES_PRIMARY가 강제)'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.SORT_ORDER IS '표시 순서'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.CREATED_BY IS '생성자'
/
COMMENT ON COLUMN LIMIT_SAMPLE_IMAGES.CREATED_AT IS '생성일시'
/

-- 4) 공통코드 LIMIT_SAMPLE_TYPE (견본 유형) · LIMIT_SAMPLE_STATUS (상태 배지)
MERGE INTO COM_CODES t
USING (SELECT 'LIMIT_SAMPLE_TYPE' GROUP_CODE,'OK' DETAIL_CODE,'양품견본' CODE_NAME,1 SORT_ORDER,'bg-green-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'LIMIT_SAMPLE_TYPE' GROUP_CODE,'NG' DETAIL_CODE,'불량견본' CODE_NAME,2 SORT_ORDER,'bg-red-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'LIMIT_SAMPLE_STATUS' GROUP_CODE,'ACTIVE' DETAIL_CODE,'사용중' CODE_NAME,1 SORT_ORDER,'bg-green-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'LIMIT_SAMPLE_STATUS' GROUP_CODE,'EXPIRED' DETAIL_CODE,'만료' CODE_NAME,2 SORT_ORDER,'bg-red-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'LIMIT_SAMPLE_STATUS' GROUP_CODE,'RETIRED' DETAIL_CODE,'폐기' CODE_NAME,3 SORT_ORDER,'bg-gray-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/

-- 5) 메뉴 등록: QC_LIMIT_SAMPLE (QUALITY, /master/limit-sample, labelKey menu.master.limitSample)
--    QC_INSPECT_AID(SORT_ORDER 6) 다음 7.
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'QC_LIMIT_SAMPLE' AS MENU_CODE,
         'QUALITY'         AS CATEGORY_CODE,
         7                 AS SORT_ORDER,
         '40'              AS COMPANY,
         '1000'            AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'QC_LIMIT_SAMPLE' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'QC_LIMIT_SAMPLE' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/

COMMIT
/
