-- 대조 실적 컬럼을 양불마스터 이름에 맞춘다 — docs/specs/2026-09-16-limit-sample-master-design.md 5절
-- INSPECT_SAMPLE_CHECK_ITEMS.AID_CODE/AID_TYPE → SAMPLE_CODE/SAMPLE_TYPE
-- 실적 0건 상태에서만 안전하게 수행한다. 타입은 VARCHAR2 그대로 유지(변경 없음).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'INSPECT_SAMPLE_CHECK_ITEMS' AND COLUMN_NAME = 'AID_CODE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE INSPECT_SAMPLE_CHECK_ITEMS RENAME COLUMN AID_CODE TO SAMPLE_CODE';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'INSPECT_SAMPLE_CHECK_ITEMS' AND COLUMN_NAME = 'AID_TYPE';
  IF n > 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE INSPECT_SAMPLE_CHECK_ITEMS RENAME COLUMN AID_TYPE TO SAMPLE_TYPE';
  END IF;
END;
/

COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.SAMPLE_CODE IS '대조한 견본 코드 (LIMIT_SAMPLES.SAMPLE_CODE)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.SAMPLE_TYPE IS '견본 유형 스냅샷 (OK 양품견본 / NG 불량견본)'
/
COMMENT ON COLUMN INSPECT_SAMPLE_CHECK_ITEMS.EXPECTED_RESULT IS '기대 결과 (양품견본 OK → PASS, 불량견본 NG → FAIL)'
/

COMMIT
/
