DECLARE
  -- Global NOCYCLE numbering and stock invariants. Idempotent for JSHANES.
  -- Dates remain readable metadata; uniqueness comes from a global sequence.
  PROCEDURE ensure_sequence(p_name VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = p_name;
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_name || ' START WITH 1 INCREMENT BY 1 NOCYCLE NOCACHE';
    END IF;
  END;
BEGIN
  ensure_sequence('SEQ_ADJ_TX'); ensure_sequence('SEQ_MISC_TX');
  ensure_sequence('SEQ_PHYS_CNT_TX'); ensure_sequence('SEQ_INV_TX');
  ensure_sequence('SEQ_PRODUCT_TX'); ensure_sequence('SEQ_AUDIT_NO');
  ensure_sequence('SEQ_FAI_NO'); ensure_sequence('SEQ_COMPLAINT_NO');
  ensure_sequence('SEQ_ECN_NO'); ensure_sequence('SEQ_CAPA_CA');
  ensure_sequence('SEQ_CAPA_PA'); ensure_sequence('SEQ_SPC_CHART');
  ensure_sequence('SEQ_CALIBRATION'); ensure_sequence('SEQ_CONTROL_PLAN');
  ensure_sequence('SEQ_REWORK_NO'); ensure_sequence('SEQ_PPAP_NO');
  ensure_sequence('SEQ_DOC_NO'); ensure_sequence('SEQ_OQC_REQUEST');
  ensure_sequence('SEQ_PROD_PLAN_NO'); ensure_sequence('SEQ_PM_WORK_ORDER_NO');
END;
/

MERGE INTO SEQ_RULES t
USING (
  SELECT 'ADJ_TX' d, 'ADJ' p, 'SEQ_ADJ_TX' s, 5 l, 'YYYYMMDD' f, NULL x, '재고보정 수불번호' m FROM DUAL UNION ALL
  SELECT 'MISC_TX','MISC','SEQ_MISC_TX',5,'YYYYMMDD',NULL,'기타입고 수불번호' FROM DUAL UNION ALL
  SELECT 'PHYS_CNT_TX','PHC','SEQ_PHYS_CNT_TX',4,'YYYYMMDD',NULL,'재고실사 수불번호' FROM DUAL UNION ALL
  SELECT 'INV_TX','TRX','SEQ_INV_TX',5,'YYYYMMDD',NULL,'자재입출고 수불번호' FROM DUAL UNION ALL
  SELECT 'PRODUCT_TX','PTX','SEQ_PRODUCT_TX',5,'YYYYMMDD',NULL,'제품입출고 수불번호' FROM DUAL UNION ALL
  SELECT 'AUDIT_NO','AUD','SEQ_AUDIT_NO',3,'YYYYMMDD','-','납품업체심사번호' FROM DUAL UNION ALL
  SELECT 'FAI_NO','FAI','SEQ_FAI_NO',3,'YYYYMMDD','-','초물검사번호' FROM DUAL UNION ALL
  SELECT 'COMPLAINT_NO','CC','SEQ_COMPLAINT_NO',3,'YYYYMMDD','-','고객클레임번호' FROM DUAL UNION ALL
  SELECT 'ECN_NO','ECN','SEQ_ECN_NO',3,'YYYYMMDD','-','4M 변경번호' FROM DUAL UNION ALL
  SELECT 'CAPA_CA','CA','SEQ_CAPA_CA',3,'YYYYMMDD','-','CAPA 시정조치번호' FROM DUAL UNION ALL
  SELECT 'CAPA_PA','PA','SEQ_CAPA_PA',3,'YYYYMMDD','-','CAPA 예방조치번호' FROM DUAL UNION ALL
  SELECT 'SPC_CHART','SPC','SEQ_SPC_CHART',3,'YYYYMMDD','-','관리도번호' FROM DUAL UNION ALL
  SELECT 'CALIBRATION','CAL','SEQ_CALIBRATION',3,'YYYYMMDD','-','교정번호' FROM DUAL UNION ALL
  SELECT 'CONTROL_PLAN','CP','SEQ_CONTROL_PLAN',3,'YYYYMMDD','-','관리계획번호' FROM DUAL UNION ALL
  SELECT 'REWORK_NO','RW','SEQ_REWORK_NO',3,'YYYYMMDD','-','재작업번호' FROM DUAL UNION ALL
  SELECT 'PPAP_NO','PPAP','SEQ_PPAP_NO',3,'YYYYMMDD','-','PPAP 제출번호' FROM DUAL UNION ALL
  SELECT 'DOC_NO','DOC','SEQ_DOC_NO',3,'YYYYMMDD','-','문서번호' FROM DUAL UNION ALL
  SELECT 'OQC_REQUEST','OQC','SEQ_OQC_REQUEST',3,'YYYYMMDD','-','출하검사 요청번호' FROM DUAL
) s
ON (t.DOC_TYPE = s.d)
WHEN MATCHED THEN UPDATE SET t.PREFIX=s.p, t.SEQ_NAME=s.s, t.PAD_LENGTH=s.l,
  t.DATE_FORMAT=s.f, t.SEPARATOR=s.x, t.DESCRIPTION=s.m, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT
  (DOC_TYPE,PREFIX,SEQ_NAME,PAD_LENGTH,DATE_FORMAT,SEPARATOR,DESCRIPTION,USE_YN,COMPANY,PLANT_CD,CREATED_AT)
VALUES (s.d,s.p,s.s,s.l,s.f,s.x,s.m,'Y','40','1000',SYSTIMESTAMP)
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='MAT_STOCKS' AND CONSTRAINT_NAME='CK_MAT_STOCKS_QTY_INVARIANT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE MAT_STOCKS ADD CONSTRAINT CK_MAT_STOCKS_QTY_INVARIANT CHECK (QTY >= 0 AND RESERVED_QTY >= 0 AND AVAILABLE_QTY >= 0 AND AVAILABLE_QTY = QTY - RESERVED_QTY)';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_CONSTRAINTS
   WHERE TABLE_NAME='PRODUCT_STOCKS' AND CONSTRAINT_NAME='CK_PRODUCT_STOCKS_QTY_INVARIANT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PRODUCT_STOCKS ADD CONSTRAINT CK_PRODUCT_STOCKS_QTY_INVARIANT CHECK (QTY >= 0 AND RESERVED_QTY >= 0 AND AVAILABLE_QTY >= 0 AND AVAILABLE_QTY = QTY - RESERVED_QTY)';
  END IF;
END;
/

COMMIT;
/
