-- 보세 사용신고의 COUNT+1 채번을 전역 Oracle SEQUENCE로 대체한다.
DECLARE
  v_exists NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'SEQ_CUSTOMS_USAGE';
  IF v_exists = 0 THEN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR(REPORT_NO, -4))), 0) + 1
      INTO v_start
      FROM CUSTOMS_USAGE_REPORTS
     WHERE REGEXP_LIKE(REPORT_NO, '^USG[0-9]{8}[0-9]{4}$');
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CUSTOMS_USAGE START WITH ' || v_start ||
                      ' INCREMENT BY 1 NOCYCLE NOCACHE';
  END IF;
END;
/
