-- 2026-09-03: 사용자별 메뉴 즐겨찾기 테이블 생성
-- 사이드바 즐겨찾기(★) — 사용자 단위 저장 (공용 PC에서 사용자별 유지 + 기기 간 공유)
-- 실행: python oracle_connector.py --site JSHANES --execute-file <this file>

CREATE TABLE USER_MENU_FAVORITES (
  COMPANY     VARCHAR2(20)   NOT NULL,
  PLANT_CD    VARCHAR2(20)   NOT NULL,
  USER_EMAIL  VARCHAR2(100)  NOT NULL,
  MENU_CODE   VARCHAR2(100)  NOT NULL,
  SORT_ORDER  NUMBER(10,0)   DEFAULT 0 NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CREATED_BY  VARCHAR2(50)   NOT NULL,
  UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_BY  VARCHAR2(50)   NOT NULL,
  CONSTRAINT PK_USER_MENU_FAVORITES PRIMARY KEY (COMPANY, PLANT_CD, USER_EMAIL, MENU_CODE)
)
/
CREATE INDEX IDX_UMF_USER ON USER_MENU_FAVORITES (COMPANY, PLANT_CD, USER_EMAIL, SORT_ORDER)
/
COMMENT ON TABLE USER_MENU_FAVORITES IS '사용자별 사이드바 메뉴 즐겨찾기'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.COMPANY IS '회사 코드'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.PLANT_CD IS '사업장 코드'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.USER_EMAIL IS '사용자 이메일 (USERS.EMAIL)'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.MENU_CODE IS '메뉴 코드 (menuConfig leaf)'
/
COMMENT ON COLUMN USER_MENU_FAVORITES.SORT_ORDER IS '즐겨찾기 표시 순서'
/
