DECLARE
  -- JSHANES: 사용자/회사/사업장별 1단계 즐겨찾기 폴더. 기존 즐겨찾기는 루트(null) 보존.
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME='USER_MENU_FAVORITE_FOLDERS';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE USER_MENU_FAVORITE_FOLDERS (
      ID NUMBER(15,0) NOT NULL,
      COMPANY VARCHAR2(20) NOT NULL,
      PLANT_CD VARCHAR2(20) NOT NULL,
      USER_EMAIL VARCHAR2(100) NOT NULL,
      NAME VARCHAR2(100 CHAR) NOT NULL,
      SORT_ORDER NUMBER(15,0) NOT NULL,
      CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_MENU_FAVORITE_FOLDER PRIMARY KEY (ID),
      CONSTRAINT UK_MENU_FAV_FOLDER_OWNER UNIQUE (COMPANY, PLANT_CD, USER_EMAIL, ID),
      CONSTRAINT CK_MENU_FAV_FOLDER_NAME CHECK (TRIM(NAME) IS NOT NULL)
    )';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME='SEQ_MENU_FAVORITE_FOLDER';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MENU_FAVORITE_FOLDER START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='USER_MENU_FAVORITES' AND COLUMN_NAME='FOLDER_ID';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USER_MENU_FAVORITES ADD (FOLDER_ID NUMBER(15,0))';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_CONSTRAINTS WHERE CONSTRAINT_NAME='FK_MENU_FAV_FOLDER_OWNER';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE USER_MENU_FAVORITES ADD CONSTRAINT FK_MENU_FAV_FOLDER_OWNER FOREIGN KEY (COMPANY, PLANT_CD, USER_EMAIL, FOLDER_ID) REFERENCES USER_MENU_FAVORITE_FOLDERS (COMPANY, PLANT_CD, USER_EMAIL, ID)';
  END IF;
END;
/
COMMENT ON TABLE USER_MENU_FAVORITE_FOLDERS IS '사용자별 메뉴 즐겨찾기 폴더 (1단계)';
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.ID IS '폴더 ID (SEQ_MENU_FAVORITE_FOLDER)';
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.NAME IS '사용자 지정 폴더명';
/
COMMENT ON COLUMN USER_MENU_FAVORITE_FOLDERS.SORT_ORDER IS '폴더 표시 순서';
/
COMMENT ON COLUMN USER_MENU_FAVORITES.FOLDER_ID IS '즐겨찾기 폴더 ID (NULL: 폴더 밖)';
/
