-- JSHANES / COMPANY=40, PLANT_CD=1000
-- 사전 확인: QUALITY 활성, QC_OQC/QC_OQC_HISTORY 배정 없음.
-- MANAGER/OPERATOR 권한 4건은 이미 Y: 권한은 변경하지 않는다.
INSERT INTO MENU_CATEGORY_ITEMS
  (MENU_CODE,CATEGORY_CODE,SORT_ORDER,COMPANY,PLANT_CD,CREATED_BY,UPDATED_BY)
SELECT 'QC_OQC','QUALITY',120,'40','1000','codex','codex' FROM DUAL
WHERE EXISTS (SELECT 1 FROM MENU_CATEGORIES WHERE COMPANY='40' AND PLANT_CD='1000' AND CATEGORY_CODE='QUALITY' AND IS_ACTIVE='Y')
AND NOT EXISTS (SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000' AND MENU_CODE='QC_OQC')
/
INSERT INTO MENU_CATEGORY_ITEMS
  (MENU_CODE,CATEGORY_CODE,SORT_ORDER,COMPANY,PLANT_CD,CREATED_BY,UPDATED_BY)
SELECT 'QC_OQC_HISTORY','QUALITY',130,'40','1000','codex','codex' FROM DUAL
WHERE EXISTS (SELECT 1 FROM MENU_CATEGORIES WHERE COMPANY='40' AND PLANT_CD='1000' AND CATEGORY_CODE='QUALITY' AND IS_ACTIVE='Y')
AND NOT EXISTS (SELECT 1 FROM MENU_CATEGORY_ITEMS WHERE COMPANY='40' AND PLANT_CD='1000' AND MENU_CODE='QC_OQC_HISTORY')
/
