DECLARE
-- JSHANES / 40 / 1000. 사용자 확정: 통전(회로검사) → 육안검사.
-- 기존 공정행 전체를 재정렬하여 공정별 설정은 그대로 보존한다.
-- SEQ는 공정 표시 순서이며 새 ID를 채번하는 작업이 아니다.
  v_visual ROUTING_PROCESSES%ROWTYPE;
  v_continuity ROUTING_PROCESSES%ROWTYPE;
  v_count NUMBER;
BEGIN
  SELECT * INTO v_visual FROM ROUTING_PROCESSES
  WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND PROCESS_CODE='OINSP' FOR UPDATE;
  SELECT * INTO v_continuity FROM ROUTING_PROCESSES
  WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND PROCESS_CODE='CIINS' FOR UPDATE;
  IF v_continuity.SEQ=20 AND v_visual.SEQ=30 THEN RETURN; END IF;
  IF v_visual.SEQ<>20 OR v_continuity.SEQ<>30 THEN
    RAISE_APPLICATION_ERROR(-20001,'Unexpected routing order; no change');
  END IF;
  SELECT COUNT(*) INTO v_count FROM (
    SELECT SEQ FROM ROUTING_MATERIALS WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ IN (20,30)
    UNION ALL
    SELECT SEQ FROM PROCESS_QUALITY_CONDITIONS WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ IN (20,30)
    UNION ALL
    SELECT SEQ FROM ROUTING_PROCESSES WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ=25
  );
  IF v_count<>0 THEN RAISE_APPLICATION_ERROR(-20002,'Dependent step data exists; no change'); END IF;
  UPDATE ROUTING_PROCESSES SET SEQ=25 WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ=20;
  UPDATE ROUTING_PROCESSES SET SEQ=20,UPDATED_BY='codex',UPDATED_AT=SYSTIMESTAMP WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ=30;
  UPDATE ROUTING_PROCESSES SET SEQ=30,UPDATED_BY='codex',UPDATED_AT=SYSTIMESTAMP WHERE COMPANY='40' AND PLANT_CD='1000' AND ROUTING_CODE='RT_MAG_EAD65942601' AND SEQ=25;
EXCEPTION WHEN OTHERS THEN
  ROLLBACK;
  RAISE;
END;
/
