DECLARE
  -- QREKA-PR-025 기반 PFD/PFMEA/Control Plan 통합 문서체계
  -- 대상: JSHANES. 이 파일은 기존 CONTROL_PLANS/CONTROL_PLAN_ITEMS를 변경하지 않는다.
  n NUMBER;
  PROCEDURE ensure_sequence(p_name VARCHAR2, p_ddl VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO n FROM user_sequences WHERE sequence_name = p_name;
    IF n = 0 THEN
      EXECUTE IMMEDIATE p_ddl;
    END IF;
  END;
BEGIN
  ensure_sequence('SEQ_QUALITY_PLAN_PACKAGE', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_PACKAGE START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PLAN_DOCUMENT', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_DOCUMENT START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PLAN_REVISION', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_REVISION START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PROCESS_FLOW_ROW', 'CREATE SEQUENCE SEQ_QUALITY_PROCESS_FLOW_ROW START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PFMEA_ROW', 'CREATE SEQUENCE SEQ_QUALITY_PFMEA_ROW START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_CONTROL_PLAN_ROW', 'CREATE SEQUENCE SEQ_QUALITY_CONTROL_PLAN_ROW START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PLAN_PARTICIPANT', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_PARTICIPANT START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PLAN_VALIDATION', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_VALIDATION START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PLAN_EVENT', 'CREATE SEQUENCE SEQ_QUALITY_PLAN_EVENT START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PFD_NO', 'CREATE SEQUENCE SEQ_QUALITY_PFD_NO START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_PFMEA_NO', 'CREATE SEQUENCE SEQ_QUALITY_PFMEA_NO START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
  ensure_sequence('SEQ_QUALITY_CP_NO', 'CREATE SEQUENCE SEQ_QUALITY_CP_NO START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20');
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_PACKAGES';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_PACKAGES (
    PACKAGE_ID NUMBER(15) NOT NULL, COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    PROJECT_CODE VARCHAR2(50), PROJECT_NAME VARCHAR2(200), CUSTOMER_CODE VARCHAR2(50), CUSTOMER_NAME VARCHAR2(200),
    ITEM_CODE VARCHAR2(50) NOT NULL, ITEM_NAME VARCHAR2(200) NOT NULL, PART_NUMBER VARCHAR2(100),
    PHASE VARCHAR2(20) NOT NULL, ORGANIZATION VARCHAR2(200), KEY_CONTACT VARCHAR2(100),
    CREATED_BY VARCHAR2(50) NOT NULL, UPDATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_PACKAGES PRIMARY KEY (PACKAGE_ID),
    CONSTRAINT UK_QP_PACKAGES_TENANT UNIQUE (COMPANY, PLANT_CD, PACKAGE_ID),
    CONSTRAINT CK_QP_PACKAGE_PHASE CHECK (PHASE IN ('PROTOTYPE','PRE_LAUNCH','PRODUCTION'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_DOCUMENTS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_DOCUMENTS (
    DOCUMENT_ID NUMBER(15) NOT NULL, PACKAGE_ID NUMBER(15) NOT NULL, COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    DOCUMENT_TYPE VARCHAR2(20) NOT NULL, DOCUMENT_NO VARCHAR2(50) NOT NULL, TITLE VARCHAR2(200) NOT NULL,
    TEMPLATE_FORM_NO VARCHAR2(30) NOT NULL, TEMPLATE_REVISION VARCHAR2(10) DEFAULT '00' NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL, CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_DOCUMENTS PRIMARY KEY (DOCUMENT_ID),
    CONSTRAINT UK_QP_DOC_TENANT_ID UNIQUE (COMPANY, PLANT_CD, DOCUMENT_ID),
    CONSTRAINT UK_QP_DOC_NO UNIQUE (COMPANY, PLANT_CD, DOCUMENT_NO),
    CONSTRAINT UK_QP_DOC_TYPE UNIQUE (COMPANY, PLANT_CD, PACKAGE_ID, DOCUMENT_TYPE),
    CONSTRAINT FK_QP_DOC_PACKAGE FOREIGN KEY (COMPANY, PLANT_CD, PACKAGE_ID)
      REFERENCES QUALITY_PLAN_PACKAGES (COMPANY, PLANT_CD, PACKAGE_ID),
    CONSTRAINT CK_QP_DOC_TYPE CHECK (DOCUMENT_TYPE IN ('PFD','PFMEA','CONTROL_PLAN'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_REVISIONS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_REVISIONS (
    REVISION_ID NUMBER(15) NOT NULL, DOCUMENT_ID NUMBER(15) NOT NULL, COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    REVISION_CODE VARCHAR2(10) NOT NULL, STATUS VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL,
    ISSUE_DATE DATE, REVISION_DATE DATE, PUBLISHED_AT TIMESTAMP, CHANGE_REASON VARCHAR2(1000), CHANGE_DESCRIPTION CLOB,
    AUTHOR_ID VARCHAR2(50) NOT NULL, PUBLISHER_ID VARCHAR2(50), REF_PFD_REVISION_ID NUMBER(15), REF_PFMEA_REVISION_ID NUMBER(15),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_REVISIONS PRIMARY KEY (REVISION_ID),
    CONSTRAINT UK_QP_REV_TENANT_ID UNIQUE (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT UK_QP_REV_DOC_CODE UNIQUE (COMPANY, PLANT_CD, DOCUMENT_ID, REVISION_CODE),
    CONSTRAINT FK_QP_REV_DOCUMENT FOREIGN KEY (COMPANY, PLANT_CD, DOCUMENT_ID)
      REFERENCES QUALITY_PLAN_DOCUMENTS (COMPANY, PLANT_CD, DOCUMENT_ID),
    CONSTRAINT FK_QP_REV_PFD FOREIGN KEY (COMPANY, PLANT_CD, REF_PFD_REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT FK_QP_REV_PFMEA FOREIGN KEY (COMPANY, PLANT_CD, REF_PFMEA_REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT CK_QP_REV_STATUS CHECK (STATUS IN ('DRAFT','PUBLISHED','SUPERSEDED'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'UK_QP_REV_ONE_DRAFT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UK_QP_REV_ONE_DRAFT ON QUALITY_PLAN_REVISIONS (
      CASE WHEN STATUS = 'DRAFT' THEN COMPANY END,
      CASE WHEN STATUS = 'DRAFT' THEN PLANT_CD END,
      CASE WHEN STATUS = 'DRAFT' THEN DOCUMENT_ID END
    )~';
  END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PROCESS_FLOW_ROWS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PROCESS_FLOW_ROWS (
    ROW_ID NUMBER(15) NOT NULL, REVISION_ID NUMBER(15) NOT NULL, ROW_SEQ NUMBER(10) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    PROCESS_NO VARCHAR2(30) NOT NULL, PROCESS_CODE VARCHAR2(50), PROCESS_NAME VARCHAR2(200) NOT NULL,
    EQUIPMENT_CODE VARCHAR2(50), EQUIPMENT_NAME VARCHAR2(200), FLOW_LANE VARCHAR2(20) NOT NULL, FLOW_SYMBOL VARCHAR2(30) NOT NULL,
    PRODUCT_SPECIAL_CHAR VARCHAR2(30), PROCESS_SPECIAL_CHAR VARCHAR2(30), DESCRIPTION VARCHAR2(1000),
    CREATED_BY VARCHAR2(50) NOT NULL, UPDATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_PFD_ROWS PRIMARY KEY (ROW_ID),
    CONSTRAINT UK_QP_PFD_TENANT_ID UNIQUE (COMPANY, PLANT_CD, ROW_ID),
    CONSTRAINT UK_QP_PFD_ROW_SEQ UNIQUE (COMPANY, PLANT_CD, REVISION_ID, ROW_SEQ),
    CONSTRAINT FK_QP_PFD_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT CK_QP_PFD_LANE CHECK (FLOW_LANE IN ('SUB','MAIN','OUTSOURCING')),
    CONSTRAINT CK_QP_PFD_SYMBOL CHECK (FLOW_SYMBOL IN ('OPERATION','INSPECTION','TRANSPORT','STORAGE','DELAY','REWORK','QUARANTINE','SHIPPING'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PFMEA_ROWS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PFMEA_ROWS (
    ROW_ID NUMBER(15) NOT NULL, REVISION_ID NUMBER(15) NOT NULL, ROW_SEQ NUMBER(10) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL, PROCESS_FLOW_ROW_ID NUMBER(15) NOT NULL,
    PROCESS_FUNCTION VARCHAR2(500) NOT NULL, REQUIREMENT VARCHAR2(500) NOT NULL,
    FAILURE_MODE VARCHAR2(1000) NOT NULL, FAILURE_EFFECT VARCHAR2(1000) NOT NULL, SEVERITY NUMBER(2) NOT NULL,
    SPECIAL_CHAR_CODE VARCHAR2(30), FAILURE_CAUSE VARCHAR2(1000) NOT NULL, PREVENTION_CONTROL VARCHAR2(1000),
    OCCURRENCE NUMBER(2) NOT NULL, DETECTION_CONTROL VARCHAR2(1000), DETECTION NUMBER(2) NOT NULL, RPN NUMBER(4) NOT NULL,
    RECOMMENDED_ACTION VARCHAR2(2000), RESPONSIBLE_ORG VARCHAR2(200), RESPONSIBLE_PERSON VARCHAR2(100), TARGET_DATE DATE,
    COMPLETED_ACTION VARCHAR2(2000), COMPLETION_DATE DATE, ACTION_SEVERITY NUMBER(2), ACTION_OCCURRENCE NUMBER(2),
    ACTION_DETECTION NUMBER(2), ACTION_RPN NUMBER(4), CREATED_BY VARCHAR2(50) NOT NULL, UPDATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_PFMEA_ROWS PRIMARY KEY (ROW_ID),
    CONSTRAINT UK_QP_PFMEA_TENANT_ID UNIQUE (COMPANY, PLANT_CD, ROW_ID),
    CONSTRAINT UK_QP_PFMEA_ROW_SEQ UNIQUE (COMPANY, PLANT_CD, REVISION_ID, ROW_SEQ),
    CONSTRAINT FK_QP_PFMEA_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT FK_QP_PFMEA_PFD FOREIGN KEY (COMPANY, PLANT_CD, PROCESS_FLOW_ROW_ID)
      REFERENCES QUALITY_PROCESS_FLOW_ROWS (COMPANY, PLANT_CD, ROW_ID),
    CONSTRAINT CK_QP_PFMEA_RANKS CHECK (SEVERITY BETWEEN 1 AND 10 AND OCCURRENCE BETWEEN 1 AND 10 AND DETECTION BETWEEN 1 AND 10)
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_CONTROL_PLAN_ROWS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_CONTROL_PLAN_ROWS (
    ROW_ID NUMBER(15) NOT NULL, REVISION_ID NUMBER(15) NOT NULL, ROW_SEQ NUMBER(10) NOT NULL,
    COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL, PROCESS_FLOW_ROW_ID NUMBER(15) NOT NULL, PFMEA_ROW_ID NUMBER(15),
    PROCESS_NO VARCHAR2(30) NOT NULL, PROCESS_NAME VARCHAR2(200) NOT NULL, EQUIPMENT_CODE VARCHAR2(50), EQUIPMENT_NAME VARCHAR2(200),
    CHARACTERISTIC_NO VARCHAR2(30), PRODUCT_CHARACTERISTIC VARCHAR2(500), PROCESS_CHARACTERISTIC VARCHAR2(500), SPECIAL_CHAR_CODE VARCHAR2(30),
    SPECIFICATION VARCHAR2(1000) NOT NULL, EVALUATION_METHOD VARCHAR2(500) NOT NULL, SAMPLE_SIZE VARCHAR2(50) NOT NULL,
    SAMPLE_FREQUENCY VARCHAR2(100), CONTROL_METHOD VARCHAR2(1000) NOT NULL, RESPONSIBLE_ROLE VARCHAR2(100),
    REACTION_PLAN VARCHAR2(2000) NOT NULL, RECORD_FORM VARCHAR2(500), CREATED_BY VARCHAR2(50) NOT NULL, UPDATED_BY VARCHAR2(50),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_CP_ROWS PRIMARY KEY (ROW_ID),
    CONSTRAINT UK_QP_CP_TENANT_ID UNIQUE (COMPANY, PLANT_CD, ROW_ID),
    CONSTRAINT UK_QP_CP_ROW_SEQ UNIQUE (COMPANY, PLANT_CD, REVISION_ID, ROW_SEQ),
    CONSTRAINT FK_QP_CP_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT FK_QP_CP_PFD FOREIGN KEY (COMPANY, PLANT_CD, PROCESS_FLOW_ROW_ID)
      REFERENCES QUALITY_PROCESS_FLOW_ROWS (COMPANY, PLANT_CD, ROW_ID),
    CONSTRAINT FK_QP_CP_PFMEA FOREIGN KEY (COMPANY, PLANT_CD, PFMEA_ROW_ID)
      REFERENCES QUALITY_PFMEA_ROWS (COMPANY, PLANT_CD, ROW_ID)
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_PARTICIPANTS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_PARTICIPANTS (
    PARTICIPANT_ID NUMBER(15) NOT NULL, REVISION_ID NUMBER(15) NOT NULL, COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL, USER_ID VARCHAR2(50), USER_NAME VARCHAR2(100) NOT NULL, ORGANIZATION VARCHAR2(200),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_PARTICIPANTS PRIMARY KEY (PARTICIPANT_ID),
    CONSTRAINT FK_QP_PART_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT CK_QP_PART_ROLE CHECK (ROLE IN ('AUTHOR','PUBLISHER','KEY_CONTACT'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_VALIDATIONS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_VALIDATIONS (
    VALIDATION_ID NUMBER(15) NOT NULL, REVISION_ID NUMBER(15) NOT NULL, COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL,
    IS_VALID CHAR(1) NOT NULL, ERROR_COUNT NUMBER(10) DEFAULT 0 NOT NULL, WARNING_COUNT NUMBER(10) DEFAULT 0 NOT NULL,
    ISSUES_JSON CLOB NOT NULL, VALIDATED_BY VARCHAR2(50) NOT NULL, VALIDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_VALIDATIONS PRIMARY KEY (VALIDATION_ID),
    CONSTRAINT FK_QP_VALID_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID),
    CONSTRAINT CK_QP_VALID_YN CHECK (IS_VALID IN ('Y','N'))
  )~'; END IF;
END;
/

DECLARE n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name = 'QUALITY_PLAN_EVENTS';
  IF n = 0 THEN EXECUTE IMMEDIATE q'~CREATE TABLE QUALITY_PLAN_EVENTS (
    EVENT_ID NUMBER(15) NOT NULL, PACKAGE_ID NUMBER(15) NOT NULL, DOCUMENT_ID NUMBER(15), REVISION_ID NUMBER(15),
    COMPANY VARCHAR2(50) NOT NULL, PLANT_CD VARCHAR2(20) NOT NULL, EVENT_TYPE VARCHAR2(30) NOT NULL,
    ACTOR_ID VARCHAR2(50) NOT NULL, DETAIL CLOB, OCCURRED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_QP_EVENTS PRIMARY KEY (EVENT_ID),
    CONSTRAINT FK_QP_EVENT_PACKAGE FOREIGN KEY (COMPANY, PLANT_CD, PACKAGE_ID)
      REFERENCES QUALITY_PLAN_PACKAGES (COMPANY, PLANT_CD, PACKAGE_ID),
    CONSTRAINT FK_QP_EVENT_DOCUMENT FOREIGN KEY (COMPANY, PLANT_CD, DOCUMENT_ID)
      REFERENCES QUALITY_PLAN_DOCUMENTS (COMPANY, PLANT_CD, DOCUMENT_ID),
    CONSTRAINT FK_QP_EVENT_REV FOREIGN KEY (COMPANY, PLANT_CD, REVISION_ID)
      REFERENCES QUALITY_PLAN_REVISIONS (COMPANY, PLANT_CD, REVISION_ID)
  )~'; END IF;
END;
/

BEGIN
  -- QREKA-PR-025 편집기에 사용하는 공통코드 (JSHANES 기본 tenant)
  MERGE INTO COM_CODES C
  USING (
    SELECT 'QC_PFD_LANE' GROUP_CODE,'SUB' DETAIL_CODE,'보조 공정' CODE_NAME,NULL ATTR1,1 SORT_ORDER FROM DUAL UNION ALL
    SELECT 'QC_PFD_LANE','MAIN','주 공정',NULL,2 FROM DUAL UNION ALL
    SELECT 'QC_PFD_LANE','OUTSOURCING','외주 공정',NULL,3 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','OPERATION','작업',NULL,1 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','INSPECTION','검사',NULL,2 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','TRANSPORT','운반',NULL,3 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','STORAGE','저장',NULL,4 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','DELAY','지연',NULL,5 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','REWORK','재작업',NULL,6 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','QUARANTINE','격리',NULL,7 FROM DUAL UNION ALL
    SELECT 'QC_PFD_SYMBOL','SHIPPING','출하',NULL,8 FROM DUAL UNION ALL
    SELECT 'QC_SPECIAL_CHAR','SAFETY_REGULATORY','★ 안전/법규 특별특성','★',1 FROM DUAL UNION ALL
    SELECT 'QC_SPECIAL_CHAR','FUNCTION_FIT','◈ 기능/조립 특별특성','◈',2 FROM DUAL UNION ALL
    SELECT 'QC_PLAN_REV_STATUS','DRAFT','작성중','bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200',1 FROM DUAL UNION ALL
    SELECT 'QC_PLAN_REV_STATUS','PUBLISHED','발행','bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-200',2 FROM DUAL UNION ALL
    SELECT 'QC_PLAN_REV_STATUS','SUPERSEDED','구버전','bg-slate-100 text-slate-700 dark:bg-slate-700 dark:text-slate-200',3 FROM DUAL
  ) S ON (C.COMPANY='40' AND C.PLANT_CD='1000' AND C.GROUP_CODE=S.GROUP_CODE AND C.DETAIL_CODE=S.DETAIL_CODE)
  WHEN MATCHED THEN UPDATE SET C.CODE_NAME=S.CODE_NAME,C.ATTR1=S.ATTR1,C.SORT_ORDER=S.SORT_ORDER,C.USE_YN='Y',C.UPDATED_BY='SYSTEM'
  WHEN NOT MATCHED THEN INSERT
    (GROUP_CODE,DETAIL_CODE,CODE_NAME,ATTR1,SORT_ORDER,USE_YN,COMPANY,PLANT_CD,CREATED_BY,UPDATED_BY)
    VALUES (S.GROUP_CODE,S.DETAIL_CODE,S.CODE_NAME,S.ATTR1,S.SORT_ORDER,'Y','40','1000','SYSTEM','SYSTEM');
END;
/
