-- Log sequence creation.
-- Safe to rerun. Existing tables may already contain SEQ values, so each
-- sequence starts after the current max SEQ to avoid primary-key collisions.

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_INTER_LOGS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "INTER_LOGS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INTER_LOGS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_CONSUMABLE_LOGS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "CONSUMABLE_LOGS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CONSUMABLE_LOGS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_CONSUMABLE_MOUNT_LOGS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "CONSUMABLE_MOUNT_LOGS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CONSUMABLE_MOUNT_LOGS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_MOLD_USAGE_LOGS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "MOLD_USAGE_LOGS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_MOLD_USAGE_LOGS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_SCHEDULER_NOTIFICATIONS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("NOTI_ID"), 0) + 1 INTO v_start FROM "SCHEDULER_NOTIFICATIONS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SCHEDULER_NOTIFICATIONS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_SCHEDULER_LOGS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("LOG_ID"), 0) + 1 INTO v_start FROM "SCHEDULER_LOGS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SCHEDULER_LOGS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_PHYSICAL_INV_SESSIONS';
  IF v_count = 0 THEN
    SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "PHYSICAL_INV_SESSIONS";
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_PHYSICAL_INV_SESSIONS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_table_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_SPC_DATA';
  IF v_count = 0 THEN
    SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'SPC_DATA';
    IF v_table_count = 0 THEN
      v_start := 1;
    ELSE
      SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "SPC_DATA";
    END IF;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_SPC_DATA START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_table_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_REPAIR_ORDERS';
  IF v_count = 0 THEN
    SELECT COUNT(*) INTO v_table_count FROM USER_TABLES WHERE TABLE_NAME = 'REPAIR_ORDERS';
    IF v_table_count = 0 THEN
      v_start := 1;
    ELSE
      SELECT NVL(MAX("SEQ"), 0) + 1 INTO v_start FROM "REPAIR_ORDERS";
    END IF;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_REPAIR_ORDERS START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_IQC_TEMPLATES';
  IF v_count = 0 THEN
    SELECT NVL(MAX(TO_NUMBER(SUBSTR("TEMPLATE_ID", 2))), 0) + 1
      INTO v_start
      FROM "IQC_TEMPLATES"
     WHERE REGEXP_LIKE("TEMPLATE_ID", '^T[0-9]+$');
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_IQC_TEMPLATES START WITH ' || v_start || ' INCREMENT BY 1 NOCACHE';
  END IF;
END;
/

COMMIT;
