DECLARE
  -- JSHANES, tenant 40/1000. Retain historical inspection references.
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM EQUIP_MASTERS
  WHERE COMPANY = '40' AND PLANT_CD = '1000'
    AND EQUIP_CODE IN ('EQ-TEST-01', 'EQ-TEST-02') AND USE_YN = 'Y';
  IF v_count <> 2 THEN
    RAISE_APPLICATION_ERROR(-20001, 'Original continuity equipment must remain active');
  END IF;

  FOR e IN (
    SELECT EQUIP_CODE, CREATED_BY, CURRENT_JOB_ORDER_ID, COMM_CONFIG
    FROM EQUIP_MASTERS
    WHERE COMPANY = '40' AND PLANT_CD = '1000'
      AND EQUIP_CODE IN ('EQ-PRC-TEST-01', 'EQ-PRC-TEST-02')
    FOR UPDATE
  ) LOOP
    IF NVL(e.CREATED_BY, '-') <> 'codex' OR e.CURRENT_JOB_ORDER_ID IS NOT NULL
       OR e.COMM_CONFIG IS NOT NULL THEN
      RAISE_APPLICATION_ERROR(-20002, 'Duplicate seed equipment has active configuration');
    END IF;
    SELECT COUNT(*) INTO v_count FROM (
      SELECT 1 FROM EQUIP_PROTOCOLS WHERE COMPANY = '40' AND PLANT_CD = '1000'
        AND EQUIP_CODE = e.EQUIP_CODE AND USE_YN = 'Y'
      UNION ALL
      SELECT 1 FROM JOB_ORDERS WHERE COMPANY = '40' AND PLANT_CD = '1000'
        AND EQUIP_CODE = e.EQUIP_CODE AND STATUS IN ('WAITING', 'RUNNING', 'HOLD')
      UNION ALL
      SELECT 1 FROM WIP_MAT_STOCKS WHERE COMPANY = '40' AND PLANT_CD = '1000'
        AND EQUIP_CODE = e.EQUIP_CODE AND QTY > 0
    );
    IF v_count > 0 THEN
      RAISE_APPLICATION_ERROR(-20003, 'Duplicate equipment has active business usage');
    END IF;
    UPDATE EQUIP_MASTERS SET USE_YN = 'N', UPDATED_BY = 'codex', UPDATED_AT = SYSTIMESTAMP
    WHERE COMPANY = '40' AND PLANT_CD = '1000' AND EQUIP_CODE = e.EQUIP_CODE AND USE_YN = 'Y';
  END LOOP;
EXCEPTION
  WHEN OTHERS THEN ROLLBACK; RAISE;
END;
/
