-- 공정 대차 적재·이동전표·자동 투입 — docs/specs/2026-09-19-process-carrier-flow-design.md 3절·12절
-- 대상: JSHANES company=40 plant=1000. 멱등(존재 확인 후 생성, 코드/메뉴는 MERGE).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 적용 후: ORACLE_SITE=JSHANES python tools/generate_db_schema_doc.py

-- 1) 대차 마스터
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'CARRIER_MASTERS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE CARRIER_MASTERS (
      COMPANY        VARCHAR2(50)   NOT NULL,
      PLANT_CD       VARCHAR2(50)   NOT NULL,
      CARRIER_NO     VARCHAR2(30)   NOT NULL,
      CARRIER_TYPE   VARCHAR2(20)   NOT NULL,
      CARRIER_NAME   VARCHAR2(100),
      CAPACITY       NUMBER,
      USE_YN         CHAR(1)        DEFAULT ''Y'' NOT NULL,
      REMARK         VARCHAR2(500),
      CREATED_BY     VARCHAR2(50),
      UPDATED_BY     VARCHAR2(50),
      CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_CARRIER_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, CARRIER_NO),
      CONSTRAINT CK_CARRIER_MASTERS_TYPE CHECK (CARRIER_TYPE IN (''CART'',''TRAY'',''MAGAZINE'')),
      CONSTRAINT CK_CARRIER_MASTERS_USE_YN CHECK (USE_YN IN (''Y'',''N'')),
      CONSTRAINT CK_CARRIER_MASTERS_CAPACITY CHECK (CAPACITY IS NULL OR CAPACITY > 0)
    )';
    EXECUTE IMMEDIATE q'[COMMENT ON TABLE CARRIER_MASTERS IS '대차/트레이/매거진 마스터 — 생산 라벨·키팅 LOT을 담아 공정 간 이동하는 운반구']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN CARRIER_MASTERS.CARRIER_NO IS '대차번호(바코드 값). 수동 입력']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN CARRIER_MASTERS.CARRIER_TYPE IS '운반구 유형 (COM_CODES CARRIER_TYPE: CART 대차 / TRAY 트레이 / MAGAZINE 매거진)']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN CARRIER_MASTERS.CAPACITY IS '최대 적재 라벨/LOT 수. NULL=무제한']';
  END IF;
END;
/
-- 2) 라벨·LOT·실적·라우팅·설비 컬럼
DECLARE
  PROCEDURE add_col(p_table VARCHAR2, p_col VARCHAR2, p_ddl VARCHAR2, p_comment VARCHAR2) IS
    n NUMBER;
  BEGIN
    SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME = p_table AND COLUMN_NAME = p_col;
    IF n = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_col || ' ' || p_ddl || ')';
    END IF;
    EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || p_table || '.' || p_col || ' IS ''' || p_comment || '''';
  END;
BEGIN
  add_col('SG_LABELS', 'CARRIER_NO', 'VARCHAR2(30)', '현재 담긴 대차번호(CARRIER_MASTERS). 소비/취소 시 NULL');
  add_col('SG_LABELS', 'CARRIER_LOADED_AT', 'TIMESTAMP', '대차 적재 일시');
  add_col('SG_LABELS', 'CARRIER_SLIP_NO', 'VARCHAR2(30)', '이동전표번호. 발행되면 추가 적재 불가·자동투입 허용');
  add_col('FG_LABELS', 'CARRIER_NO', 'VARCHAR2(30)', '현재 담긴 대차번호(CARRIER_MASTERS). 소비/취소 시 NULL');
  add_col('FG_LABELS', 'CARRIER_LOADED_AT', 'TIMESTAMP', '대차 적재 일시');
  add_col('FG_LABELS', 'CARRIER_SLIP_NO', 'VARCHAR2(30)', '이동전표번호');
  add_col('MAT_LOTS', 'CARRIER_NO', 'VARCHAR2(30)', '키팅 출고 시 담긴 대차번호. 설비 장착/출고 취소 시 NULL');
  add_col('MAT_LOTS', 'CARRIER_LOADED_AT', 'TIMESTAMP', '대차 적재 일시');
  add_col('MAT_LOTS', 'CARRIER_SLIP_NO', 'VARCHAR2(30)', '이동전표번호(원자재 대차는 선택)');
  add_col('PROD_RESULTS', 'CARRIER_NO', 'VARCHAR2(30)', '실적 시점 출력 대차번호(보존용)');
  add_col('ROUTING_PROCESSES', 'CARRIER_LOAD_YN', 'CHAR(1) DEFAULT ''N''', '출력측: 이 공정 실적 라벨을 대차에 담는다 Y/N (라벨 발행 공정만 Y 가능)');
  add_col('ROUTING_PROCESSES', 'CARRIER_AUTO_INPUT_YN', 'CHAR(1) DEFAULT ''N''', '입력측: 이 공정에서 대차 스캔 시 담긴 것을 자동 투입한다 Y/N');
  add_col('EQUIP_MASTERS', 'CUR_CARRIER_NO', 'VARCHAR2(30)', '설비의 현재 출력 대차번호(재진입 복원용)');
END;
/
-- 3) 인덱스
DECLARE
  n NUMBER;
BEGIN
  FOR r IN (SELECT 'IX_SG_LABELS_CARRIER' ix, 'SG_LABELS' tb FROM DUAL UNION ALL
            SELECT 'IX_FG_LABELS_CARRIER', 'FG_LABELS' FROM DUAL UNION ALL
            SELECT 'IX_MAT_LOTS_CARRIER', 'MAT_LOTS' FROM DUAL) LOOP
    SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = r.ix;
    IF n = 0 THEN
      EXECUTE IMMEDIATE 'CREATE INDEX ' || r.ix || ' ON ' || r.tb || ' (COMPANY, PLANT_CD, CARRIER_NO)';
    END IF;
  END LOOP;
END;
/
-- 4) 이동전표 시퀀스
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_CARRIER_SLIP';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_CARRIER_SLIP START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/
-- 5) 공통코드 CARRIER_TYPE
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_TYPE' GROUP_CODE,'CART' DETAIL_CODE,'대차' CODE_NAME,1 SORT_ORDER,'bg-blue-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_TYPE' GROUP_CODE,'TRAY' DETAIL_CODE,'트레이' CODE_NAME,2 SORT_ORDER,'bg-teal-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_TYPE' GROUP_CODE,'MAGAZINE' DETAIL_CODE,'매거진' CODE_NAME,3 SORT_ORDER,'bg-purple-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
-- 6) 공통코드 CARRIER_STATUS (현황 화면 배지용, 값은 도출값)
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_STATUS' GROUP_CODE,'EMPTY' DETAIL_CODE,'빈 대차' CODE_NAME,1 SORT_ORDER,'bg-gray-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_STATUS' GROUP_CODE,'LOADING' DETAIL_CODE,'적재 중' CODE_NAME,2 SORT_ORDER,'bg-amber-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'CARRIER_STATUS' GROUP_CODE,'IN_TRANSIT' DETAIL_CODE,'이동 중' CODE_NAME,3 SORT_ORDER,'bg-green-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
-- 7) 메뉴: 기준정보 대차관리, 생산 대차현황 — 각 카테고리 SORT_ORDER MAX+1(끝 배치). 표시 순서는 프론트 menuConfig children 순서가 우선.
MERGE INTO MENU_CATEGORY_ITEMS t
USING (SELECT 'MST_CARRIER' MENU_CODE, 'MASTER' CATEGORY_CODE,
              (SELECT NVL(MAX(SORT_ORDER),0)+1 FROM MENU_CATEGORY_ITEMS WHERE CATEGORY_CODE='MASTER' AND COMPANY='40' AND PLANT_CD='1000') SORT_ORDER,
              '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/
MERGE INTO MENU_CATEGORY_ITEMS t
USING (SELECT 'PROD_CARRIER_STATUS' MENU_CODE, 'PRODUCTION' CATEGORY_CODE,
              (SELECT NVL(MAX(SORT_ORDER),0)+1 FROM MENU_CATEGORY_ITEMS WHERE CATEGORY_CODE='PRODUCTION' AND COMPANY='40' AND PLANT_CD='1000') SORT_ORDER,
              '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/
COMMIT
/
