-- E50 TUBE 절단기·커넥터 마킹기 설비마스터 등록 + 일상점검 항목 연결
-- JSHANES 40/1000. MERGE 멱등.

MERGE INTO EQUIP_MASTERS t
USING (
  SELECT 'EQ-TUBCT-01' C, 'TUBE 절단기 #1' N, 'SINGLE_CUT' T, 'LINE-04' L FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', '커넥터 마킹기 #1', 'LABEL_PRINTER', 'LINE-04' FROM dual
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.EQUIP_CODE = s.C)
WHEN MATCHED THEN UPDATE SET
  t.EQUIP_NAME = s.N, t.EQUIP_TYPE = s.T, t.LINE_CODE = s.L,
  t.STATUS = 'NORMAL', t.USE_YN = 'Y',
  t.UPDATED_BY = 'thn-e50-seed', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  EQUIP_CODE, EQUIP_NAME, EQUIP_TYPE, LINE_CODE, STATUS, USE_YN,
  COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  s.C, s.N, s.T, s.L, 'NORMAL', 'Y',
  '40', '1000', 'thn-e50-seed', 'thn-e50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

MERGE INTO EQUIP_INSPECT_ITEM_MASTERS t
USING (
  SELECT 'EI-E50-01' C, 'TUBE절단기 전원 ON/OFF' N, 'SINGLE_CUT' ET, 'VISUAL' TY,
         '전원 ON/OFF, 시작/멈춤이 정상일 것.' R FROM dual UNION ALL
  SELECT 'EI-E50-02', 'TUBE절단기 SPEED 조절', 'SINGLE_CUT', 'VISUAL',
         'SPEED 조절이 정상적일 것.' FROM dual UNION ALL
  SELECT 'EI-E50-03', '절단 CUTTER 마모', 'SINGLE_CUT', 'VISUAL',
         '절단 CUTTER 마모상태 확인할 것. 이상 시 부품 교체.' FROM dual UNION ALL
  SELECT 'EI-E50-04', '이송 ROLLER FEEDING', 'SINGLE_CUT', 'VISUAL',
         'FEEDING 상태가 양호할 것. 절단 후 길이 산포가 없을 것.' FROM dual UNION ALL
  SELECT 'EI-E50-05', 'ROLLER UP/DOWN·LOCK', 'SINGLE_CUT', 'VISUAL',
         'ROLLER UP/DOWN 조절 및 LOCK''G가 정상일 것.' FROM dual UNION ALL
  SELECT 'EI-E50-06', '커넥터 마킹기 전원', 'LABEL_PRINTER', 'VISUAL',
         '전원 ON/OFF가 정상일 것.' FROM dual UNION ALL
  SELECT 'EI-E50-07', '마킹기 잉크·희석제', 'LABEL_PRINTER', 'VISUAL',
         '희석제(왼쪽)·잉크량(오른쪽) 5% 이상. 0%이면 희석부용 교체.' FROM dual UNION ALL
  SELECT 'EI-E50-08', '커넥터 고정지그', 'LABEL_PRINTER', 'VISUAL',
         '이물질이 없고 커넥터 삽입 시 간섭이 없을 것.' FROM dual
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.ITEM_CODE = s.C)
WHEN MATCHED THEN UPDATE SET
  t.ITEM_NAME = s.N, t.INSPECT_TYPE = 'DAILY', t.EQUIP_TYPE = s.ET, t.ITEM_TYPE = s.TY,
  t.CRITERIA = s.R, t.CYCLE = 'DAILY', t.USE_YN = 'Y',
  t.REMARK = 'THN E50 TUBE절단/커넥터마킹 일상점검',
  t.UPDATED_BY = 'thn-e50-seed', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, ITEM_NAME, INSPECT_TYPE, EQUIP_TYPE, ITEM_TYPE,
  CRITERIA, CYCLE, USE_YN, REMARK, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  '40', '1000', s.C, s.N, 'DAILY', s.ET, s.TY, s.R, 'DAILY', 'Y',
  'THN E50 TUBE절단/커넥터마킹 일상점검',
  'thn-e50-seed', 'thn-e50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

MERGE INTO EQUIP_INSPECT_ITEM_POOL t
USING (
  SELECT 'EQ-TUBCT-01' E, 'EI-E50-01' I, 10 S FROM dual UNION ALL
  SELECT 'EQ-TUBCT-01', 'EI-E50-02', 20 FROM dual UNION ALL
  SELECT 'EQ-TUBCT-01', 'EI-E50-03', 30 FROM dual UNION ALL
  SELECT 'EQ-TUBCT-01', 'EI-E50-04', 40 FROM dual UNION ALL
  SELECT 'EQ-TUBCT-01', 'EI-E50-05', 50 FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', 'EI-E50-06', 10 FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', 'EI-E50-07', 20 FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', 'EI-E50-08', 30 FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', 'EI-LBP-001', 40 FROM dual UNION ALL
  SELECT 'EQ-CNMRK-01', 'EI-LBP-002', 50 FROM dual
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.EQUIP_CODE = s.E
    AND t.ITEM_CODE = s.I AND t.INSPECT_TYPE = 'DAILY')
WHEN MATCHED THEN UPDATE SET
  t.USE_YN = 'Y', t.SORT_SEQ = s.S, t.UPDATED_BY = 'thn-e50-seed', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, EQUIP_CODE, ITEM_CODE, INSPECT_TYPE, USE_YN, SORT_SEQ,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  '40', '1000', s.E, s.I, 'DAILY', 'Y', s.S,
  'thn-e50-seed', 'thn-e50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

COMMIT
/
