-- 검사기별 검사유형 관리. 관련 검사 화면은 이 값으로 TESTER 설비를 제한한다.
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM USER_TAB_COLUMNS
  WHERE TABLE_NAME = 'EQUIP_MASTERS' AND COLUMN_NAME = 'INSPECT_TYPE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_MASTERS ADD (INSPECT_TYPE VARCHAR2(50))';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN EQUIP_MASTERS.INSPECT_TYPE IS '검사기 검사유형 (COM_CODES.INSPECT_TYPE). 검사 화면 설비 필터 기준']';
  END IF;
END;
/

UPDATE EQUIP_MASTERS
SET INSPECT_TYPE = CASE
  WHEN EQUIP_CODE IN ('EQ-TEST-01', 'EQ-TEST-02', 'EQ-PRC-TEST-01', 'EQ-PRC-TEST-02') THEN 'CONTINUITY'
  WHEN EQUIP_CODE IN ('EQ-TINSP-01', 'EQ-TINSP-02') THEN 'TERMINAL'
  WHEN EQUIP_CODE = 'EQ-TORQUE-01' THEN 'TORQUE'
  WHEN EQUIP_CODE = 'EQ-VISION-01' THEN 'VISION'
  WHEN EQUIP_CODE = 'EQ-RELAY-01' THEN 'RELAY_FUNCTION'
  WHEN EQUIP_CODE IN ('EQ-OINSP-01', 'EQ-OINSP-02') THEN 'VISUAL'
  ELSE INSPECT_TYPE
END,
UPDATED_BY = 'equip-inspect-type',
UPDATED_AT = SYSTIMESTAMP
WHERE COMPANY = '40' AND PLANT_CD = '1000' AND EQUIP_TYPE = 'TESTER'
  AND EQUIP_CODE IN (
    'EQ-TEST-01', 'EQ-TEST-02', 'EQ-PRC-TEST-01', 'EQ-PRC-TEST-02',
    'EQ-TINSP-01', 'EQ-TINSP-02', 'EQ-TORQUE-01', 'EQ-VISION-01',
    'EQ-RELAY-01', 'EQ-OINSP-01', 'EQ-OINSP-02'
  )
/

COMMIT
/
