DECLARE
  -- CONTROL_PLANS / CONTROL_PLAN_ITEMS -> QREKA-PR-025 통합 문서체계 이관
  -- 2026-09-15 JSHANES pre-check: header 0, item 0, orphan 0.
  -- CC -> SAFETY_REGULATORY(★), SC/HI -> FUNCTION_FIT(◈).
  V_AMBIGUOUS NUMBER;
BEGIN
  SELECT COUNT(*) INTO V_AMBIGUOUS FROM (
    SELECT COMPANY,PLANT_CD,ITEM_CODE,PHASE
      FROM CONTROL_PLANS
     GROUP BY COMPANY,PLANT_CD,ITEM_CODE,PHASE
    HAVING COUNT(DISTINCT PLAN_NO)>1
  );
  IF V_AMBIGUOUS > 0 THEN
    RAISE_APPLICATION_ERROR(-20091, 'Legacy Control Plan 계보가 모호합니다. itemCode/phase 중복을 수동 검토하세요.');
  END IF;
END;
/

DECLARE
  V_PACKAGE_ID NUMBER;
  V_PFD_DOCUMENT_ID NUMBER;
  V_PFMEA_DOCUMENT_ID NUMBER;
  V_CP_DOCUMENT_ID NUMBER;
  V_PFD_REVISION_ID NUMBER;
  V_PFMEA_REVISION_ID NUMBER;
  V_CP_REVISION_ID NUMBER;
  V_PFD_ROW_ID NUMBER;
  V_PFMEA_ROW_ID NUMBER;
  V_ITEM_COUNT NUMBER;
  V_REV_CODE VARCHAR2(10);
  V_STATUS VARCHAR2(20);
  V_PHASE VARCHAR2(20);
BEGIN
  -- 한 PLAN_NO 계보당 패키지와 문서는 한 번만 만들고, 기존 REVISION_NO별 Revision을 그 아래에 적재한다.
  FOR G IN (
    SELECT P.COMPANY,P.PLANT_CD,P.ITEM_CODE,P.PHASE,P.PLAN_NO,
           MAX(P.ITEM_NAME) AS ITEM_NAME,MAX(P.CREATED_BY) AS CREATED_BY,MAX(P.UPDATED_BY) AS UPDATED_BY,
           MIN(P.CREATED_AT) AS CREATED_AT,MAX(P.UPDATED_AT) AS UPDATED_AT,MAX(P.REVISION_NO) AS MAX_REVISION_NO
      FROM CONTROL_PLANS P
     WHERE NOT EXISTS (
       SELECT 1 FROM QUALITY_PLAN_DOCUMENTS D
        WHERE D.COMPANY=P.COMPANY AND D.PLANT_CD=P.PLANT_CD AND D.DOCUMENT_NO=P.PLAN_NO
     )
     GROUP BY P.COMPANY,P.PLANT_CD,P.ITEM_CODE,P.PHASE,P.PLAN_NO
     ORDER BY P.COMPANY,P.PLANT_CD,P.ITEM_CODE,P.PHASE,P.PLAN_NO
  ) LOOP
    V_PACKAGE_ID := SEQ_QUALITY_PLAN_PACKAGE.NEXTVAL;
    V_PFD_DOCUMENT_ID := SEQ_QUALITY_PLAN_DOCUMENT.NEXTVAL;
    V_PFMEA_DOCUMENT_ID := SEQ_QUALITY_PLAN_DOCUMENT.NEXTVAL;
    V_CP_DOCUMENT_ID := SEQ_QUALITY_PLAN_DOCUMENT.NEXTVAL;
    V_PHASE := CASE G.PHASE WHEN 'PROTOTYPE' THEN 'PROTOTYPE' WHEN 'PRE_LAUNCH' THEN 'PRE_LAUNCH' ELSE 'PRODUCTION' END;

    INSERT INTO QUALITY_PLAN_PACKAGES
      (PACKAGE_ID,COMPANY,PLANT_CD,ITEM_CODE,ITEM_NAME,PHASE,CREATED_BY,UPDATED_BY,CREATED_AT,UPDATED_AT)
    VALUES
      (V_PACKAGE_ID,G.COMPANY,G.PLANT_CD,G.ITEM_CODE,NVL(G.ITEM_NAME,G.ITEM_CODE),V_PHASE,
       NVL(G.CREATED_BY,'MIGRATION'),NVL(G.UPDATED_BY,G.CREATED_BY),G.CREATED_AT,G.UPDATED_AT);

    INSERT INTO QUALITY_PLAN_DOCUMENTS
      (DOCUMENT_ID,PACKAGE_ID,COMPANY,PLANT_CD,DOCUMENT_TYPE,DOCUMENT_NO,TITLE,TEMPLATE_FORM_NO,TEMPLATE_REVISION,CREATED_BY,CREATED_AT)
    VALUES (V_PFD_DOCUMENT_ID,V_PACKAGE_ID,G.COMPANY,G.PLANT_CD,'PFD',SUBSTR(G.PLAN_NO||'-PFD',1,50),'공정흐름도','QREKA-PR-025-01','00',NVL(G.CREATED_BY,'MIGRATION'),G.CREATED_AT);
    INSERT INTO QUALITY_PLAN_DOCUMENTS
      (DOCUMENT_ID,PACKAGE_ID,COMPANY,PLANT_CD,DOCUMENT_TYPE,DOCUMENT_NO,TITLE,TEMPLATE_FORM_NO,TEMPLATE_REVISION,CREATED_BY,CREATED_AT)
    VALUES (V_PFMEA_DOCUMENT_ID,V_PACKAGE_ID,G.COMPANY,G.PLANT_CD,'PFMEA',SUBSTR(G.PLAN_NO||'-PFMEA',1,50),'공정 FMEA','QREKA-PR-025-02','00',NVL(G.CREATED_BY,'MIGRATION'),G.CREATED_AT);
    INSERT INTO QUALITY_PLAN_DOCUMENTS
      (DOCUMENT_ID,PACKAGE_ID,COMPANY,PLANT_CD,DOCUMENT_TYPE,DOCUMENT_NO,TITLE,TEMPLATE_FORM_NO,TEMPLATE_REVISION,CREATED_BY,CREATED_AT)
    VALUES (V_CP_DOCUMENT_ID,V_PACKAGE_ID,G.COMPANY,G.PLANT_CD,'CONTROL_PLAN',G.PLAN_NO,'관리계획서','QREKA-PR-025-04','00',NVL(G.CREATED_BY,'MIGRATION'),G.CREATED_AT);

    FOR H IN (
      SELECT P.* FROM CONTROL_PLANS P
       WHERE P.COMPANY=G.COMPANY AND P.PLANT_CD=G.PLANT_CD AND P.PLAN_NO=G.PLAN_NO
       ORDER BY P.REVISION_NO
    ) LOOP
      V_PFD_REVISION_ID := SEQ_QUALITY_PLAN_REVISION.NEXTVAL;
      V_PFMEA_REVISION_ID := SEQ_QUALITY_PLAN_REVISION.NEXTVAL;
      V_CP_REVISION_ID := SEQ_QUALITY_PLAN_REVISION.NEXTVAL;
      V_REV_CODE := LPAD(TO_CHAR(H.REVISION_NO),2,'0');
      SELECT COUNT(*) INTO V_ITEM_COUNT
        FROM CONTROL_PLAN_ITEMS
       WHERE CONTROL_PLAN_ID=H.PLAN_NO AND COMPANY=H.COMPANY AND PLANT_CD=H.PLANT_CD;
      V_STATUS := CASE
        -- 행이 없는 레거시 문서는 현재 발행 불변식을 만족하지 않으므로 검토용 DRAFT로 이관한다.
        WHEN V_ITEM_COUNT = 0 THEN 'DRAFT'
        WHEN H.REVISION_NO <> G.MAX_REVISION_NO THEN 'SUPERSEDED'
        WHEN H.STATUS = 'APPROVED' THEN 'PUBLISHED'
        WHEN H.STATUS = 'OBSOLETE' THEN 'SUPERSEDED'
        ELSE 'DRAFT'
      END;

      INSERT INTO QUALITY_PLAN_REVISIONS
        (REVISION_ID,DOCUMENT_ID,COMPANY,PLANT_CD,REVISION_CODE,STATUS,REVISION_DATE,PUBLISHED_AT,CHANGE_REASON,CHANGE_DESCRIPTION,AUTHOR_ID,PUBLISHER_ID,CREATED_AT,UPDATED_AT)
      VALUES (V_PFD_REVISION_ID,V_PFD_DOCUMENT_ID,H.COMPANY,H.PLANT_CD,V_REV_CODE,V_STATUS,H.REVISION_DATE,
        CASE WHEN V_STATUS IN ('PUBLISHED','SUPERSEDED') THEN NVL(H.APPROVED_AT,H.UPDATED_AT) END,'Legacy Control Plan 이관',NVL(H.REMARK,'Legacy Revision 이관'),NVL(H.CREATED_BY,'MIGRATION'),H.APPROVED_BY,H.CREATED_AT,H.UPDATED_AT);
      INSERT INTO QUALITY_PLAN_REVISIONS
        (REVISION_ID,DOCUMENT_ID,COMPANY,PLANT_CD,REVISION_CODE,STATUS,REVISION_DATE,PUBLISHED_AT,CHANGE_REASON,CHANGE_DESCRIPTION,AUTHOR_ID,PUBLISHER_ID,REF_PFD_REVISION_ID,CREATED_AT,UPDATED_AT)
      VALUES (V_PFMEA_REVISION_ID,V_PFMEA_DOCUMENT_ID,H.COMPANY,H.PLANT_CD,V_REV_CODE,V_STATUS,H.REVISION_DATE,
        CASE WHEN V_STATUS IN ('PUBLISHED','SUPERSEDED') THEN NVL(H.APPROVED_AT,H.UPDATED_AT) END,'Legacy Control Plan 이관',NVL(H.REMARK,'Legacy Revision 이관'),NVL(H.CREATED_BY,'MIGRATION'),H.APPROVED_BY,V_PFD_REVISION_ID,H.CREATED_AT,H.UPDATED_AT);
      INSERT INTO QUALITY_PLAN_REVISIONS
        (REVISION_ID,DOCUMENT_ID,COMPANY,PLANT_CD,REVISION_CODE,STATUS,REVISION_DATE,PUBLISHED_AT,CHANGE_REASON,CHANGE_DESCRIPTION,
         AUTHOR_ID,PUBLISHER_ID,REF_PFD_REVISION_ID,REF_PFMEA_REVISION_ID,CREATED_AT,UPDATED_AT)
      VALUES (V_CP_REVISION_ID,V_CP_DOCUMENT_ID,H.COMPANY,H.PLANT_CD,V_REV_CODE,V_STATUS,H.REVISION_DATE,
        CASE WHEN V_STATUS IN ('PUBLISHED','SUPERSEDED') THEN NVL(H.APPROVED_AT,H.UPDATED_AT) END,'Legacy Control Plan 이관',NVL(H.REMARK,'Legacy Revision 이관'),
        NVL(H.CREATED_BY,'MIGRATION'),H.APPROVED_BY,V_PFD_REVISION_ID,V_PFMEA_REVISION_ID,H.CREATED_AT,H.UPDATED_AT);

      FOR I IN (SELECT * FROM CONTROL_PLAN_ITEMS WHERE CONTROL_PLAN_ID=H.PLAN_NO AND COMPANY=H.COMPANY AND PLANT_CD=H.PLANT_CD ORDER BY SEQ) LOOP
        V_PFD_ROW_ID := SEQ_QUALITY_PROCESS_FLOW_ROW.NEXTVAL;
        V_PFMEA_ROW_ID := SEQ_QUALITY_PFMEA_ROW.NEXTVAL;
        INSERT INTO QUALITY_PROCESS_FLOW_ROWS
          (ROW_ID,REVISION_ID,ROW_SEQ,COMPANY,PLANT_CD,PROCESS_NO,PROCESS_CODE,PROCESS_NAME,FLOW_LANE,FLOW_SYMBOL,DESCRIPTION,CREATED_BY,UPDATED_BY,CREATED_AT,UPDATED_AT)
        VALUES (V_PFD_ROW_ID,V_PFD_REVISION_ID,I.SEQ,H.COMPANY,H.PLANT_CD,TO_CHAR(I.SEQ),I.PROCESS_CODE,I.PROCESS_NAME,'MAIN','OPERATION','Legacy Control Plan 항목에서 생성',NVL(I.CREATED_BY,'MIGRATION'),NVL(I.CREATED_BY,'MIGRATION'),I.CREATED_AT,I.CREATED_AT);

        -- 레거시에는 PFMEA 원본이 없으므로 CP의 명시 정보만 사용해 추적 가능한 검토용 PFMEA 행을 만든다.
        INSERT INTO QUALITY_PFMEA_ROWS
          (ROW_ID,REVISION_ID,ROW_SEQ,COMPANY,PLANT_CD,PROCESS_FLOW_ROW_ID,PROCESS_FUNCTION,REQUIREMENT,
           FAILURE_MODE,FAILURE_EFFECT,SEVERITY,SPECIAL_CHAR_CODE,FAILURE_CAUSE,PREVENTION_CONTROL,
           OCCURRENCE,DETECTION_CONTROL,DETECTION,RPN,RECOMMENDED_ACTION,CREATED_BY,UPDATED_BY,CREATED_AT,UPDATED_AT)
        VALUES
          (V_PFMEA_ROW_ID,V_PFMEA_REVISION_ID,I.SEQ,H.COMPANY,H.PLANT_CD,V_PFD_ROW_ID,NVL(I.PROCESS_NAME,'Legacy 공정'),
           NVL(I.SPECIFICATION,NVL(I.PRODUCT_CHARACTERISTIC,NVL(I.PROCESS_CHARACTERISTIC,'Legacy 요구사항 확인 필요'))),
           SUBSTR(NVL(I.PRODUCT_CHARACTERISTIC,NVL(I.PROCESS_CHARACTERISTIC,NVL(I.PROCESS_NAME,'공정'))) || ' 규격 이탈',1,1000),
           '품질 요구사항 불충족',1,
           CASE I.SPECIAL_CHAR_CLASS WHEN 'CC' THEN 'SAFETY_REGULATORY' WHEN 'SC' THEN 'FUNCTION_FIT' WHEN 'HI' THEN 'FUNCTION_FIT' ELSE NULL END,
           'Legacy Control Plan 이관 - 원인 검토 필요',NVL(I.CONTROL_METHOD,'Legacy 예방관리 확인 필요'),1,
           NVL(I.EVAL_METHOD,'Legacy 검출관리 확인 필요'),1,1,NVL(I.REACTION_PLAN,'Legacy 권고조치 확인 필요'),
           NVL(I.CREATED_BY,'MIGRATION'),NVL(I.CREATED_BY,'MIGRATION'),I.CREATED_AT,I.CREATED_AT);

        INSERT INTO QUALITY_CONTROL_PLAN_ROWS
          (ROW_ID,REVISION_ID,ROW_SEQ,COMPANY,PLANT_CD,PROCESS_FLOW_ROW_ID,PFMEA_ROW_ID,PROCESS_NO,PROCESS_NAME,CHARACTERISTIC_NO,
           PRODUCT_CHARACTERISTIC,PROCESS_CHARACTERISTIC,SPECIAL_CHAR_CODE,SPECIFICATION,EVALUATION_METHOD,SAMPLE_SIZE,SAMPLE_FREQUENCY,
           CONTROL_METHOD,REACTION_PLAN,RECORD_FORM,CREATED_BY,UPDATED_BY,CREATED_AT,UPDATED_AT)
        VALUES
          (SEQ_QUALITY_CONTROL_PLAN_ROW.NEXTVAL,V_CP_REVISION_ID,I.SEQ,H.COMPANY,H.PLANT_CD,V_PFD_ROW_ID,V_PFMEA_ROW_ID,TO_CHAR(I.SEQ),I.PROCESS_NAME,I.CHARACTERISTIC_NO,
           I.PRODUCT_CHARACTERISTIC,I.PROCESS_CHARACTERISTIC,CASE I.SPECIAL_CHAR_CLASS WHEN 'CC' THEN 'SAFETY_REGULATORY' WHEN 'SC' THEN 'FUNCTION_FIT' WHEN 'HI' THEN 'FUNCTION_FIT' ELSE NULL END,
           NVL(I.SPECIFICATION,'Legacy 확인 필요'),NVL(I.EVAL_METHOD,'Legacy 확인 필요'),NVL(I.SAMPLE_SIZE,'미정'),I.SAMPLE_FREQ,
           NVL(I.CONTROL_METHOD,'Legacy 확인 필요'),NVL(I.REACTION_PLAN,'Legacy 확인 필요'),I.REMARK,NVL(I.CREATED_BY,'MIGRATION'),NVL(I.CREATED_BY,'MIGRATION'),I.CREATED_AT,I.CREATED_AT);
      END LOOP;

      INSERT INTO QUALITY_PLAN_EVENTS
        (EVENT_ID,PACKAGE_ID,DOCUMENT_ID,REVISION_ID,COMPANY,PLANT_CD,EVENT_TYPE,ACTOR_ID,DETAIL,OCCURRED_AT)
      VALUES (SEQ_QUALITY_PLAN_EVENT.NEXTVAL,V_PACKAGE_ID,V_CP_DOCUMENT_ID,V_CP_REVISION_ID,H.COMPANY,H.PLANT_CD,'MIGRATED',NVL(H.UPDATED_BY,'MIGRATION'),'legacy planNo='||H.PLAN_NO||', revision='||V_REV_CODE,SYSTIMESTAMP);
    END LOOP;
  END LOOP;
END;
/
