DECLARE
  -- 이미 적용된 환경의 인덱스를 교정한다. 함수 기반 unique index의 비대상 행은
  -- 모든 index expression이 NULL이어야 index에서 제외된다.
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'UK_QP_REV_ONE_DRAFT';

  IF n > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX UK_QP_REV_ONE_DRAFT';
  END IF;

  EXECUTE IMMEDIATE q'~CREATE UNIQUE INDEX UK_QP_REV_ONE_DRAFT ON QUALITY_PLAN_REVISIONS (
    CASE WHEN STATUS = 'DRAFT' THEN COMPANY END,
    CASE WHEN STATUS = 'DRAFT' THEN PLANT_CD END,
    CASE WHEN STATUS = 'DRAFT' THEN DOCUMENT_ID END
  )~';
END;
/
