-- JSHANES: ITEM_MASTERS -> IQC_AQL_POLICIES tenant-scoped integrity
-- Oracle DDL commits implicitly. Every block is idempotent so a partial run can be resumed safely.

DECLARE
  v_parent_key NUMBER;
  v_type_match NUMBER;
  v_orphans NUMBER;
  v_fk_exists NUMBER;
  v_fk_matches NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_parent_key
    FROM (
      SELECT c.CONSTRAINT_NAME,
             LISTAGG(cc.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY cc.POSITION) AS COLS
        FROM USER_CONSTRAINTS c
        JOIN USER_CONS_COLUMNS cc ON cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
       WHERE c.TABLE_NAME = 'IQC_AQL_POLICIES'
         AND c.CONSTRAINT_TYPE IN ('P', 'U')
         AND c.STATUS = 'ENABLED'
         AND c.VALIDATED = 'VALIDATED'
       GROUP BY c.CONSTRAINT_NAME
    )
   WHERE COLS = 'COMPANY,PLANT_CD,POLICY_CODE';

  IF v_parent_key <> 1 THEN
    RAISE_APPLICATION_ERROR(-20001, 'IQC_AQL_POLICIES tenant policy key is missing or invalid');
  END IF;

  SELECT COUNT(*)
    INTO v_type_match
    FROM (
      SELECT 'COMPANY' child_col, 'COMPANY' parent_col FROM DUAL
      UNION ALL SELECT 'PLANT_CD', 'PLANT_CD' FROM DUAL
      UNION ALL SELECT 'IQC_AQL_POLICY_CODE', 'POLICY_CODE' FROM DUAL
    ) m
    JOIN USER_TAB_COLUMNS child
      ON child.TABLE_NAME = 'ITEM_MASTERS' AND child.COLUMN_NAME = m.child_col
    JOIN USER_TAB_COLUMNS parent
      ON parent.TABLE_NAME = 'IQC_AQL_POLICIES' AND parent.COLUMN_NAME = m.parent_col
   WHERE child.DATA_TYPE = parent.DATA_TYPE
     AND NVL(child.DATA_LENGTH, -1) = NVL(parent.DATA_LENGTH, -1);

  IF v_type_match <> 3 THEN
    RAISE_APPLICATION_ERROR(-20002, 'ITEM_MASTERS and IQC_AQL_POLICIES FK column types do not match');
  END IF;

  SELECT COUNT(*)
    INTO v_orphans
    FROM ITEM_MASTERS i
    LEFT JOIN IQC_AQL_POLICIES p
      ON p.COMPANY = i.COMPANY
     AND p.PLANT_CD = i.PLANT_CD
     AND p.POLICY_CODE = UPPER(TRIM(i.IQC_AQL_POLICY_CODE))
   WHERE i.IQC_AQL_POLICY_CODE IS NOT NULL
     AND NVL(UPPER(TRIM(i.IQC_FLAG)), 'Y') = 'Y'
     AND NVL(UPPER(TRIM(i.INSPECT_METHOD)), '(NULL)') NOT IN ('SKIP', 'NONE')
     AND p.POLICY_CODE IS NULL;

  IF v_orphans <> 0 THEN
    RAISE_APPLICATION_ERROR(-20003, 'Orphan IQC AQL policy links must be corrected before migration');
  END IF;

  SELECT COUNT(*) INTO v_fk_exists
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_ITEM_MASTERS_IQC_AQL_POLICY';

  IF v_fk_exists > 0 THEN
    SELECT COUNT(*)
      INTO v_fk_matches
      FROM (
        SELECT c.CONSTRAINT_NAME,
               c.STATUS,
               c.VALIDATED,
               r.TABLE_NAME AS PARENT_TABLE,
               LISTAGG(cc.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY cc.POSITION) AS CHILD_COLS,
               LISTAGG(rc.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY rc.POSITION) AS PARENT_COLS
          FROM USER_CONSTRAINTS c
          JOIN USER_CONS_COLUMNS cc ON cc.CONSTRAINT_NAME = c.CONSTRAINT_NAME
          JOIN USER_CONSTRAINTS r ON r.CONSTRAINT_NAME = c.R_CONSTRAINT_NAME
          JOIN USER_CONS_COLUMNS rc
            ON rc.CONSTRAINT_NAME = r.CONSTRAINT_NAME AND rc.POSITION = cc.POSITION
         WHERE c.CONSTRAINT_NAME = 'FK_ITEM_MASTERS_IQC_AQL_POLICY'
           AND c.CONSTRAINT_TYPE = 'R'
         GROUP BY c.CONSTRAINT_NAME, c.STATUS, c.VALIDATED, r.TABLE_NAME
      )
     WHERE STATUS = 'ENABLED'
       AND VALIDATED = 'VALIDATED'
       AND PARENT_TABLE = 'IQC_AQL_POLICIES'
       AND CHILD_COLS = 'COMPANY,PLANT_CD,IQC_AQL_POLICY_CODE'
       AND PARENT_COLS = 'COMPANY,PLANT_CD,POLICY_CODE';

    IF v_fk_matches <> 1 THEN
      RAISE_APPLICATION_ERROR(-20004, 'Existing FK_ITEM_MASTERS_IQC_AQL_POLICY definition is invalid');
    END IF;
  END IF;
END;
/

UPDATE ITEM_MASTERS
   SET IQC_AQL_POLICY_CODE = NULL,
       UPDATED_AT = SYSTIMESTAMP,
       UPDATED_BY = 'MIGRATION'
 WHERE IQC_AQL_POLICY_CODE IS NOT NULL
   AND (
     NVL(UPPER(TRIM(IQC_FLAG)), 'Y') <> 'Y'
     OR NVL(UPPER(TRIM(INSPECT_METHOD)), '(NULL)') IN ('SKIP', 'NONE')
   );
/

UPDATE ITEM_MASTERS
   SET IQC_AQL_POLICY_CODE = UPPER(TRIM(IQC_AQL_POLICY_CODE)),
       UPDATED_AT = SYSTIMESTAMP,
       UPDATED_BY = 'MIGRATION'
 WHERE IQC_AQL_POLICY_CODE IS NOT NULL
   AND IQC_AQL_POLICY_CODE <> UPPER(TRIM(IQC_AQL_POLICY_CODE));
/

COMMIT;
/

DECLARE
  v_fk_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_fk_exists
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'FK_ITEM_MASTERS_IQC_AQL_POLICY';

  IF v_fk_exists = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE ITEM_MASTERS
      ADD CONSTRAINT FK_ITEM_MASTERS_IQC_AQL_POLICY
      FOREIGN KEY (COMPANY, PLANT_CD, IQC_AQL_POLICY_CODE)
      REFERENCES IQC_AQL_POLICIES (COMPANY, PLANT_CD, POLICY_CODE)
      ENABLE VALIDATE';
  END IF;
END;
/
