-- 단자별 압착 규격 전선 변형 기준 데이터 — JSHANES (40/1000)
-- 근거: BOM_MASTERS GCRMP 연결 + ITEM_MASTERS SPEC의 실제 전선 규격/색상.
-- 수치 상하한은 원본 기준서가 없어 NULL이며, 승인 전 판정 기준으로 사용하지 않는다.

MERGE INTO TERMINAL_CRIMP_SPECS t
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, terminal_item_code, wire_size, wire_item_code,
         'BOM GCRMP + ITEM_MASTERS SPEC 기준 전선 변형. 압착 수치 기준서 확인 전.' remark
  FROM (
    SELECT 'MAG_TERX00616NA' terminal_item_code, '0.5SQ BN' wire_size, 'MAG_LDWX01563NA' wire_item_code FROM DUAL UNION ALL
    SELECT 'MAG_TERX00616NA', '0.5SQ GN', 'MAG_LDWX01564NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX00616NA', '0.5SQ GY', 'MAG_LDWX01565NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX00616NA', '0.5SQ RD', 'MAG_LDWX01567NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX00616NA', '0.5SQ YL', 'MAG_LDWX01568NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX00616NA', '0.5SQ BL', 'MAG_LDWX01601NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ BN', 'MAG_LDWX01563NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ GN', 'MAG_LDWX01564NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ GY', 'MAG_LDWX01565NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ RD', 'MAG_LDWX01567NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ YL', 'MAG_LDWX01568NA' FROM DUAL UNION ALL
    SELECT 'MAG_TERX01115NA', '0.5SQ BL', 'MAG_LDWX01601NA' FROM DUAL
  )
) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD
    AND t.TERMINAL_ITEM_CODE = s.terminal_item_code AND t.WIRE_SIZE = s.wire_size)
WHEN MATCHED THEN UPDATE SET
  t.WIRE_ITEM_CODE = s.wire_item_code,
  t.REMARK = s.remark,
  t.USE_YN = 'Y',
  t.UPDATED_BY = 'seed'
WHEN NOT MATCHED THEN INSERT (
  SPEC_ID, COMPANY, PLANT_CD, TERMINAL_ITEM_CODE, TERMINAL_TYPE, WIRE_SIZE, WIRE_ITEM_CODE,
  CRIMP_HEIGHT_LSL, CRIMP_HEIGHT_USL, CRIMP_WIDTH_LSL, CRIMP_WIDTH_USL,
  INS_CRIMP_HEIGHT_LSL, INS_CRIMP_HEIGHT_USL, PULL_FORCE_MIN,
  STRIP_LENGTH_MIN, STRIP_LENGTH_MAX, APPLICATOR_CODE, REMARK, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  SEQ_TERMINAL_CRIMP_SPEC.NEXTVAL, s.COMPANY, s.PLANT_CD, s.terminal_item_code, NULL, s.wire_size, s.wire_item_code,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, s.remark, 'Y',
  'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

COMMIT
/
