-- 단자별 압착 규격 기준 데이터 — JSHANES (COMPANY=40, PLANT_CD=1000)
-- 근거: ITEM_MASTERS의 MAG_TERX00616NA(KH1400004-21), MAG_TERX01115NA(N02-252-0055C)
--       BOM_MASTERS의 EAD65942601 계열 6개 반제품에 두 단자가 GCRMP 공정으로 공통 적용
--       연결 전선 ITEM_MASTERS의 SPEC가 모두 0.5SQ
-- 수치 상하한은 원본 기준서가 DB에 없어 임의 입력하지 않고 NULL로 둔다.

MERGE INTO TERMINAL_CRIMP_SPECS t
USING (
  SELECT '40' COMPANY, '1000' PLANT_CD, 'MAG_TERX00616NA' TERMINAL_ITEM_CODE,
         '0.5SQ' WIRE_SIZE, CAST(NULL AS VARCHAR2(50)) WIRE_ITEM_CODE,
         'BOM 기준: EAD65942601 계열 6개 반제품 GCRMP 공정 공통 적용. 압착 수치 기준서 확인 전.' REMARK
  FROM DUAL
  UNION ALL
  SELECT '40', '1000', 'MAG_TERX01115NA', '0.5SQ', CAST(NULL AS VARCHAR2(50)),
         'BOM 기준: EAD65942601 계열 6개 반제품 GCRMP 공정 공통 적용. 압착 수치 기준서 확인 전.'
  FROM DUAL
) s
ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD
    AND t.TERMINAL_ITEM_CODE = s.TERMINAL_ITEM_CODE AND t.WIRE_SIZE = s.WIRE_SIZE)
WHEN MATCHED THEN UPDATE SET
  t.WIRE_ITEM_CODE = COALESCE(t.WIRE_ITEM_CODE, s.WIRE_ITEM_CODE),
  t.REMARK = COALESCE(t.REMARK, s.REMARK),
  t.USE_YN = 'Y',
  t.UPDATED_BY = 'seed'
WHEN NOT MATCHED THEN INSERT (
  SPEC_ID, COMPANY, PLANT_CD, TERMINAL_ITEM_CODE, TERMINAL_TYPE, WIRE_SIZE, WIRE_ITEM_CODE,
  CRIMP_HEIGHT_LSL, CRIMP_HEIGHT_USL, CRIMP_WIDTH_LSL, CRIMP_WIDTH_USL,
  INS_CRIMP_HEIGHT_LSL, INS_CRIMP_HEIGHT_USL, PULL_FORCE_MIN,
  STRIP_LENGTH_MIN, STRIP_LENGTH_MAX, APPLICATOR_CODE, REMARK, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  SEQ_TERMINAL_CRIMP_SPEC.NEXTVAL, s.COMPANY, s.PLANT_CD, s.TERMINAL_ITEM_CODE, NULL, s.WIRE_SIZE, s.WIRE_ITEM_CODE,
  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, s.REMARK, 'Y',
  'seed', 'seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

COMMIT
/
