-- THN A50: 품목 스펙/템플릿의 JUDGE_CRITERIA는 풀 CRITERIA와 중복. 품목별 화면에서는 비우고 풀 기준을 쓴다.
-- 대상: JSHANES 40/1000

UPDATE IQC_PART_SPEC_ITEMS
   SET JUDGE_CRITERIA = NULL,
       UPDATED_BY = 'thn-a50-seed',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND INSP_ITEM_CODE LIKE 'THN-A50%'
   AND JUDGE_CRITERIA IS NOT NULL
/

UPDATE IQC_TEMPLATE_ITEMS
   SET JUDGE_CRITERIA = NULL,
       UPDATED_BY = 'thn-a50-seed',
       UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND TEMPLATE_ID LIKE 'THN-A50%'
   AND JUDGE_CRITERIA IS NOT NULL
/

COMMIT
/
