-- JSHANES / COMPANY=40 PLANT_CD=1000: 소스에만 있고 DB 배치가 누락된 출고이력조회 복구.
-- 기존 출고 업무 권한이 있는 역할의 누락 권한만 추가하며 명시적 N은 보존한다.
MERGE INTO MENU_CATEGORY_ITEMS target
USING (
  SELECT 'MAT_ISSUE_HIST' MENU_CODE, 'MATERIAL' CATEGORY_CODE, 105 SORT_ORDER,
         COMPANY, PLANT_CD
  FROM MENU_CATEGORIES
  WHERE CATEGORY_CODE = 'MATERIAL' AND COMPANY = '40' AND PLANT_CD = '1000'
) source
ON (target.MENU_CODE = source.MENU_CODE AND target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD)
WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
VALUES (source.MENU_CODE, source.CATEGORY_CODE, source.SORT_ORDER, source.COMPANY, source.PLANT_CD, SYSTIMESTAMP, 'codex', SYSTIMESTAMP, 'codex');
/
MERGE INTO ROLE_MENU_PERMISSIONS target
USING (
  SELECT DISTINCT ROLE_CODE, COMPANY, PLANT_CD
  FROM ROLE_MENU_PERMISSIONS
  WHERE MENU_CODE IN ('MAT_ISSUE', 'MAT_ISSUE_OTHER') AND CAN_ACCESS = 'Y'
    AND COMPANY = '40' AND PLANT_CD = '1000'
) source
ON (target.ROLE_CODE = source.ROLE_CODE AND target.MENU_CODE = 'MAT_ISSUE_HIST'
    AND target.COMPANY = source.COMPANY AND target.PLANT_CD = source.PLANT_CD)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
VALUES (source.ROLE_CODE, 'MAT_ISSUE_HIST', 'Y', source.COMPANY, source.PLANT_CD, SYSTIMESTAMP, SYSTIMESTAMP);
/
