-- 검사보조구 마스터 (INSPECT_AIDS: 한도견본·검사홀더) — 고객 감사 갭 해소 설계서 7절
-- 대상: JSHANES company=40 plant=1000. 멱등(테이블/제약은 존재 확인 후 생성, 코드/메뉴는 MERGE).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 적용 후: ORACLE_SITE=JSHANES python tools/generate_db_schema_doc.py (ERD 갱신)

-- 1) 테이블 (PK = COMPANY + PLANT_CD + AID_CODE, 설비점검항목 마스터와 같은 복합 PK 패턴)
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'INSPECT_AIDS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE INSPECT_AIDS (
      COMPANY        VARCHAR2(50)   NOT NULL,
      PLANT_CD       VARCHAR2(50)   NOT NULL,
      AID_CODE       VARCHAR2(50)   NOT NULL,
      AID_TYPE       VARCHAR2(30)   NOT NULL,
      AID_NAME       VARCHAR2(200)  NOT NULL,
      ITEM_CODE      VARCHAR2(50),
      PROCESS_CODE   VARCHAR2(50),
      DEFECT_CODE    VARCHAR2(50),
      IMAGE_URL      VARCHAR2(500),
      LOCATION       VARCHAR2(200),
      VALID_FROM     DATE,
      VALID_TO       DATE,
      APPROVED_BY    VARCHAR2(50),
      APPROVED_AT    TIMESTAMP,
      STATUS         VARCHAR2(20)   DEFAULT ''ACTIVE'' NOT NULL,
      REMARK         VARCHAR2(500),
      USE_YN         CHAR(1)        DEFAULT ''Y'' NOT NULL,
      CREATED_BY     VARCHAR2(50),
      UPDATED_BY     VARCHAR2(50),
      CREATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_INSPECT_AIDS PRIMARY KEY (COMPANY, PLANT_CD, AID_CODE),
      CONSTRAINT CK_INSPECT_AIDS_STATUS CHECK (STATUS IN (''ACTIVE'',''EXPIRED'',''RETIRED'')),
      CONSTRAINT CK_INSPECT_AIDS_USE_YN CHECK (USE_YN IN (''Y'',''N''))
    )';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IX_INSPECT_AIDS_TYPE';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_INSPECT_AIDS_TYPE ON INSPECT_AIDS (COMPANY, PLANT_CD, AID_TYPE, VALID_TO)';
  END IF;
END;
/

-- 2) 코멘트
COMMENT ON TABLE INSPECT_AIDS IS '검사보조구 마스터 (양품/불량 한도견본, 검사홀더/지그) — 유효기간·승인·사진 관리'
/
COMMENT ON COLUMN INSPECT_AIDS.COMPANY IS '회사 코드'
/
COMMENT ON COLUMN INSPECT_AIDS.PLANT_CD IS '사업장 코드'
/
COMMENT ON COLUMN INSPECT_AIDS.AID_CODE IS '보조구 코드 (사용자 입력)'
/
COMMENT ON COLUMN INSPECT_AIDS.AID_TYPE IS '보조구 유형 (COM_CODES INSPECT_AID_TYPE: LIMIT_OK 양품한도견본 / LIMIT_NG 불량한도견본 / HOLDER 검사홀더·지그)'
/
COMMENT ON COLUMN INSPECT_AIDS.AID_NAME IS '보조구 명칭'
/
COMMENT ON COLUMN INSPECT_AIDS.ITEM_CODE IS '대상 품목코드 (ITEM_MASTERS.ITEM_CODE, 선택)'
/
COMMENT ON COLUMN INSPECT_AIDS.PROCESS_CODE IS '적용 공정코드 (PROCESS_MASTERS.PROCESS_CODE, 선택)'
/
COMMENT ON COLUMN INSPECT_AIDS.DEFECT_CODE IS '불량 한도견본의 대표 불량코드 (DEFECT_CODE_MASTERS.DEFECT_CODE, 선택)'
/
COMMENT ON COLUMN INSPECT_AIDS.IMAGE_URL IS '사진 경로 (/uploads/inspect-aids/...)'
/
COMMENT ON COLUMN INSPECT_AIDS.LOCATION IS '보관 위치'
/
COMMENT ON COLUMN INSPECT_AIDS.VALID_FROM IS '유효기간 시작일'
/
COMMENT ON COLUMN INSPECT_AIDS.VALID_TO IS '유효기간 종료일 (만료/임박 판정 기준)'
/
COMMENT ON COLUMN INSPECT_AIDS.APPROVED_BY IS '승인자'
/
COMMENT ON COLUMN INSPECT_AIDS.APPROVED_AT IS '승인일시'
/
COMMENT ON COLUMN INSPECT_AIDS.STATUS IS '상태 (ACTIVE 사용중 / EXPIRED 만료 / RETIRED 폐기)'
/
COMMENT ON COLUMN INSPECT_AIDS.REMARK IS '비고'
/
COMMENT ON COLUMN INSPECT_AIDS.USE_YN IS '사용여부 (Y/N)'
/
COMMENT ON COLUMN INSPECT_AIDS.CREATED_BY IS '생성자'
/
COMMENT ON COLUMN INSPECT_AIDS.UPDATED_BY IS '수정자'
/
COMMENT ON COLUMN INSPECT_AIDS.CREATED_AT IS '생성일시'
/
COMMENT ON COLUMN INSPECT_AIDS.UPDATED_AT IS '수정일시'
/

-- 3) 공통코드 그룹 INSPECT_AID_TYPE (보조구 유형) · INSPECT_AID_STATUS (상태 배지)
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_TYPE' GROUP_CODE,'LIMIT_OK' DETAIL_CODE,'양품 한도견본' CODE_NAME,1 SORT_ORDER,'bg-green-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_TYPE' GROUP_CODE,'LIMIT_NG' DETAIL_CODE,'불량 한도견본' CODE_NAME,2 SORT_ORDER,'bg-red-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_TYPE' GROUP_CODE,'HOLDER' DETAIL_CODE,'검사홀더/지그' CODE_NAME,3 SORT_ORDER,'bg-slate-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_STATUS' GROUP_CODE,'ACTIVE' DETAIL_CODE,'사용중' CODE_NAME,1 SORT_ORDER,'bg-green-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_STATUS' GROUP_CODE,'EXPIRED' DETAIL_CODE,'만료' CODE_NAME,2 SORT_ORDER,'bg-red-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'INSPECT_AID_STATUS' GROUP_CODE,'RETIRED' DETAIL_CODE,'폐기' CODE_NAME,3 SORT_ORDER,'bg-gray-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/

-- 4) 메뉴 등록: QC_INSPECT_AID (QUALITY, /master/inspect-aid, labelKey menu.master.inspectAid)
--    QC_TERMINAL_CRIMP_SPEC(SORT_ORDER 5) 다음 6. DB QUALITY 첫 항목 QC_IQC=10 앞.
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'QC_INSPECT_AID' AS MENU_CODE,
         'QUALITY'        AS CATEGORY_CODE,
         6                AS SORT_ORDER,
         '40'             AS COMPANY,
         '1000'           AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'QC_INSPECT_AID' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'QC_INSPECT_AID' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/

COMMIT
/
