-- IQC 검사의뢰 LOT (입하 수량 단위 구성). 기존 입하단위 IQC는 SYS_CONFIG IQC_INSPECT_LOT_MODE=ARRIVAL 기본.
-- 실행: oracle-db --site JSHANES --execute-file

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_LEGACY_IQC_REQUEST_LOT';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_LEGACY_IQC_REQUEST_LOT START WITH 1 INCREMENT BY 1 NOCACHE';
  END IF;
END;
/
CREATE TABLE IQC_REQUEST_LOTS (
  REQUEST_NO VARCHAR2(50) NOT NULL,
  ITEM_CODE VARCHAR2(50) NOT NULL,
  ITEM_NAME VARCHAR2(200),
  VENDOR_CODE VARCHAR2(50),
  INVOICE_NO VARCHAR2(100),
  LOT_QTY NUMBER NOT NULL,
  SAMPLE_QTY NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'REQUESTED' NOT NULL,
  REMARK VARCHAR2(500),
  COMPANY VARCHAR2(50) NOT NULL,
  PLANT_CD VARCHAR2(50) NOT NULL,
  CREATED_BY VARCHAR2(50),
  UPDATED_BY VARCHAR2(50),
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT PK_IQC_REQUEST_LOTS PRIMARY KEY (REQUEST_NO)
)
/
COMMENT ON TABLE IQC_REQUEST_LOTS IS 'IQC 검사의뢰 LOT 헤더. 한 건=품목 1개. 담당자가 입하 수량을 묶어 의뢰한다.'
/
COMMENT ON COLUMN IQC_REQUEST_LOTS.LOT_QTY IS '모집단 수량(구성 입하 수량 합)'
/
COMMENT ON COLUMN IQC_REQUEST_LOTS.SAMPLE_QTY IS '시료 수량(AQL 또는 담당자 지정)'
/
CREATE INDEX IX_IQC_REQ_LOT_ITEM ON IQC_REQUEST_LOTS (COMPANY, PLANT_CD, ITEM_CODE, STATUS)
/
CREATE TABLE IQC_REQUEST_LOT_LINES (
  REQUEST_NO VARCHAR2(50) NOT NULL,
  SEQ NUMBER NOT NULL,
  ARRIVAL_NO VARCHAR2(50) NOT NULL,
  ITEM_CODE VARCHAR2(50) NOT NULL,
  QTY NUMBER NOT NULL,
  LINE_ROLE VARCHAR2(20) DEFAULT 'REPRESENTED' NOT NULL,
  INVOICE_NO VARCHAR2(100),
  COMPANY VARCHAR2(50) NOT NULL,
  PLANT_CD VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_IQC_REQUEST_LOT_LINES PRIMARY KEY (REQUEST_NO, SEQ),
  CONSTRAINT FK_IQC_REQ_LOT_LINES FOREIGN KEY (REQUEST_NO) REFERENCES IQC_REQUEST_LOTS (REQUEST_NO),
  CONSTRAINT CK_IQC_REQ_LINE_ROLE CHECK (LINE_ROLE IN ('SAMPLE', 'REPRESENTED'))
)
/
COMMENT ON TABLE IQC_REQUEST_LOT_LINES IS '검사의뢰 LOT 구성 입하. SAMPLE=시료, REPRESENTED=미검사 대표 대상'
/
CREATE INDEX IX_IQC_REQ_LOT_ARR ON IQC_REQUEST_LOT_LINES (COMPANY, PLANT_CD, ARRIVAL_NO, ITEM_CODE)
/
MERGE INTO SYS_CONFIGS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
   ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.CONFIG_KEY = 'IQC_INSPECT_LOT_MODE')
 WHEN NOT MATCHED THEN INSERT (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
      VALUES ('QUALITY', 'IQC_INSPECT_LOT_MODE', 'ARRIVAL', 'SELECT', 'IQC 검사 단위',
              'ARRIVAL: 기존 입하번호+품목 단위 검사(변경 없음). REQUEST: 검사의뢰 LOT 구성 후 모집단 일괄 판정. 의뢰된 입하는 기존 IQC 목록에서 제외.',
              '[{"label":"입하단위(기존)","value":"ARRIVAL"},{"label":"검사의뢰 LOT","value":"REQUEST"}]', 13, 'Y', '40', '1000', 'grok', 'grok', SYSTIMESTAMP, SYSTIMESTAMP)
/
MERGE INTO MENU_CATEGORY_ITEMS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
   ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.MENU_CODE = 'QC_IQC_REQUEST_LOT')
 WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
      VALUES ('QC_IQC_REQUEST_LOT', 'QUALITY', 32, '40', '1000', SYSTIMESTAMP, 'grok', SYSTIMESTAMP, 'grok')
/
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'ADMIN' ROLE_CODE, 'QC_IQC_REQUEST_LOT' MENU_CODE, '40' COMPANY, '1000' PLANT_CD FROM DUAL
  UNION ALL SELECT 'MANAGER', 'QC_IQC_REQUEST_LOT', '40', '1000' FROM DUAL
  UNION ALL SELECT 'OPERATOR', 'QC_IQC_REQUEST_LOT', '40', '1000' FROM DUAL
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', s.COMPANY, s.PLANT_CD)
/
COMMIT
/
