-- 내전압(절연저항 포함)·리크 검사 스테이션 도입 (2026-09-20)
-- 1) INSPECT_ITEM_SPECS.MIN_INSULATION_MOHM — 절연저항 하한(MΩ). HIPOT 스펙 행에서 같이 판정한다.
--    (TypeORM 마이그레이션 1771891000000-AddMinInsulationMohmToInspectItemSpec 과 동일 DDL)
-- 2) 공통코드 INSPECT_TYPE — 코드(HIPOT/LEAK/STRUCTURE/TORQUE)와 맞추고, 결과 데이터가 없는 옛 코드 HI_POT/INSULATION 은 미사용 처리
-- 3) 메뉴 — INSP_HIPOT_RESULT / INSP_LEAK_RESULT 등록. 누락돼 있던 INSP_TERMINAL_RESULT / INSP_STRUCTURE 도 같이 넣는다.
--    프론트 menuConfig 순서: INTEGRATED, STRUCTURE, RESULT, TERMINAL, HIPOT, LEAK, HISTORY, PROTOCOL

ALTER TABLE INSPECT_ITEM_SPECS ADD (MIN_INSULATION_MOHM NUMBER(10,3))
/
COMMENT ON COLUMN INSPECT_ITEM_SPECS.MIN_INSULATION_MOHM IS '절연저항 하한 (MΩ) - HIPOT 스펙에서 같이 판정'
/
MERGE INTO COM_CODES c
USING (
  SELECT 'HIPOT' AS DETAIL_CODE, '내전압' AS CODE_NAME, '내전압(절연저항 포함) 검사' AS CODE_DESC, 3 AS SORT_ORDER FROM DUAL UNION ALL
  SELECT 'LEAK', '리크', '리크(기밀) 검사', 4 FROM DUAL UNION ALL
  SELECT 'STRUCTURE', '구조', '구조 검사', 8 FROM DUAL UNION ALL
  SELECT 'TORQUE', '토크', '체결 토크 검사', 9 FROM DUAL
) s
ON (c.COMPANY = '40' AND c.PLANT_CD = '1000' AND c.GROUP_CODE = 'INSPECT_TYPE' AND c.DETAIL_CODE = s.DETAIL_CODE)
WHEN MATCHED THEN UPDATE SET c.CODE_NAME = s.CODE_NAME, c.CODE_DESC = s.CODE_DESC, c.SORT_ORDER = s.SORT_ORDER, c.USE_YN = 'Y', c.UPDATED_BY = 'system'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, CODE_DESC, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES ('INSPECT_TYPE', s.DETAIL_CODE, s.CODE_NAME, s.CODE_DESC, s.SORT_ORDER, 'Y', '40', '1000', 'system', 'system')
/
UPDATE COM_CODES SET USE_YN = 'N', UPDATED_BY = 'system'
 WHERE COMPANY = '40' AND PLANT_CD = '1000' AND GROUP_CODE = 'INSPECT_TYPE' AND DETAIL_CODE IN ('HI_POT', 'INSULATION')
/
MERGE INTO MENU_CATEGORY_ITEMS m
USING (
  SELECT 'INSP_TERMINAL_RESULT' AS MENU_CODE, 21 AS SORT_ORDER FROM DUAL UNION ALL
  SELECT 'INSP_HIPOT_RESULT', 22 FROM DUAL UNION ALL
  SELECT 'INSP_LEAK_RESULT', 23 FROM DUAL UNION ALL
  SELECT 'INSP_STRUCTURE', 25 FROM DUAL
) s
ON (m.COMPANY = '40' AND m.PLANT_CD = '1000' AND m.MENU_CODE = s.MENU_CODE)
WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.MENU_CODE, 'INSPECTION', s.SORT_ORDER, '40', '1000', 'system', 'system')
/
MERGE INTO ROLE_MENU_PERMISSIONS r
USING (
  SELECT ro.ROLE_CODE, mc.MENU_CODE
    FROM (SELECT 'MANAGER' AS ROLE_CODE FROM DUAL UNION ALL SELECT 'OPERATOR' FROM DUAL) ro
   CROSS JOIN (SELECT 'INSP_TERMINAL_RESULT' AS MENU_CODE FROM DUAL UNION ALL SELECT 'INSP_HIPOT_RESULT' FROM DUAL
               UNION ALL SELECT 'INSP_LEAK_RESULT' FROM DUAL UNION ALL SELECT 'INSP_STRUCTURE' FROM DUAL) mc
) s
ON (r.COMPANY = '40' AND r.PLANT_CD = '1000' AND r.ROLE_CODE = s.ROLE_CODE AND r.MENU_CODE = s.MENU_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', '40', '1000')
/
COMMIT
/
