DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CATEGORY_MASTERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CATEGORY_MASTERS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        CATEGORY_CODE VARCHAR2(50) NOT NULL,
        CATEGORY_NAME VARCHAR2(100) NOT NULL,
        LEVEL_NO NUMBER(1) NOT NULL,
        PARENT_CATEGORY_CODE VARCHAR2(50),
        SORT_ORDER NUMBER(8) DEFAULT 0 NOT NULL,
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        DESCRIPTION VARCHAR2(500),
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CATEGORY_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, CATEGORY_CODE),
        CONSTRAINT CK_DEFECT_CATEGORY_LEVEL CHECK (LEVEL_NO IN (1, 2, 3)),
        CONSTRAINT CK_DEFECT_CATEGORY_USE_YN CHECK (USE_YN IN ('Y', 'N')),
        CONSTRAINT FK_DEFECT_CATEGORY_PARENT FOREIGN KEY (COMPANY, PLANT_CD, PARENT_CATEGORY_CODE)
          REFERENCES DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CODE_MASTERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CODE_MASTERS (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        DEFECT_CODE VARCHAR2(50) NOT NULL,
        DEFECT_NAME VARCHAR2(100) NOT NULL,
        CATEGORY_CODE VARCHAR2(50) NOT NULL,
        DEFECT_GRADE VARCHAR2(20) NOT NULL,
        DEFECT_SCOPE VARCHAR2(30) DEFAULT 'COMMON' NOT NULL,
        DESCRIPTION VARCHAR2(500),
        SORT_ORDER NUMBER(8) DEFAULT 0 NOT NULL,
        USE_YN VARCHAR2(1) DEFAULT 'Y' NOT NULL,
        CREATED_BY VARCHAR2(50),
        UPDATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        UPDATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CODE_MASTERS PRIMARY KEY (COMPANY, PLANT_CD, DEFECT_CODE),
        CONSTRAINT CK_DEFECT_CODE_GRADE CHECK (DEFECT_GRADE IN ('CRITICAL', 'MAJOR', 'MINOR')),
        CONSTRAINT CK_DEFECT_CODE_SCOPE CHECK (DEFECT_SCOPE IN ('RAW_MATERIAL', 'PRODUCT', 'PROCESS', 'COMMON')),
        CONSTRAINT CK_DEFECT_CODE_USE_YN CHECK (USE_YN IN ('Y', 'N')),
        CONSTRAINT FK_DEFECT_CODE_CATEGORY FOREIGN KEY (COMPANY, PLANT_CD, CATEGORY_CODE)
          REFERENCES DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'DEFECT_CODE_PRODUCT_TYPES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE DEFECT_CODE_PRODUCT_TYPES (
        COMPANY VARCHAR2(50) NOT NULL,
        PLANT_CD VARCHAR2(50) NOT NULL,
        DEFECT_CODE VARCHAR2(50) NOT NULL,
        PRODUCT_TYPE VARCHAR2(50) NOT NULL,
        CREATED_BY VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT PK_DEFECT_CODE_PRODUCT_TYPES PRIMARY KEY (COMPANY, PLANT_CD, DEFECT_CODE, PRODUCT_TYPE),
        CONSTRAINT FK_DEFECT_PRODUCT_CODE FOREIGN KEY (COMPANY, PLANT_CD, DEFECT_CODE)
          REFERENCES DEFECT_CODE_MASTERS (COMPANY, PLANT_CD, DEFECT_CODE)
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_CAT_PARENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_CAT_PARENT ON DEFECT_CATEGORY_MASTERS (COMPANY, PLANT_CD, PARENT_CATEGORY_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_CODE_CATEGORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_CODE_CATEGORY ON DEFECT_CODE_MASTERS (COMPANY, PLANT_CD, CATEGORY_CODE)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM USER_INDEXES WHERE INDEX_NAME = 'IX_DEFECT_PRODUCT_TYPE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_DEFECT_PRODUCT_TYPE ON DEFECT_CODE_PRODUCT_TYPES (COMPANY, PLANT_CD, PRODUCT_TYPE)';
  END IF;

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS DISABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CATEGORY_MASTERS d
    USING (
      WITH tenants AS (
        SELECT DISTINCT COMPANY, PLANT_CD FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE'
        UNION
        SELECT '40' AS COMPANY, '1000' AS PLANT_CD FROM DUAL
        WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE = 'DEFECT_TYPE')
      ),
      categories AS (
        SELECT 'APPEARANCE' CATEGORY_CODE, '외관 불량' CATEGORY_NAME, 1 LEVEL_NO, NULL PARENT_CATEGORY_CODE, 10 SORT_ORDER FROM DUAL UNION ALL
        SELECT 'FUNCTION', '기능 불량', 1, NULL, 20 FROM DUAL UNION ALL
        SELECT 'PROCESS', '공정 불량', 1, NULL, 30 FROM DUAL UNION ALL
        SELECT 'MATERIAL', '원자재 불량', 1, NULL, 40 FROM DUAL UNION ALL
        SELECT 'ETC', '기타 불량', 1, NULL, 90 FROM DUAL UNION ALL
        SELECT 'APP_RAW', '원자재 외관', 2, 'APPEARANCE', 10 FROM DUAL UNION ALL
        SELECT 'APP_PRODUCT', '제품 외관', 2, 'APPEARANCE', 20 FROM DUAL UNION ALL
        SELECT 'FUNC_PRODUCT', '제품 기능', 2, 'FUNCTION', 10 FROM DUAL UNION ALL
        SELECT 'PROC_WORK', '작업/조립', 2, 'PROCESS', 10 FROM DUAL UNION ALL
        SELECT 'MAT_RAW', '원자재 품질', 2, 'MATERIAL', 10 FROM DUAL UNION ALL
        SELECT 'ETC_COMMON', '공통', 2, 'ETC', 10 FROM DUAL UNION ALL
        SELECT 'APP_RAW_WIRE', '전선/자재 외관', 3, 'APP_RAW', 10 FROM DUAL UNION ALL
        SELECT 'APP_PRODUCT_FINISH', '제품 외관/마감', 3, 'APP_PRODUCT', 10 FROM DUAL UNION ALL
        SELECT 'FUNC_PRODUCT_ELEC', '제품 전기기능', 3, 'FUNC_PRODUCT', 10 FROM DUAL UNION ALL
        SELECT 'PROC_ASSEMBLY', '조립/작업', 3, 'PROC_WORK', 10 FROM DUAL UNION ALL
        SELECT 'PROC_WELD', '용접/접합', 3, 'PROC_WORK', 20 FROM DUAL UNION ALL
        SELECT 'MAT_RAW_QUALITY', '원자재 품질', 3, 'MAT_RAW', 10 FROM DUAL UNION ALL
        SELECT 'ETC_COMMON_ETC', '기타/공통', 3, 'ETC_COMMON', 10 FROM DUAL
      )
      SELECT tenants.COMPANY, tenants.PLANT_CD, categories.*
      FROM tenants CROSS JOIN categories
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.CATEGORY_CODE = s.CATEGORY_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, CATEGORY_CODE, CATEGORY_NAME, LEVEL_NO, PARENT_CATEGORY_CODE,
      SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.CATEGORY_CODE, s.CATEGORY_NAME, s.LEVEL_NO, s.PARENT_CATEGORY_CODE,
      s.SORT_ORDER, 'Y', 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE 'ALTER TABLE DEFECT_CATEGORY_MASTERS ENABLE CONSTRAINT FK_DEFECT_CATEGORY_PARENT';

  EXECUTE IMMEDIATE q'[
    MERGE INTO DEFECT_CODE_MASTERS d
    USING (
      SELECT
        COMPANY,
        PLANT_CD,
        DETAIL_CODE AS DEFECT_CODE,
        CODE_NAME AS DEFECT_NAME,
        CASE DETAIL_CODE
          WHEN 'APP' THEN 'APP_PRODUCT_FINISH'
          WHEN 'MARK' THEN 'APP_PRODUCT_FINISH'
          WHEN 'BURR' THEN 'APP_PRODUCT_FINISH'
          WHEN 'CRACK' THEN 'APP_PRODUCT_FINISH'
          WHEN 'FUNC' THEN 'FUNC_PRODUCT_ELEC'
          WHEN 'WELD' THEN 'PROC_WELD'
          WHEN 'ASM' THEN 'PROC_ASSEMBLY'
          WHEN 'WORK' THEN 'PROC_ASSEMBLY'
          WHEN 'MATERIAL' THEN 'MAT_RAW_QUALITY'
          WHEN 'MAT' THEN 'MAT_RAW_QUALITY'
          WHEN 'DIM' THEN 'APP_PRODUCT_FINISH'
          ELSE 'ETC_COMMON_ETC'
        END AS CATEGORY_CODE,
        NVL(DEFECT_GRADE, CASE WHEN DETAIL_CODE = 'CRACK' THEN 'CRITICAL' ELSE 'MAJOR' END) AS DEFECT_GRADE,
        CASE
          WHEN DETAIL_CODE IN ('MATERIAL', 'MAT') THEN 'RAW_MATERIAL'
          WHEN DETAIL_CODE IN ('WORK', 'ASM', 'WELD') THEN 'PROCESS'
          WHEN DETAIL_CODE = 'ETC' THEN 'COMMON'
          ELSE 'PRODUCT'
        END AS DEFECT_SCOPE,
        SORT_ORDER,
        USE_YN
      FROM COM_CODES
      WHERE GROUP_CODE = 'DEFECT_TYPE'
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.DEFECT_CODE = s.DEFECT_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, DEFECT_CODE, DEFECT_NAME, CATEGORY_CODE, DEFECT_GRADE, DEFECT_SCOPE,
      SORT_ORDER, USE_YN, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.DEFECT_CODE, s.DEFECT_NAME, s.CATEGORY_CODE, s.DEFECT_GRADE, s.DEFECT_SCOPE,
      s.SORT_ORDER, s.USE_YN, 'migration', 'migration', SYSTIMESTAMP, SYSTIMESTAMP
    )
  ]';

  EXECUTE IMMEDIATE q'[
    MERGE INTO MENU_CATEGORY_ITEMS d
    USING (
      SELECT '40' COMPANY, '1000' PLANT_CD, 'QUALITY' CATEGORY_CODE, 'QC_DEFECT_CODE' MENU_CODE, 55 SORT_ORDER FROM DUAL
    ) s
    ON (d.COMPANY = s.COMPANY AND d.PLANT_CD = s.PLANT_CD AND d.MENU_CODE = s.MENU_CODE)
    WHEN NOT MATCHED THEN INSERT (
      COMPANY, PLANT_CD, CATEGORY_CODE, MENU_CODE, SORT_ORDER, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
    ) VALUES (
      s.COMPANY, s.PLANT_CD, s.CATEGORY_CODE, s.MENU_CODE, s.SORT_ORDER, SYSTIMESTAMP, 'migration', SYSTIMESTAMP, 'migration'
    )
  ]';

  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CATEGORY_MASTERS IS '불량코드 전용 3레벨 분류 마스터']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CODE_MASTERS IS '불량코드 전용 마스터']';
  EXECUTE IMMEDIATE q'[COMMENT ON TABLE DEFECT_CODE_PRODUCT_TYPES IS '불량코드 제품류별 적용 매핑']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_MASTERS.DEFECT_GRADE IS 'CRITICAL/MAJOR/MINOR AQL 판정 등급']';
  EXECUTE IMMEDIATE q'[COMMENT ON COLUMN DEFECT_CODE_MASTERS.DEFECT_SCOPE IS 'RAW_MATERIAL/PRODUCT/PROCESS/COMMON 적용 범위']';

  COMMIT;
END;
/
