-- 시나리오 런너 메뉴 등록
--
-- 사이드바 순서는 DB 가 정한다(MENU_CATEGORIES.SORT_ORDER). menuConfig.ts 의 배열 순서는
-- DB 응답 전 잠깐 쓰는 폴백일 뿐이다. INTERFACE 가 160 이고 그 앞 150(GAUGE_MGMT)은
-- 비활성이라, 155 를 주면 인터페이스 바로 위에 들어간다(2026-09-14 실측).
--
-- MENU_CATEGORY_ITEMS 행이 없는 메뉴는 사이드바에서 아예 제외되므로 항목 행도 같이 넣는다.
-- 권한은 MANAGER 에만 준다 — 실데이터를 바꾸는 절차를 대신 실행하는 화면이라
-- 기본 배포 대상이 아니다. 필요하면 시스템관리 > 권한관리에서 역할별로 연다.
BEGIN
  MERGE INTO MENU_CATEGORIES t
  USING (
    SELECT 'SCENARIO' CATEGORY_CODE, 'menu.scenario' LABEL_KEY, 'PlayCircle' ICON_NAME,
           155 SORT_ORDER, 'Y' IS_ACTIVE, '40' COMPANY, '1000' PLANT_CD FROM DUAL
  ) s
  ON (t.CATEGORY_CODE = s.CATEGORY_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
  WHEN NOT MATCHED THEN
    INSERT (CATEGORY_CODE, LABEL_KEY, ICON_NAME, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES (s.CATEGORY_CODE, s.LABEL_KEY, s.ICON_NAME, s.SORT_ORDER, s.IS_ACTIVE, s.COMPANY, s.PLANT_CD, 'migration', 'migration');

  MERGE INTO MENU_CATEGORY_ITEMS t
  USING (
    SELECT 'SCN_RUNNER' MENU_CODE, 'SCENARIO' CATEGORY_CODE, 10 SORT_ORDER,
           '40' COMPANY, '1000' PLANT_CD FROM DUAL
  ) s
  ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
  WHEN NOT MATCHED THEN
    INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
    VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, 'migration', 'migration');

  MERGE INTO ROLE_MENU_PERMISSIONS t
  USING (
    SELECT 'MANAGER' ROLE_CODE, 'SCN_RUNNER' MENU_CODE, 'Y' CAN_ACCESS,
           '40' COMPANY, '1000' PLANT_CD FROM DUAL
  ) s
  ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE
      AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
  WHEN NOT MATCHED THEN
    -- ROLE_MENU_PERMISSIONS 에는 CREATED_BY/UPDATED_BY 가 없다(2026-09-14 실측)
    INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
    VALUES (s.ROLE_CODE, s.MENU_CODE, s.CAN_ACCESS, s.COMPANY, s.PLANT_CD);

  COMMIT;
END;
/
