-- 유수명 재검사 회차 COUNT+1 채번을 전역 Oracle SEQUENCE로 대체한다.
DECLARE
  v_exists NUMBER;
  v_start NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_SEQUENCES
   WHERE SEQUENCE_NAME = 'SEQ_IQC_RETEST_ROUND';
  IF v_exists = 0 THEN
    SELECT NVL(MAX(RETEST_ROUND), 0) + 1 INTO v_start FROM IQC_LOGS;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_IQC_RETEST_ROUND START WITH ' || v_start ||
                      ' INCREMENT BY 1 NOCYCLE NOCACHE';
  END IF;
END;
/
