-- 실적입력(조립) B안(PROD_INPUT_ASSEMBLY_B) 좌측 메뉴 DB 시드
-- 신규 leaf: PROD_INPUT_ASSEMBLY_B / path /production/input-assembly-b / labelKey menu.production.inputAssemblyB
-- 직전 PROD_INPUT_ASSEMBLY(CATEGORY=PRODUCTION, SORT_ORDER=60, 2026-09-21 실측) 바로 다음 SORT_ORDER=61에 배치.
--   (다음 항목 PROD_ORDER_RESULT 는 SORT_ORDER=70 이라 61 은 빈 자리다.)
-- 멀티테넌시 정본: COMPANY=40, PLANT_CD='1000'. 멱등 MERGE(ON = MENU_CODE+COMPANY+PLANT_CD). add-only.
--
-- ROLE_MENU_PERMISSIONS: A안 PROD_INPUT_ASSEMBLY 와 동일하게 MANAGER/OPERATOR 를 등록한다.
--   CAN_ACCESS 값은 A안 기존 행과 같은 'Y' 다(2026-09-21 실측).
--   PROD_INPUT_KIOSK_B 는 '1' 을 쓰지만 그건 그 화면의 기존 행을 따른 것이고, 여기서는 조립 A안을 따른다.
--   서브공정 키팅(PROD_KITTING_B)은 A안에 권한 행 자체가 없어 만들지 않았다 — 각자 A안 상태를 따른다.
--
-- 배치 시안 검토용 라우트다. 채택/폐기 결정 후 이 메뉴는 정리한다.

-- 1) 메뉴 아이템 등록
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'PROD_INPUT_ASSEMBLY_B' AS MENU_CODE,
         'PRODUCTION'            AS CATEGORY_CODE,
         61                      AS SORT_ORDER,
         '40'                    AS COMPANY,
         '1000'                  AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

-- 2) RBAC 권한 등록 (A안 PROD_INPUT_ASSEMBLY 와 동일: MANAGER/OPERATOR, CAN_ACCESS='Y')
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'PROD_INPUT_ASSEMBLY_B' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'PROD_INPUT_ASSEMBLY_B' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/
