-- 입고~출하 구멍: OQC 게이트 켜기 + 자동차감 재고부족 시 실적 차단
-- 사이트: JSHANES (40/1000)
UPDATE SYS_CONFIGS
   SET CONFIG_VALUE = 'Y',
       UPDATED_AT = SYSTIMESTAMP
 WHERE CONFIG_KEY = 'OQC_ENABLED'
   AND COMPANY = '40'
   AND PLANT_CD = '1000'
   AND NVL(CONFIG_VALUE, 'N') <> 'Y'
/
UPDATE SYS_CONFIGS
   SET CONFIG_VALUE = 'BLOCK',
       UPDATED_AT = SYSTIMESTAMP
 WHERE CONFIG_KEY = 'MAT_ISSUE_STOCK_CHECK'
   AND COMPANY = '40'
   AND PLANT_CD = '1000'
   AND NVL(CONFIG_VALUE, ' ') <> 'BLOCK'
/
COMMIT
/
