DECLARE
  -- JSHANES: 계측기 수치 수신 진입점 — EQUIP_PROTOCOLS 파서가 수치 토큰 위치/단위를 알 수 있도록 컬럼 추가 (멱등)
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='EQUIP_PROTOCOLS' AND COLUMN_NAME='VALUE_INDEX';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_PROTOCOLS ADD (VALUE_INDEX NUMBER NULL)';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME='EQUIP_PROTOCOLS' AND COLUMN_NAME='VALUE_UNIT';
  IF n=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE EQUIP_PROTOCOLS ADD (VALUE_UNIT VARCHAR2(20) NULL)';
  END IF;
END;
/
COMMENT ON COLUMN EQUIP_PROTOCOLS.VALUE_INDEX IS '측정 수치 토큰 위치 (0-based, NULL: 수치 미수신)';
/
COMMENT ON COLUMN EQUIP_PROTOCOLS.VALUE_UNIT IS '측정 수치 단위 (예: kgf, N, mm)';
/
