-- 조립·서브조립 점검 필수 여부 환경설정 (SYS_CONFIGS, PRODUCTION 그룹)
-- 값: Y=점검 완료 필수, N=점검 선택사항. 사이트: JSHANES(40/1000).
INSERT INTO SYS_CONFIGS
  (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'ASSEMBLY_DAILY_INSPECT_REQUIRED', 'PRODUCTION', 'Y', 'BOOLEAN', '조립 설비 일상점검 필수',
  '조립 실적 처리 전에 설비 일상점검 완료를 필수로 검사합니다. Y=필수, N=선택', NULL, 20, 'Y', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'ASSEMBLY_DAILY_INSPECT_REQUIRED' AND COMPANY = '40' AND PLANT_CD = '1000');
/
INSERT INTO SYS_CONFIGS
  (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'ASSEMBLY_WORKER_INSPECT_REQUIRED', 'PRODUCTION', 'Y', 'BOOLEAN', '조립 작업자점검 필수',
  '조립 실적 처리 전에 작업자 설비점검 완료를 필수로 검사합니다. Y=필수, N=선택', NULL, 21, 'Y', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'ASSEMBLY_WORKER_INSPECT_REQUIRED' AND COMPANY = '40' AND PLANT_CD = '1000');
/
INSERT INTO SYS_CONFIGS
  (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'SUBASSEMBLY_DAILY_INSPECT_REQUIRED', 'PRODUCTION', 'Y', 'BOOLEAN', '서브조립 설비 일상점검 필수',
  '서브조립 실적 처리 전에 설비 일상점검 완료를 필수로 검사합니다. Y=필수, N=선택', NULL, 22, 'Y', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'SUBASSEMBLY_DAILY_INSPECT_REQUIRED' AND COMPANY = '40' AND PLANT_CD = '1000');
/
INSERT INTO SYS_CONFIGS
  (CONFIG_KEY, CONFIG_GROUP, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_AT, UPDATED_AT)
SELECT 'SUBASSEMBLY_WORKER_INSPECT_REQUIRED', 'PRODUCTION', 'Y', 'BOOLEAN', '서브조립 작업자점검 필수',
  '서브조립 실적 처리 전에 작업자 설비점검 완료를 필수로 검사합니다. Y=필수, N=선택', NULL, 23, 'Y', '40', '1000', SYSTIMESTAMP, SYSTIMESTAMP
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM SYS_CONFIGS WHERE CONFIG_KEY = 'SUBASSEMBLY_WORKER_INSPECT_REQUIRED' AND COMPANY = '40' AND PLANT_CD = '1000');
/
COMMIT;
/
