-- THN A50 템플릿을 RAW 품목에 적용 (ITEM_NAME 매핑). 기존 SEQ 1~n은 유지, THN 항목은 SEQ 100번대.
-- 대상: JSHANES 40/1000. MERGE 멱등.

MERGE INTO IQC_PART_SPECS t
USING (
  SELECT ITEM_CODE
  FROM ITEM_MASTERS
  WHERE COMPANY = '40' AND PLANT_CD = '1000' AND NVL(USE_YN,'Y') = 'Y' AND ITEM_TYPE = 'RAW_MATERIAL'
    AND ITEM_CODE NOT LIKE '%\_FAIL' ESCAPE '\'
    AND ITEM_CODE NOT LIKE '%\_PASS' ESCAPE '\'
    AND UPPER(TRIM(ITEM_NAME)) IN (
      'WIRE','LEAD WIRE','TUBE','TAPE','TML','EARTH TML','TERMINAL',
      'CRIMP RING','CRIMP SHILED','CRIMP SHIELD','HSG','HOUSING','SEAL','B/CABLE'
    )
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.ITEM_CODE = s.ITEM_CODE)
WHEN MATCHED THEN UPDATE SET
  t.USE_YN = 'Y', t.UPDATED_BY = 'thn-a50-seed', t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, SAMPLE_QTY, IS_DEST, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  '40', '1000', s.ITEM_CODE, 1, 'N', 'Y',
  'thn-a50-seed', 'thn-a50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

MERGE INTO IQC_PART_SPEC_ITEMS t
USING (
  SELECT
    m.ITEM_CODE,
    ti.SEQ + 100 AS SEQ,
    ti.INSP_ITEM_CODE,
    ti.JUDGE_CRITERIA,
    ti.DEFECT_GRADE,
    ti.INSPECTION_TYPE,
    ti.SAMPLE_METHOD
  FROM ITEM_MASTERS m
  JOIN IQC_TEMPLATE_ITEMS ti
    ON ti.COMPANY = '40' AND ti.PLANT_CD = '1000'
   AND ti.TEMPLATE_ID = CASE UPPER(TRIM(m.ITEM_NAME))
     WHEN 'WIRE' THEN 'THN-A50-WIRE'
     WHEN 'LEAD WIRE' THEN 'THN-A50-WIRE'
     WHEN 'TUBE' THEN 'THN-A50-CTUBE'
     WHEN 'TAPE' THEN 'THN-A50-TAPE'
     WHEN 'TML' THEN 'THN-A50-TWL'
     WHEN 'EARTH TML' THEN 'THN-A50-TWL'
     WHEN 'TERMINAL' THEN 'THN-A50-TWL'
     WHEN 'CRIMP RING' THEN 'THN-A50-TWL'
     WHEN 'CRIMP SHILED' THEN 'THN-A50-TWL'
     WHEN 'CRIMP SHIELD' THEN 'THN-A50-TWL'
     WHEN 'HSG' THEN 'THN-A50-HOUSING'
     WHEN 'HOUSING' THEN 'THN-A50-HOUSING'
     WHEN 'SEAL' THEN 'THN-A50-SEAL'
     WHEN 'B/CABLE' THEN 'THN-A50-WCABLE'
   END
  WHERE m.COMPANY = '40' AND m.PLANT_CD = '1000'
    AND NVL(m.USE_YN,'Y') = 'Y' AND m.ITEM_TYPE = 'RAW_MATERIAL'
    AND m.ITEM_CODE NOT LIKE '%\_FAIL' ESCAPE '\'
    AND m.ITEM_CODE NOT LIKE '%\_PASS' ESCAPE '\'
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.ITEM_CODE = s.ITEM_CODE AND t.INSP_ITEM_CODE = s.INSP_ITEM_CODE)
WHEN MATCHED THEN UPDATE SET
  t.JUDGE_CRITERIA = s.JUDGE_CRITERIA,
  t.DEFECT_GRADE = s.DEFECT_GRADE,
  t.INSPECTION_TYPE = s.INSPECTION_TYPE,
  t.SAMPLE_METHOD = s.SAMPLE_METHOD,
  t.USE_YN = 'Y',
  t.UPDATED_BY = 'thn-a50-seed',
  t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, JUDGE_CRITERIA,
  DEFECT_GRADE, INSPECTION_TYPE, SAMPLE_METHOD, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  '40', '1000', s.ITEM_CODE, s.SEQ, s.INSP_ITEM_CODE, s.JUDGE_CRITERIA,
  s.DEFECT_GRADE, s.INSPECTION_TYPE, s.SAMPLE_METHOD, 'Y',
  'thn-a50-seed', 'thn-a50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

-- VOC 주기항목은 매핑된 전 원자재에 공통 부여
MERGE INTO IQC_PART_SPEC_ITEMS t
USING (
  SELECT m.ITEM_CODE, ti.SEQ + 200 AS SEQ, ti.INSP_ITEM_CODE, ti.JUDGE_CRITERIA,
         ti.DEFECT_GRADE, ti.INSPECTION_TYPE, ti.SAMPLE_METHOD
  FROM ITEM_MASTERS m
  JOIN IQC_TEMPLATE_ITEMS ti
    ON ti.COMPANY = '40' AND ti.PLANT_CD = '1000'
   AND ti.TEMPLATE_ID = 'THN-A50-COMMON'
   AND ti.INSP_ITEM_CODE IN ('THN-A50-V01','THN-A50-V02')
  WHERE m.COMPANY = '40' AND m.PLANT_CD = '1000'
    AND NVL(m.USE_YN,'Y') = 'Y' AND m.ITEM_TYPE = 'RAW_MATERIAL'
    AND m.ITEM_CODE NOT LIKE '%\_FAIL' ESCAPE '\'
    AND m.ITEM_CODE NOT LIKE '%\_PASS' ESCAPE '\'
    AND UPPER(TRIM(m.ITEM_NAME)) IN (
      'WIRE','LEAD WIRE','TUBE','TAPE','TML','EARTH TML','TERMINAL',
      'CRIMP RING','CRIMP SHILED','CRIMP SHIELD','HSG','HOUSING','SEAL','B/CABLE'
    )
) s
ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.ITEM_CODE = s.ITEM_CODE AND t.INSP_ITEM_CODE = s.INSP_ITEM_CODE)
WHEN MATCHED THEN UPDATE SET
  t.JUDGE_CRITERIA = s.JUDGE_CRITERIA,
  t.DEFECT_GRADE = s.DEFECT_GRADE,
  t.INSPECTION_TYPE = s.INSPECTION_TYPE,
  t.SAMPLE_METHOD = s.SAMPLE_METHOD,
  t.USE_YN = 'Y',
  t.UPDATED_BY = 'thn-a50-seed',
  t.UPDATED_AT = SYSTIMESTAMP
WHEN NOT MATCHED THEN INSERT (
  COMPANY, PLANT_CD, ITEM_CODE, SEQ, INSP_ITEM_CODE, JUDGE_CRITERIA,
  DEFECT_GRADE, INSPECTION_TYPE, SAMPLE_METHOD, USE_YN,
  CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
  '40', '1000', s.ITEM_CODE, s.SEQ, s.INSP_ITEM_CODE, s.JUDGE_CRITERIA,
  s.DEFECT_GRADE, s.INSPECTION_TYPE, s.SAMPLE_METHOD, 'Y',
  'thn-a50-seed', 'thn-a50-seed', SYSTIMESTAMP, SYSTIMESTAMP
)
/

COMMIT
/
