-- THN 제조공정표 대비 검사 공백 보완 (JSHANES 40/1000)
-- 코드: 퓨즈삽입/토크, 비전, 릴레이 기능
-- 메뉴: 각 검사 스테이션 + MANAGER/OPERATOR 권한

MERGE INTO COM_CODES c
USING (
  SELECT 'TORQUE' AS DETAIL_CODE, '퓨즈삽입/토크' AS CODE_NAME, '퓨즈 삽입 및 체결 토크 검사' AS CODE_DESC, 50 AS SORT_ORDER FROM DUAL UNION ALL
  SELECT 'VISION', '비전', '릴레이, 퓨즈, 블록 누락 및 이중 삽입 검사', 60 FROM DUAL UNION ALL
  SELECT 'RELAY_FUNCTION', '릴레이 기능', '릴레이 작동 기능 검사', 70 FROM DUAL
) s
ON (c.COMPANY = '40' AND c.PLANT_CD = '1000' AND c.GROUP_CODE = 'INSPECT_TYPE' AND c.DETAIL_CODE = s.DETAIL_CODE)
WHEN MATCHED THEN UPDATE SET c.CODE_NAME = s.CODE_NAME, c.CODE_DESC = s.CODE_DESC, c.SORT_ORDER = s.SORT_ORDER, c.USE_YN = 'Y', c.UPDATED_BY = 'codex'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, CODE_DESC, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES ('INSPECT_TYPE', s.DETAIL_CODE, s.CODE_NAME, s.CODE_DESC, s.SORT_ORDER, 'Y', '40', '1000', 'codex', 'codex')
/

MERGE INTO MENU_CATEGORY_ITEMS m
USING (
  SELECT 'INSP_TORQUE_RESULT' AS MENU_CODE, 24 AS SORT_ORDER FROM DUAL UNION ALL
  SELECT 'INSP_VISION_RESULT', 25 FROM DUAL UNION ALL
  SELECT 'INSP_RELAY_RESULT', 26 FROM DUAL
) s
ON (m.COMPANY = '40' AND m.PLANT_CD = '1000' AND m.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET m.CATEGORY_CODE = 'INSPECTION', m.SORT_ORDER = s.SORT_ORDER, m.UPDATED_BY = 'codex'
WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.MENU_CODE, 'INSPECTION', s.SORT_ORDER, '40', '1000', 'codex', 'codex')
/

MERGE INTO ROLE_MENU_PERMISSIONS r
USING (
  SELECT roles.ROLE_CODE, menus.MENU_CODE
    FROM (SELECT 'MANAGER' AS ROLE_CODE FROM DUAL UNION ALL SELECT 'OPERATOR' FROM DUAL) roles
   CROSS JOIN (
     SELECT 'INSP_TORQUE_RESULT' AS MENU_CODE FROM DUAL UNION ALL
     SELECT 'INSP_VISION_RESULT' FROM DUAL UNION ALL
     SELECT 'INSP_RELAY_RESULT' FROM DUAL
   ) menus
) s
ON (r.COMPANY = '40' AND r.PLANT_CD = '1000' AND r.ROLE_CODE = s.ROLE_CODE AND r.MENU_CODE = s.MENU_CODE)
WHEN MATCHED THEN UPDATE SET r.CAN_ACCESS = 'Y'
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', '40', '1000')
/

COMMIT
/

-- 최초 검토 중 생성했다가 기존 VISUAL 최종육안과 중복임을 확인한 임시 FINAL 등록 제거
DELETE FROM ROLE_MENU_PERMISSIONS WHERE COMPANY = '40' AND PLANT_CD = '1000' AND MENU_CODE = 'INSP_FINAL_RESULT'
/
DELETE FROM MENU_CATEGORY_ITEMS WHERE COMPANY = '40' AND PLANT_CD = '1000' AND MENU_CODE = 'INSP_FINAL_RESULT'
/
DELETE FROM COM_CODES WHERE COMPANY = '40' AND PLANT_CD = '1000' AND GROUP_CODE = 'INSPECT_TYPE' AND DETAIL_CODE = 'FINAL'
/
COMMIT
/
