-- 품목별 리크/내전압/토크 검사 스펙 + 압착 Applicator 디스크/수명
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 적용 후: ORACLE_SITE=JSHANES python tools/generate_db_schema_doc.py

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'INSPECT_ITEM_SPECS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE INSPECT_ITEM_SPECS (
      SPEC_ID           NUMBER(15,0)   NOT NULL,
      COMPANY           VARCHAR2(50)   NOT NULL,
      PLANT_CD          VARCHAR2(50)   NOT NULL,
      ITEM_CODE         VARCHAR2(50)   NOT NULL,
      INSPECT_TYPE      VARCHAR2(20)   NOT NULL,
      CONNECTOR_KEY     VARCHAR2(50)   DEFAULT ''*'' NOT NULL,
      CHARGE_BAR        NUMBER(10,3),
      CHARGE_TOL_BAR    NUMBER(10,3),
      MEASURE_BAR       NUMBER(10,3),
      MEASURE_TOL_BAR   NUMBER(10,3),
      HOLD_SECONDS      NUMBER(10,3),
      MIN_HOLD_BAR      NUMBER(10,3),
      TEST_VOLTAGE_KV   NUMBER(10,3),
      TEST_SECONDS      NUMBER(10,3),
      MAX_CURRENT_MA    NUMBER(10,3),
      TORQUE_LSL        NUMBER(10,3),
      TORQUE_USL        NUMBER(10,3),
      TORQUE_UNIT       VARCHAR2(20),
      REMARK            VARCHAR2(500),
      USE_YN            CHAR(1)        DEFAULT ''Y'' NOT NULL,
      CREATED_BY        VARCHAR2(50),
      UPDATED_BY        VARCHAR2(50),
      CREATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT        TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_INSPECT_ITEM_SPECS PRIMARY KEY (SPEC_ID),
      CONSTRAINT UK_INSPECT_ITEM_SPECS UNIQUE (COMPANY, PLANT_CD, ITEM_CODE, INSPECT_TYPE, CONNECTOR_KEY),
      CONSTRAINT CK_INSPECT_ITEM_SPEC_TYPE CHECK (INSPECT_TYPE IN (''LEAK'',''HIPOT'',''TORQUE'')),
      CONSTRAINT CK_INSPECT_ITEM_SPEC_USE CHECK (USE_YN IN (''Y'',''N''))
    )';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_INSPECT_ITEM_SPEC';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INSPECT_ITEM_SPEC START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20';
  END IF;
END;
/

COMMENT ON TABLE INSPECT_ITEM_SPECS IS '품목별 리크/내전압/토크 검사 스펙 (THN 관리계획서 I50/H57 실측 판정)'
/
COMMENT ON COLUMN INSPECT_ITEM_SPECS.MIN_HOLD_BAR IS '리크 유지 후 합격 하한 압력 (bar), THN 0.3'
/
COMMENT ON COLUMN INSPECT_ITEM_SPECS.CHARGE_BAR IS '리크 주입압 목표 (bar), THN 0.7'
/
COMMENT ON COLUMN INSPECT_ITEM_SPECS.TEST_VOLTAGE_KV IS '내전압 시험 전압 (kV), THN 3.00'
/
COMMENT ON COLUMN INSPECT_ITEM_SPECS.MAX_CURRENT_MA IS '내전압 허용전류 (mA), THN 2.0'
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TERMINAL_CRIMP_SPECS' AND COLUMN_NAME = 'APPLICATOR_DISK';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TERMINAL_CRIMP_SPECS ADD APPLICATOR_DISK NUMBER(10,3)';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TERMINAL_CRIMP_SPECS' AND COLUMN_NAME = 'APPLICATOR_LIFE_SHOTS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TERMINAL_CRIMP_SPECS ADD APPLICATOR_LIFE_SHOTS NUMBER(10,0)';
  END IF;
  SELECT COUNT(*) INTO n FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'TERMINAL_CRIMP_SPECS' AND COLUMN_NAME = 'SAMPLE_LOT_QTY';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TERMINAL_CRIMP_SPECS ADD SAMPLE_LOT_QTY NUMBER(10,0)';
  END IF;
END;
/

COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.APPLICATOR_DISK IS 'Applicator 디스크값 (크림프하이트와 일치해야 함)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.APPLICATOR_LIFE_SHOTS IS 'Applicator 수명 타수 (측각 10만/일반 20만)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.SAMPLE_LOT_QTY IS '초중종물 기준 작업수량 (THN 300)'
/

MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'QC_INSPECT_ITEM_SPEC' AS MENU_CODE,
         'QUALITY'              AS CATEGORY_CODE,
         6                      AS SORT_ORDER,
         '40'                   AS COMPANY,
         '1000'                 AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'QC_INSPECT_ITEM_SPEC' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'QC_INSPECT_ITEM_SPEC' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/

COMMIT
/
