-- 품목마스터 고정 적재위치(ITEM_MASTERS.STORAGE_LOCATION) 초기 배정
--
-- 배경: 입고 로직(receiving.service.ts)은 수동 지정이 없으면 이 값을 MAT_STOCKS.LOCATION_CODE 에 자동 적용한다.
--       값이 전부 비어 있어 재고 287건 중 18건(테스트 흔적)만 위치를 갖고 있었다.
-- 대상: 자재 입고 대상인 RAW_MATERIAL 41건. 반제품/완제품은 자재 입고 경로가 아니므로 제외한다.
-- 기준: W001(원자재창고) 랙 6개에 자재 종류별로 모아 배정한다(같은 종류는 같은 랙).
--       변동 위치가 필요하면 PDA 창고랙 지정(PDA_MAT_RACK_ASSIGN)으로 덮어쓴다.
-- 멱등: 이미 값이 있는 품목은 건드리지 않는다(STORAGE_LOCATION IS NULL 조건).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 되돌리기: UPDATE ITEM_MASTERS SET STORAGE_LOCATION = NULL WHERE ITEM_TYPE = 'RAW_MATERIAL';

-- 1) 전선류 → W001-A-01-01
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-A-01-01', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
   AND ITEM_NAME IN ('LEAD WIRE', 'WIRE', 'B/CABLE', 'B/CABLE_PASS', 'B/CABLE_FAIL', 'CORE')
/

-- 2) 단자·압착류 → W001-A-01-02
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-A-01-02', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
   AND ITEM_NAME IN ('TERMINAL', 'TML', 'EARTH TML', 'CRIMP RING', 'CRIMP SHIELD', 'CRIMP SHILED')
/

-- 3) 하우징·씰류 → W001-A-02-01
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-A-02-01', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
   AND ITEM_NAME IN ('HOUSING', 'HSG', 'HSG_PASS', 'HSG_FAIL', 'SEAL', 'RET')
/

-- 4) 튜브·테이프류 → W001-A-02-02
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-A-02-02', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
   AND ITEM_NAME IN ('TUBE', 'TAPE', 'CABLE TIE')
/

-- 5) 라벨·리본류 → W001-B-01-01
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-B-01-01', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
   AND (ITEM_NAME LIKE 'LABEL%' OR ITEM_NAME LIKE 'RIBBON%')
/

-- 6) 위 분류에 들지 않는 나머지 원자재 → W001-B-01-02 (예비 랙)
UPDATE ITEM_MASTERS
   SET STORAGE_LOCATION = 'W001-B-01-02', UPDATED_AT = SYSTIMESTAMP
 WHERE ITEM_TYPE = 'RAW_MATERIAL'
   AND STORAGE_LOCATION IS NULL
/

COMMIT
/
