-- 기준정보 참조 무결성 FK 가드 (2026-09-03)
-- 근거: 기준정보검증(MST_VALIDATION) REF_INTEGRITY 규칙 22건을 DB 제약으로 승격.
--       부모 9개 테이블은 모두 (COMPANY, PLANT_CD, CODE) 복합 PK 보유, 적용 전 전 회사 고아 0건 실측.
-- 삭제 규칙: NO ACTION(기본) — 참조 중인 기준정보 삭제 시 ORA-02292 → HttpExceptionFilter가 409 REF_IN_USE로 변환.
-- 삽입 규칙: 미존재 코드 참조 시 ORA-02291 → 400 REF_NOT_FOUND.
-- 멱등: 이미 존재하는 제약/인덱스(ORA-02275, ORA-00955, ORA-01408)는 건너뛴다.
-- 인덱스: 미인덱스 FK는 부모 삭제/갱신 시 자식 테이블 락을 유발하므로 FK 컬럼 선행 인덱스를 함께 생성한다.

DECLARE
  PROCEDURE add_fk(p_ddl IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2275, -2264) THEN RAISE; END IF; -- 02275 동일 FK 존재 / 02264 동일 이름 존재
  END;
  PROCEDURE add_idx(p_ddl IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_ddl;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-955, -1408) THEN RAISE; END IF; -- 00955 이름 중복 / 01408 동일 컬럼 인덱스 존재
  END;
BEGIN
  -- BOM (CHILD_ITEM_CODE FK는 기존 FK_BOM_MASTERS_ITEM_CODE)
  add_fk('ALTER TABLE BOM_MASTERS ADD CONSTRAINT FK_BOM_PARENT_ITEM FOREIGN KEY (COMPANY, PLANT_CD, PARENT_ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_BOM_CHILD_ITEM_FK ON BOM_MASTERS (COMPANY, PLANT_CD, CHILD_ITEM_CODE)');

  -- 라우팅
  add_fk('ALTER TABLE ROUTING_GROUPS ADD CONSTRAINT FK_RTG_GRP_ITEM FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_RTG_GRP_ITEM_FK ON ROUTING_GROUPS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_fk('ALTER TABLE ROUTING_PROCESSES ADD CONSTRAINT FK_RTG_PRC_ROUTING FOREIGN KEY (COMPANY, PLANT_CD, ROUTING_CODE) REFERENCES ROUTING_GROUPS (COMPANY, PLANT_CD, ROUTING_CODE)');
  add_fk('ALTER TABLE ROUTING_PROCESSES ADD CONSTRAINT FK_RTG_PRC_PROCESS FOREIGN KEY (COMPANY, PLANT_CD, PROCESS_CODE) REFERENCES PROCESS_MASTERS (COMPANY, PLANT_CD, PROCESS_CODE)');
  add_idx('CREATE INDEX IDX_RTG_PRC_PROCESS_FK ON ROUTING_PROCESSES (COMPANY, PLANT_CD, PROCESS_CODE)');
  add_fk('ALTER TABLE ROUTING_MATERIALS ADD CONSTRAINT FK_RTG_MAT_ROUTING FOREIGN KEY (COMPANY, PLANT_CD, ROUTING_CODE) REFERENCES ROUTING_GROUPS (COMPANY, PLANT_CD, ROUTING_CODE)');
  add_fk('ALTER TABLE ROUTING_MATERIALS ADD CONSTRAINT FK_RTG_MAT_ITEM FOREIGN KEY (COMPANY, PLANT_CD, CHILD_ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_RTG_MAT_ITEM_FK ON ROUTING_MATERIALS (COMPANY, PLANT_CD, CHILD_ITEM_CODE)');

  -- 공정-설비 / 공정 CAPA
  add_fk('ALTER TABLE PROCESS_EQUIPMENTS ADD CONSTRAINT FK_PRC_EQP_PROCESS FOREIGN KEY (COMPANY, PLANT_CD, PROCESS_CODE) REFERENCES PROCESS_MASTERS (COMPANY, PLANT_CD, PROCESS_CODE)');
  add_fk('ALTER TABLE PROCESS_EQUIPMENTS ADD CONSTRAINT FK_PRC_EQP_EQUIP FOREIGN KEY (COMPANY, PLANT_CD, EQUIP_CODE) REFERENCES EQUIP_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE)');
  add_idx('CREATE INDEX IDX_PRC_EQP_EQUIP_FK ON PROCESS_EQUIPMENTS (COMPANY, PLANT_CD, EQUIP_CODE)');
  add_fk('ALTER TABLE PROCESS_CAPAS ADD CONSTRAINT FK_PRC_CAPA_PROCESS FOREIGN KEY (COMPANY, PLANT_CD, PROCESS_CODE) REFERENCES PROCESS_MASTERS (COMPANY, PLANT_CD, PROCESS_CODE)');
  add_fk('ALTER TABLE PROCESS_CAPAS ADD CONSTRAINT FK_PRC_CAPA_ITEM FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_PRC_CAPA_ITEM_FK ON PROCESS_CAPAS (COMPANY, PLANT_CD, ITEM_CODE)');

  -- 소모품 사용 정의
  add_fk('ALTER TABLE CONSUMABLE_USAGE_MAP ADD CONSTRAINT FK_CNS_USAGE_ITEM FOREIGN KEY (COMPANY, PLANT_CD, PRODUCT_ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_fk('ALTER TABLE CONSUMABLE_USAGE_MAP ADD CONSTRAINT FK_CNS_USAGE_EQUIP FOREIGN KEY (COMPANY, PLANT_CD, EQUIP_CODE) REFERENCES EQUIP_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE)');
  add_idx('CREATE INDEX IDX_CNS_USAGE_EQUIP_FK ON CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, EQUIP_CODE)');
  add_fk('ALTER TABLE CONSUMABLE_USAGE_MAP ADD CONSTRAINT FK_CNS_USAGE_CONSUMABLE FOREIGN KEY (COMPANY, PLANT_CD, CONSUMABLE_CODE) REFERENCES CONSUMABLE_MASTERS (COMPANY, PLANT_CD, CONSUMABLE_CODE)');
  add_idx('CREATE INDEX IDX_CNS_USAGE_CONS_FK ON CONSUMABLE_USAGE_MAP (COMPANY, PLANT_CD, CONSUMABLE_CODE)');

  -- IQC 품목 기준 (IQC_PART_SPEC_ITEMS.INSP_ITEM_CODE → IQC_ITEM_POOL 은 기존 FK_SPEC_ITEMS_INSP 가 있어 ORA-02275 로 건너뜀)
  add_fk('ALTER TABLE IQC_PART_SPECS ADD CONSTRAINT FK_IQC_SPEC_ITEM FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_fk('ALTER TABLE IQC_PART_SPEC_ITEMS ADD CONSTRAINT FK_IQC_SPEC_INSP_ITEM FOREIGN KEY (COMPANY, PLANT_CD, INSP_ITEM_CODE) REFERENCES IQC_ITEM_POOL (COMPANY, PLANT_CD, INSP_ITEM_CODE)');
  add_idx('CREATE INDEX IDX_IQC_SPEC_INSP_ITEM_FK ON IQC_PART_SPEC_ITEMS (COMPANY, PLANT_CD, INSP_ITEM_CODE)');

  -- 설비 점검항목 풀
  add_fk('ALTER TABLE EQUIP_INSPECT_ITEM_POOL ADD CONSTRAINT FK_EQP_INSP_POOL_EQUIP FOREIGN KEY (COMPANY, PLANT_CD, EQUIP_CODE) REFERENCES EQUIP_MASTERS (COMPANY, PLANT_CD, EQUIP_CODE)');
  add_fk('ALTER TABLE EQUIP_INSPECT_ITEM_POOL ADD CONSTRAINT FK_EQP_INSP_POOL_ITEM FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE) REFERENCES EQUIP_INSPECT_ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_EQP_INSP_POOL_ITEM_FK ON EQUIP_INSPECT_ITEM_POOL (COMPANY, PLANT_CD, ITEM_CODE)');

  -- 벤더 바코드 매핑
  add_fk('ALTER TABLE VENDOR_BARCODE_MAPPINGS ADD CONSTRAINT FK_VBC_MAP_ITEM FOREIGN KEY (COMPANY, PLANT_CD, ITEM_CODE) REFERENCES ITEM_MASTERS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_idx('CREATE INDEX IDX_VBC_MAP_ITEM_FK ON VENDOR_BARCODE_MAPPINGS (COMPANY, PLANT_CD, ITEM_CODE)');
  add_fk('ALTER TABLE VENDOR_BARCODE_MAPPINGS ADD CONSTRAINT FK_VBC_MAP_VENDOR FOREIGN KEY (COMPANY, PLANT_CD, VENDOR_CODE) REFERENCES VENDOR_MASTERS (COMPANY, PLANT_CD, VENDOR_CODE)');
  add_idx('CREATE INDEX IDX_VBC_MAP_VENDOR_FK ON VENDOR_BARCODE_MAPPINGS (COMPANY, PLANT_CD, VENDOR_CODE)');

  -- 창고
  add_fk('ALTER TABLE WAREHOUSE_LOCATIONS ADD CONSTRAINT FK_WH_LOC_WAREHOUSE FOREIGN KEY (COMPANY, PLANT_CD, WAREHOUSE_CODE) REFERENCES WAREHOUSES (COMPANY, PLANT_CD, WAREHOUSE_CODE)');
  add_fk('ALTER TABLE WAREHOUSE_TRANSFER_RULES ADD CONSTRAINT FK_WH_XFER_FROM_WH FOREIGN KEY (COMPANY, PLANT_CD, FROM_WAREHOUSE_ID) REFERENCES WAREHOUSES (COMPANY, PLANT_CD, WAREHOUSE_CODE)');
  add_fk('ALTER TABLE WAREHOUSE_TRANSFER_RULES ADD CONSTRAINT FK_WH_XFER_TO_WH FOREIGN KEY (COMPANY, PLANT_CD, TO_WAREHOUSE_ID) REFERENCES WAREHOUSES (COMPANY, PLANT_CD, WAREHOUSE_CODE)');
  add_idx('CREATE INDEX IDX_WH_XFER_TO_WH_FK ON WAREHOUSE_TRANSFER_RULES (COMPANY, PLANT_CD, TO_WAREHOUSE_ID)');
END;
/
-- DDL로 INVALID 된 PL/SQL 재컴파일
BEGIN
  FOR o IN (SELECT OBJECT_NAME, OBJECT_TYPE FROM USER_OBJECTS WHERE STATUS = 'INVALID' AND OBJECT_TYPE IN ('PACKAGE','PACKAGE BODY','PROCEDURE','FUNCTION','TRIGGER','VIEW')) LOOP
    BEGIN
      IF o.OBJECT_TYPE = 'PACKAGE BODY' THEN
        EXECUTE IMMEDIATE 'ALTER PACKAGE ' || o.OBJECT_NAME || ' COMPILE BODY';
      ELSE
        EXECUTE IMMEDIATE 'ALTER ' || o.OBJECT_TYPE || ' ' || o.OBJECT_NAME || ' COMPILE';
      END IF;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END LOOP;
END;
/
