-- 단자별 압착 규격 마스터 (TERMINAL_CRIMP_SPECS) — 고객 감사 갭 해소 설계서 6절
-- 대상: JSHANES company=40 plant=1000. 멱등(테이블/시퀀스/제약은 존재 확인 후 생성, 코드/메뉴는 MERGE).
-- 실행: python C:/Users/hsyou/.claude/skills/oracle-db/scripts/oracle_connector.py --site JSHANES --execute-file <this file>
-- 적용 후: ORACLE_SITE=JSHANES python tools/generate_db_schema_doc.py (ERD 갱신)

-- 1) 테이블 · 시퀀스 · UNIQUE
DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM USER_TABLES WHERE TABLE_NAME = 'TERMINAL_CRIMP_SPECS';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE TABLE TERMINAL_CRIMP_SPECS (
      SPEC_ID              NUMBER(15,0)   NOT NULL,
      COMPANY              VARCHAR2(50)   NOT NULL,
      PLANT_CD             VARCHAR2(50)   NOT NULL,
      TERMINAL_ITEM_CODE   VARCHAR2(50)   NOT NULL,
      TERMINAL_TYPE        VARCHAR2(30),
      WIRE_SIZE            VARCHAR2(50)   NOT NULL,
      WIRE_ITEM_CODE       VARCHAR2(50),
      CRIMP_HEIGHT_LSL     NUMBER(10,3),
      CRIMP_HEIGHT_USL     NUMBER(10,3),
      CRIMP_WIDTH_LSL      NUMBER(10,3),
      CRIMP_WIDTH_USL      NUMBER(10,3),
      INS_CRIMP_HEIGHT_LSL NUMBER(10,3),
      INS_CRIMP_HEIGHT_USL NUMBER(10,3),
      PULL_FORCE_MIN       NUMBER(10,3),
      STRIP_LENGTH_MIN     NUMBER(10,3),
      STRIP_LENGTH_MAX     NUMBER(10,3),
      APPLICATOR_CODE      VARCHAR2(50),
      REMARK               VARCHAR2(500),
      USE_YN               CHAR(1)        DEFAULT ''Y'' NOT NULL,
      CREATED_BY           VARCHAR2(50),
      UPDATED_BY           VARCHAR2(50),
      CREATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      UPDATED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
      CONSTRAINT PK_TERMINAL_CRIMP_SPECS PRIMARY KEY (SPEC_ID),
      CONSTRAINT UK_TERMINAL_CRIMP_SPECS UNIQUE (COMPANY, PLANT_CD, TERMINAL_ITEM_CODE, WIRE_SIZE),
      CONSTRAINT CK_TERMINAL_CRIMP_USE_YN CHECK (USE_YN IN (''Y'',''N''))
    )';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TERMINAL_CRIMP_SPEC';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_TERMINAL_CRIMP_SPEC START WITH 1 INCREMENT BY 1 MAXVALUE 999999999999999 NOCYCLE CACHE 20';
  END IF;

  SELECT COUNT(*) INTO n FROM USER_INDEXES WHERE INDEX_NAME = 'IX_TERMINAL_CRIMP_TERMINAL';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX IX_TERMINAL_CRIMP_TERMINAL ON TERMINAL_CRIMP_SPECS (COMPANY, PLANT_CD, TERMINAL_ITEM_CODE)';
  END IF;
END;
/

-- 2) 코멘트
COMMENT ON TABLE TERMINAL_CRIMP_SPECS IS '단자별 압착 규격 마스터 (단자 품목 × 전선 사이즈별 압착고/폭/인장력/탈피길이 상하한)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.SPEC_ID IS '규격 ID (SEQ_TERMINAL_CRIMP_SPEC)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.COMPANY IS '회사 코드'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.PLANT_CD IS '사업장 코드'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.TERMINAL_ITEM_CODE IS '단자 품목코드 (ITEM_MASTERS.ITEM_CODE)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.TERMINAL_TYPE IS '단자 종류 (COM_CODES TERMINAL_TYPE: DISK/RING/FASTON/PIN/SOCKET)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.WIRE_SIZE IS '전선 사이즈 (예: 0.5SQ, AWG20)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.WIRE_ITEM_CODE IS '전선 품목코드 (ITEM_MASTERS.ITEM_CODE, 선택)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CRIMP_HEIGHT_LSL IS '압착 높이 하한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CRIMP_HEIGHT_USL IS '압착 높이 상한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CRIMP_WIDTH_LSL IS '압착 폭 하한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CRIMP_WIDTH_USL IS '압착 폭 상한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.INS_CRIMP_HEIGHT_LSL IS '절연부 압착 높이 하한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.INS_CRIMP_HEIGHT_USL IS '절연부 압착 높이 상한 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.PULL_FORCE_MIN IS '인장력 최소값 (N)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.STRIP_LENGTH_MIN IS '탈피 길이 최소 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.STRIP_LENGTH_MAX IS '탈피 길이 최대 (mm)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.APPLICATOR_CODE IS '어플리케이터 코드'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.REMARK IS '비고'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.USE_YN IS '사용여부 (Y/N)'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CREATED_BY IS '생성자'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.UPDATED_BY IS '수정자'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.CREATED_AT IS '생성일시'
/
COMMENT ON COLUMN TERMINAL_CRIMP_SPECS.UPDATED_AT IS '수정일시'
/

-- 3) 공통코드 그룹 TERMINAL_TYPE (초기 5종. 김종현 책임 확인 후 화면에서 추가)
MERGE INTO COM_CODES t
USING (SELECT 'TERMINAL_TYPE' GROUP_CODE,'DISK' DETAIL_CODE,'디스크' CODE_NAME,1 SORT_ORDER,'bg-slate-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'TERMINAL_TYPE' GROUP_CODE,'RING' DETAIL_CODE,'링' CODE_NAME,2 SORT_ORDER,'bg-blue-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'TERMINAL_TYPE' GROUP_CODE,'FASTON' DETAIL_CODE,'파스톤' CODE_NAME,3 SORT_ORDER,'bg-teal-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'TERMINAL_TYPE' GROUP_CODE,'PIN' DETAIL_CODE,'핀' CODE_NAME,4 SORT_ORDER,'bg-amber-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/
MERGE INTO COM_CODES t
USING (SELECT 'TERMINAL_TYPE' GROUP_CODE,'SOCKET' DETAIL_CODE,'소켓' CODE_NAME,5 SORT_ORDER,'bg-purple-600 text-white' ATTR1,'40' COMPANY,'1000' PLANT_CD FROM DUAL) s
ON (t.GROUP_CODE=s.GROUP_CODE AND t.DETAIL_CODE=s.DETAIL_CODE AND t.COMPANY=s.COMPANY AND t.PLANT_CD=s.PLANT_CD)
WHEN MATCHED THEN UPDATE SET t.CODE_NAME=s.CODE_NAME, t.SORT_ORDER=s.SORT_ORDER, t.USE_YN='Y'
WHEN NOT MATCHED THEN INSERT (GROUP_CODE,DETAIL_CODE,CODE_NAME,SORT_ORDER,USE_YN,ATTR1,COMPANY,PLANT_CD,CREATED_BY) VALUES (s.GROUP_CODE,s.DETAIL_CODE,s.CODE_NAME,s.SORT_ORDER,'Y',s.ATTR1,s.COMPANY,s.PLANT_CD,'claude')
/

-- 4) 메뉴 등록: QC_TERMINAL_CRIMP_SPEC (QUALITY, /master/terminal-crimp-spec, labelKey menu.master.terminalCrimpSpec)
--    DB QUALITY 카테고리 실측(2026-09-09): QC_IQC_PART_SPEC 행 없음, QC_IQC=10이 첫 항목 → menuConfig 순서(QC_IQC_PART_SPEC 다음)대로 5에 배치.
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'QC_TERMINAL_CRIMP_SPEC' AS MENU_CODE,
         'QUALITY'                AS CATEGORY_CODE,
         5                        AS SORT_ORDER,
         '40'                     AS COMPANY,
         '1000'                   AS PLANT_CD
  FROM dual
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD,
          CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD,
          SYSTIMESTAMP, 'system', SYSTIMESTAMP, 'system')
/

MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER'  AS ROLE_CODE, 'QC_TERMINAL_CRIMP_SPEC' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
  UNION ALL
  SELECT 'OPERATOR' AS ROLE_CODE, 'QC_TERMINAL_CRIMP_SPEC' AS MENU_CODE, '40' AS COMPANY, '1000' AS PLANT_CD FROM dual
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', SYSTIMESTAMP, SYSTIMESTAMP, s.COMPANY, s.PLANT_CD)
/

COMMIT
/
