-- 시스템 상태 모니터 메뉴 등록 (SYS_HEALTH → /system/health, menu.system.health) 2026-09-20
-- SYSTEM 카테고리 맨 뒤(개선요청 SYS_IMPR_REQ 다음). 프론트 menuConfig 순서와 같다.
MERGE INTO MENU_CATEGORY_ITEMS m
USING (SELECT 'SYS_HEALTH' AS MENU_CODE FROM DUAL) s
ON (m.COMPANY = '40' AND m.PLANT_CD = '1000' AND m.MENU_CODE = s.MENU_CODE)
WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES ('SYS_HEALTH', 'SYSTEM',
          (SELECT NVL(MAX(SORT_ORDER), 0) + 10 FROM MENU_CATEGORY_ITEMS WHERE CATEGORY_CODE = 'SYSTEM' AND COMPANY = '40' AND PLANT_CD = '1000' AND SORT_ORDER < 9999),
          '40', '1000', 'system', 'system')
/
MERGE INTO ROLE_MENU_PERMISSIONS r
USING (SELECT 'ADMIN' AS ROLE_CODE, 'SYS_HEALTH' AS MENU_CODE FROM DUAL) s
ON (r.COMPANY = '40' AND r.PLANT_CD = '1000' AND r.ROLE_CODE = s.ROLE_CODE AND r.MENU_CODE = s.MENU_CODE)
WHEN NOT MATCHED THEN INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', '40', '1000')
/
COMMIT
/
