DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM MENU_CATEGORY_ITEMS
   WHERE COMPANY = '40'
     AND PLANT_CD = '1000'
     AND MENU_CODE = 'SHIP_BOX_STOCK';

  IF v_count = 0 THEN
    INSERT INTO MENU_CATEGORY_ITEMS (
      COMPANY, PLANT_CD, CATEGORY_CODE, MENU_CODE, SORT_ORDER,
      CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
    )
    VALUES (
      '40', '1000', 'SHIPPING', 'SHIP_BOX_STOCK', 25,
      SYSTIMESTAMP, 'codex', SYSTIMESTAMP, 'codex'
    );
  END IF;

  INSERT INTO ROLE_MENU_PERMISSIONS (
    ROLE_CODE, MENU_CODE, CAN_ACCESS, CREATED_AT, UPDATED_AT, COMPANY, PLANT_CD
  )
  SELECT
    ROLE_CODE, 'SHIP_BOX_STOCK', CAN_ACCESS, SYSTIMESTAMP, SYSTIMESTAMP, COMPANY, PLANT_CD
  FROM ROLE_MENU_PERMISSIONS src
  WHERE COMPANY = '40'
    AND PLANT_CD = '1000'
    AND MENU_CODE = 'SHIP_PACK'
    AND CAN_ACCESS = 'Y'
    AND NOT EXISTS (
      SELECT 1
      FROM ROLE_MENU_PERMISSIONS dst
      WHERE dst.COMPANY = src.COMPANY
        AND dst.PLANT_CD = src.PLANT_CD
        AND dst.ROLE_CODE = src.ROLE_CODE
        AND dst.MENU_CODE = 'SHIP_BOX_STOCK'
    );

  COMMIT;
END;
