-- ============================================================
-- THN GAP Phase 2: 엔티티 컬럼 추가 + 신규 테이블
-- ============================================================

-- G8: MAT_ISSUES — 불출자/수령인
ALTER TABLE MAT_ISSUES ADD (ISSUER_ID VARCHAR2(20));
ALTER TABLE MAT_ISSUES ADD (ISSUER_NAME VARCHAR2(50));
ALTER TABLE MAT_ISSUES ADD (RECEIVER_ID VARCHAR2(20));
ALTER TABLE MAT_ISSUES ADD (RECEIVER_NAME VARCHAR2(50));

COMMENT ON COLUMN MAT_ISSUES.ISSUER_ID IS '불출자 사번 (바코드 스캔)';
COMMENT ON COLUMN MAT_ISSUES.ISSUER_NAME IS '불출자 이름';
COMMENT ON COLUMN MAT_ISSUES.RECEIVER_ID IS '수령인 사번 (바코드 스캔)';
COMMENT ON COLUMN MAT_ISSUES.RECEIVER_NAME IS '수령인 이름';

-- G7: MAT_ISSUE_REQUEST_ITEMS — BOM 소요량
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (BOM_REQ_QTY NUMBER(12,3));
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (PREV_ISSUE_QTY NUMBER(12,3));
ALTER TABLE MAT_ISSUE_REQUEST_ITEMS ADD (FLOOR_STOCK_QTY NUMBER(12,3));

COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.BOM_REQ_QTY IS 'BOM 소요량 (= BOM * 생산수량)';
COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.PREV_ISSUE_QTY IS '기 불출수량';
COMMENT ON COLUMN MAT_ISSUE_REQUEST_ITEMS.FLOOR_STOCK_QTY IS '현장재고';

-- Minor: PHYSICAL_INV_COUNT_DETAILS — 실제 로케이션
ALTER TABLE PHYSICAL_INV_COUNT_DETAILS ADD (ACTUAL_LOCATION VARCHAR2(50));

COMMENT ON COLUMN PHYSICAL_INV_COUNT_DETAILS.ACTUAL_LOCATION IS '실사 시 확인된 실제 로케이션 (위치 보정용)';

-- G9: MAT_OUT_REQUESTS 신규 테이블
CREATE TABLE MAT_OUT_REQUESTS (
  REQUEST_NO    VARCHAR2(20)  NOT NULL,
  OUT_TYPE      VARCHAR2(10)  NOT NULL,
  STATUS        VARCHAR2(10)  DEFAULT 'REQUESTED' NOT NULL,
  MAT_UID       VARCHAR2(30)  NOT NULL,
  ITEM_CODE     VARCHAR2(50)  NOT NULL,
  QTY           NUMBER(12,3)  NOT NULL,
  REASON        VARCHAR2(500),
  REQUESTER_ID  VARCHAR2(20),
  APPROVER_ID   VARCHAR2(20),
  APPROVED_AT   TIMESTAMP,
  LOCK_YN       CHAR(1)       DEFAULT 'Y',
  COMPANY       VARCHAR2(50),
  PLANT_CD      VARCHAR2(50),
  CREATED_BY    VARCHAR2(50),
  UPDATED_BY    VARCHAR2(50),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_MAT_OUT_REQUESTS PRIMARY KEY (REQUEST_NO)
);

CREATE INDEX IDX_MAT_OUT_REQ_TYPE ON MAT_OUT_REQUESTS (OUT_TYPE);
CREATE INDEX IDX_MAT_OUT_REQ_STATUS ON MAT_OUT_REQUESTS (STATUS);
CREATE INDEX IDX_MAT_OUT_REQ_MATUID ON MAT_OUT_REQUESTS (MAT_UID);

COMMENT ON TABLE MAT_OUT_REQUESTS IS 'G9: 기타출고 승인요청 (반품/폐기/기타)';

-- G11: SHELF_LIFE_REINSPECTS 신규 테이블
CREATE TABLE SHELF_LIFE_REINSPECTS (
  REINSPECT_NO      VARCHAR2(20)  NOT NULL,
  MAT_UID           VARCHAR2(30)  NOT NULL,
  ITEM_CODE         VARCHAR2(50)  NOT NULL,
  INSPECTOR_ID      VARCHAR2(20),
  INSPECTOR_NAME    VARCHAR2(50),
  INSPECT_DATE      DATE          NOT NULL,
  RESULT            VARCHAR2(10)  NOT NULL,
  DESTRUCT_SAMPLE_QTY NUMBER(10),
  DETAILS           CLOB,
  PREV_EXPIRY_DATE  DATE,
  NEW_EXPIRY_DATE   DATE,
  REMARK            VARCHAR2(500),
  COMPANY           VARCHAR2(50),
  PLANT_CD          VARCHAR2(50),
  CREATED_BY        VARCHAR2(50),
  CREATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_SHELF_LIFE_REINSPECTS PRIMARY KEY (REINSPECT_NO)
);

CREATE INDEX IDX_REINSPECT_MATUID ON SHELF_LIFE_REINSPECTS (MAT_UID);
CREATE INDEX IDX_REINSPECT_RESULT ON SHELF_LIFE_REINSPECTS (RESULT);

COMMENT ON TABLE SHELF_LIFE_REINSPECTS IS 'G11: 유수명자재 재검사 이력';

COMMIT;
