-- ============================================================
-- 재작업(Rework) 관련 ComCode 그룹 추가
-- 대상: REWORK_STATUS, REWORK_PROCESS_STATUS, REWORK_INSPECT_RESULT
-- 실행 전 해당 그룹/코드 존재 여부 확인 후 없는 것만 INSERT
-- ============================================================

-- REWORK_STATUS (재작업 상태)
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','REGISTERED','등록',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='REGISTERED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','QC_PENDING','품질승인대기',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='QC_PENDING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','QC_APPROVED','품질승인',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='QC_APPROVED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','QC_REJECTED','품질반려',4,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='QC_REJECTED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','PROD_PENDING','생산승인대기',5,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='PROD_PENDING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','APPROVED','승인완료',6,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='APPROVED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','PROD_REJECTED','생산반려',7,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='PROD_REJECTED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','IN_PROGRESS','진행중',8,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='IN_PROGRESS');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','INSPECT_PENDING','재검사대기',9,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='INSPECT_PENDING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','PASS','합격',10,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='PASS');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','FAIL','불합격',11,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='FAIL');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_STATUS','SCRAP','폐기',12,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_STATUS' AND CODE='SCRAP');

-- REWORK_PROCESS_STATUS (재작업 공정 상태)
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_PROCESS_STATUS','WAITING','대기',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_PROCESS_STATUS' AND CODE='WAITING');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_PROCESS_STATUS','IN_PROGRESS','진행중',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_PROCESS_STATUS' AND CODE='IN_PROGRESS');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_PROCESS_STATUS','COMPLETED','완료',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_PROCESS_STATUS' AND CODE='COMPLETED');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_PROCESS_STATUS','SKIPPED','건너뛰기',4,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_PROCESS_STATUS' AND CODE='SKIPPED');

-- REWORK_INSPECT_RESULT (재작업 검사 결과)
INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_INSPECT_RESULT','PASS','합격',1,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_INSPECT_RESULT' AND CODE='PASS');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_INSPECT_RESULT','FAIL','불합격',2,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_INSPECT_RESULT' AND CODE='FAIL');

INSERT INTO COM_CODES (GROUP_CODE,CODE,CODE_NAME,SORT_ORDER,USE_YN,COMPANY)
SELECT 'REWORK_INSPECT_RESULT','SCRAP','폐기',3,'Y','40' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COM_CODES WHERE GROUP_CODE='REWORK_INSPECT_RESULT' AND CODE='SCRAP');

COMMIT;
