import { KNOWLEDGE_CATEGORIES, type KnowledgeCategory, type KnowledgeCoverage, type KnowledgeRelation } from "@harness/shared";
import { useTranslation } from "react-i18next";
export function RelationFilters({ active, relations, coverage, onChange, compact = false }: { active: readonly KnowledgeCategory[]; relations: readonly KnowledgeRelation[]; coverage?: KnowledgeCoverage; onChange: (v: KnowledgeCategory[]) => void; compact?: boolean }) {
  const { t } = useTranslation();
  const toggle = (category: KnowledgeCategory) => onChange(active.includes(category) ? active.filter((v) => v !== category) : [...active, category]);
  const filters = <div className={compact ? "mt-2 flex flex-wrap gap-2" : "space-y-1"}>{KNOWLEDGE_CATEGORIES.map((category) => { const count = relations.filter((r) => r.category === category).length; const state = coverage?.[category] ?? "undocumented"; return <button key={category} type="button" aria-pressed={active.includes(category)} onClick={() => toggle(category)} className={`${compact ? "w-auto gap-2" : "w-full justify-between"} flex items-center rounded-md border border-transparent px-2 py-2 text-left text-sm text-text hover:border-border aria-pressed:border-primary aria-pressed:bg-surface`}><span>{t(`workflowGuide.knowledge.categories.${category}`)}</span><span className="font-mono text-[10px] text-text-muted">{count.toString().padStart(2,"0")} · {t(`workflowGuide.knowledge.coverage.${state}`)}</span></button>; })}</div>;
  if (compact) return <details className="rounded-md border border-border bg-card p-3" aria-label={t("workflowGuide.knowledge.filters.mobileLabel")}><summary className="cursor-pointer text-sm font-semibold text-text">{t("workflowGuide.knowledge.filters.mobileSummary", { count: KNOWLEDGE_CATEGORIES.length })}</summary>{filters}</details>;
  return <aside className="min-h-0 overflow-y-auto border-r border-border bg-card p-3" aria-label={t("workflowGuide.knowledge.filters.label")}><p className="mb-3 font-mono text-[11px] uppercase tracking-[0.18em] text-text-muted">{t("workflowGuide.knowledge.filters.channels", { count: KNOWLEDGE_CATEGORIES.length })}</p>{filters}<p className="mt-4 border-t border-border pt-3 text-xs leading-5 text-text-muted">{t("workflowGuide.knowledge.filters.evidenceHint")}</p></aside>;
}
