-- 검사 불량코드에 결함등급(치명/중/경)을 채운다.
--
-- 배경: 불량코드가 두 갈래다.
--   ① DEFECT_CODE_MASTERS (12건) — 등급 CRITICAL/MAJOR/MINOR 를 갖췄으나 실사용 0건
--   ② COM_CODES CONTINUITY_DEFECT(7)/VISUAL_DEFECT(8) — 검사 화면이 실제로 쓰는 코드, 등급 전부 NULL
-- 실데이터는 ② 에만 있는데 등급이 비어 있어 "이 부적합이 치명인지 경미인지" 판정 근거가 DB 에 없다.
-- NCR(부적합 보고서)이 결함구분을 요구하므로 ② 에 등급을 채운다.
-- ①↔② 코드체계 통합은 검사 화면 다수가 걸려 별건으로 둔다.
--
-- 등급 기준 (하네스):
--   CRITICAL — 전기적 기능 상실·안전 직결 (단선/단락/오배선/절연불량/크랙)
--   MAJOR    — 기능에 영향 (저항과다/간헐/이물질/치수)
--   MINOR    — 외관 수준 (스크래치/변색/찍힘/버/기타)
-- 이름이 겹치는 ① 항목과 같은 등급으로 맞췄다(CRACK=CRITICAL, DIM=MAJOR, BURR=MINOR).

UPDATE COM_CODES SET DEFECT_GRADE = 'CRITICAL', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'CONTINUITY_DEFECT'
   AND DETAIL_CODE IN ('OPEN', 'SHORT', 'MISWIRE', 'INSULATION')
/

UPDATE COM_CODES SET DEFECT_GRADE = 'MAJOR', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'CONTINUITY_DEFECT'
   AND DETAIL_CODE IN ('HIGH_R', 'INTERMIT')
/

UPDATE COM_CODES SET DEFECT_GRADE = 'MINOR', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'CONTINUITY_DEFECT'
   AND DETAIL_CODE = 'OTHER'
/

UPDATE COM_CODES SET DEFECT_GRADE = 'CRITICAL', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'VISUAL_DEFECT'
   AND DETAIL_CODE = 'CRACK'
/

UPDATE COM_CODES SET DEFECT_GRADE = 'MAJOR', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'VISUAL_DEFECT'
   AND DETAIL_CODE IN ('FOREIGN', 'DIMENSION')
/

UPDATE COM_CODES SET DEFECT_GRADE = 'MINOR', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND GROUP_CODE = 'VISUAL_DEFECT'
   AND DETAIL_CODE IN ('SCRATCH', 'DISCOLOR', 'DENT', 'BURR', 'OTHER')
/

COMMIT
/
