-- 발견단계 라벨에 현장 약어를 넣어 인식을 돕는다(IQC/IPQC/FQC/OQC/RMA).
UPDATE COM_CODES SET CODE_NAME = '수입검사(IQC)'      WHERE GROUP_CODE='NCR_FOUND_STAGE' AND DETAIL_CODE='IQC'
/
UPDATE COM_CODES SET CODE_NAME = '공정·자주검사(IPQC)' WHERE GROUP_CODE='NCR_FOUND_STAGE' AND DETAIL_CODE='PROCESS'
/
UPDATE COM_CODES SET CODE_NAME = '최종검사(FQC)'      WHERE GROUP_CODE='NCR_FOUND_STAGE' AND DETAIL_CODE='FINAL'
/
UPDATE COM_CODES SET CODE_NAME = '출하검사(OQC)'      WHERE GROUP_CODE='NCR_FOUND_STAGE' AND DETAIL_CODE='OQC'
/
UPDATE COM_CODES SET CODE_NAME = '고객불만(RMA)'      WHERE GROUP_CODE='NCR_FOUND_STAGE' AND DETAIL_CODE='CUSTOMER'
/
COMMIT
/
