-- 부적합 보고서(NCR) — 테이블 + 채번규칙 + 공통코드
-- 설계: docs/specs/2026-09-15-ncr-nonconformance-report-design.md
--
-- 감사 대응을 위해 부적합 1건을 하나의 문서번호로 묶는다. 부적합은 IQC_LOGS(수입검사),
-- INSPECT_RESULTS(공정·최종검사) 등 서로 다른 테이블에 쌓이므로, NCR 은 독립 문서로 두고
-- 출처를 SOURCE_TYPE + SOURCE_ID 참조로 붙인다.

CREATE TABLE NCR_REPORTS (
  NCR_NO              VARCHAR2(30)   NOT NULL,
  COMPANY             VARCHAR2(50)   DEFAULT '40'   NOT NULL,
  PLANT_CD            VARCHAR2(50)   DEFAULT '1000' NOT NULL,

  -- 발행
  ISSUED_AT           TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  DUE_DATE            DATE,                                   -- 회신 요구일
  ISSUE_DEPT          VARCHAR2(50),
  WRITER_CODE         VARCHAR2(50),
  WRITTEN_AT          TIMESTAMP,

  -- 분류 (대상과 발견 시점은 다를 수 있어 축을 나눈다)
  TARGET_TYPE         VARCHAR2(20)   NOT NULL,                 -- RAW_MATERIAL/SEMI_PRODUCT/FINISHED/WIP
  FOUND_STAGE         VARCHAR2(20)   NOT NULL,                 -- IQC/PROCESS/FINAL/OQC/CUSTOMER

  -- 출처 (어느 검사에서 나왔나)
  SOURCE_TYPE         VARCHAR2(30),                            -- IQC_LOG/INSPECT_RESULT/DEFECT_LOG/COMPLAINT
  SOURCE_ID           VARCHAR2(100),

  -- 대상
  ITEM_CODE           VARCHAR2(50)   NOT NULL,
  LOT_NO              VARCHAR2(50),
  SERIAL_NO           VARCHAR2(50),
  ORDER_NO            VARCHAR2(50),
  PO_NO               VARCHAR2(50),
  VENDOR_CODE         VARCHAR2(50),
  INSPECT_QTY         NUMBER(12,3),
  DEFECT_QTY          NUMBER(12,3),

  -- 부적합 내용
  DEFECT_CODE         VARCHAR2(50),
  CATEGORY_CODE       VARCHAR2(50),
  DEFECT_GRADE        VARCHAR2(20),                            -- CRITICAL/MAJOR/MINOR
  DESCRIPTION         VARCHAR2(2000),
  IMAGE_URL           VARCHAR2(500),

  -- 처리방안
  DISPOSITION         VARCHAR2(20),                            -- CONCESSION/REPAIR/REWORK/SCRAP/RETURN
  DISPOSITION_DETAIL  VARCHAR2(2000),
  DUE_ACTION_DATE     DATE,
  RESPONSIBLE_CODE    VARCHAR2(50),
  RESPONDED_AT        TIMESTAMP,

  -- 원인 / 재발방지
  CAUSE_CATEGORY      VARCHAR2(20),                            -- MAN/MACHINE/METHOD/MEASUREMENT/ENVIRONMENT
  ROOT_CAUSE          VARCHAR2(2000),
  PREVENTIVE_ACTION   VARCHAR2(2000),

  -- 승인 / 종결
  APPROVER_CODE       VARCHAR2(50),
  APPROVED_AT         TIMESTAMP,
  STATUS              VARCHAR2(20)   DEFAULT 'OPEN' NOT NULL,  -- OPEN/IN_PROGRESS/CLOSED
  CLOSED_AT           TIMESTAMP,
  CLOSED_BY           VARCHAR2(50),

  -- 시정조치 연계 (정식 CAPA 가 필요한 건에만)
  CAPA_NO             VARCHAR2(30),

  REMARK              VARCHAR2(1000),
  CREATED_BY          VARCHAR2(50),
  UPDATED_BY          VARCHAR2(50),
  CREATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_NCR_REPORTS PRIMARY KEY (NCR_NO)
)
/

CREATE INDEX IX_NCR_REPORTS_ISSUED  ON NCR_REPORTS (COMPANY, PLANT_CD, ISSUED_AT)
/
CREATE INDEX IX_NCR_REPORTS_STATUS  ON NCR_REPORTS (COMPANY, PLANT_CD, STATUS)
/
CREATE INDEX IX_NCR_REPORTS_SOURCE  ON NCR_REPORTS (SOURCE_TYPE, SOURCE_ID)
/
CREATE INDEX IX_NCR_REPORTS_ITEM    ON NCR_REPORTS (COMPANY, PLANT_CD, ITEM_CODE)
/

COMMENT ON TABLE  NCR_REPORTS IS '부적합 보고서(NCR) — 부적합 1건을 문서번호로 묶어 처리·시정조치까지 추적'
/
COMMENT ON COLUMN NCR_REPORTS.TARGET_TYPE IS '대상구분 RAW_MATERIAL/SEMI_PRODUCT/FINISHED/WIP'
/
COMMENT ON COLUMN NCR_REPORTS.FOUND_STAGE IS '발견공정 IQC/PROCESS/FINAL/OQC/CUSTOMER'
/
COMMENT ON COLUMN NCR_REPORTS.DISPOSITION IS '처리방안 CONCESSION(특채)/REPAIR/REWORK/SCRAP/RETURN(반품)'
/
COMMENT ON COLUMN NCR_REPORTS.CAUSE_CATEGORY IS '원인분류 4M1E — MAN/MACHINE/METHOD/MEASUREMENT/ENVIRONMENT'
/
COMMENT ON COLUMN NCR_REPORTS.DUE_DATE IS '회신 요구일 — 원인분석·대책 회신 기한'
/

-- 채번: NCR + YYMMDD + 3자리 (기존 AUDIT_NO/INSPECT_RESULT 와 같은 방식)
CREATE SEQUENCE SEQ_NCR_NO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/

MERGE INTO SEQ_RULES t
USING (SELECT 'NCR_NO' DOC_TYPE FROM DUAL) s
ON (t.DOC_TYPE = s.DOC_TYPE)
WHEN NOT MATCHED THEN
  INSERT (DOC_TYPE, PREFIX, SEQ_NAME, PAD_LENGTH, DATE_FORMAT, SEPARATOR, DESCRIPTION, USE_YN, COMPANY, PLANT_CD)
  VALUES ('NCR_NO', 'NCR', 'SEQ_NCR_NO', 3, 'YYMMDD', '-', '부적합보고서번호', 'Y', '40', '1000')
/

-- 공통코드: 대상구분 / 발견공정 / 처리방안(NCR 전용, 반품 포함) / 원인분류 4M1E / 상태
MERGE INTO COM_CODES t
USING (
  SELECT 'NCR_TARGET_TYPE' G, 'RAW_MATERIAL' D, '원자재' N, 1 S FROM DUAL UNION ALL
  SELECT 'NCR_TARGET_TYPE', 'SEMI_PRODUCT', '반제품', 2 FROM DUAL UNION ALL
  SELECT 'NCR_TARGET_TYPE', 'FINISHED', '완제품', 3 FROM DUAL UNION ALL
  SELECT 'NCR_TARGET_TYPE', 'WIP', '재공품', 4 FROM DUAL UNION ALL
  SELECT 'NCR_FOUND_STAGE', 'IQC', '수입검사', 1 FROM DUAL UNION ALL
  SELECT 'NCR_FOUND_STAGE', 'PROCESS', '공정검사', 2 FROM DUAL UNION ALL
  SELECT 'NCR_FOUND_STAGE', 'FINAL', '최종검사', 3 FROM DUAL UNION ALL
  SELECT 'NCR_FOUND_STAGE', 'OQC', '출하검사', 4 FROM DUAL UNION ALL
  SELECT 'NCR_FOUND_STAGE', 'CUSTOMER', '고객클레임', 5 FROM DUAL UNION ALL
  SELECT 'NCR_DISPOSITION', 'CONCESSION', '특채(진행)', 1 FROM DUAL UNION ALL
  SELECT 'NCR_DISPOSITION', 'REPAIR', '수리', 2 FROM DUAL UNION ALL
  SELECT 'NCR_DISPOSITION', 'REWORK', '재작업', 3 FROM DUAL UNION ALL
  SELECT 'NCR_DISPOSITION', 'SCRAP', '폐기', 4 FROM DUAL UNION ALL
  SELECT 'NCR_DISPOSITION', 'RETURN', '반품', 5 FROM DUAL UNION ALL
  SELECT 'NCR_CAUSE_CATEGORY', 'MAN', '사람(Man)', 1 FROM DUAL UNION ALL
  SELECT 'NCR_CAUSE_CATEGORY', 'MACHINE', '설비(Machine)', 2 FROM DUAL UNION ALL
  SELECT 'NCR_CAUSE_CATEGORY', 'METHOD', '방법(Method)', 3 FROM DUAL UNION ALL
  SELECT 'NCR_CAUSE_CATEGORY', 'MEASUREMENT', '측정(Measurement)', 4 FROM DUAL UNION ALL
  SELECT 'NCR_CAUSE_CATEGORY', 'ENVIRONMENT', '환경(Environment)', 5 FROM DUAL UNION ALL
  SELECT 'NCR_STATUS', 'OPEN', '발행', 1 FROM DUAL UNION ALL
  SELECT 'NCR_STATUS', 'IN_PROGRESS', '조치중', 2 FROM DUAL UNION ALL
  SELECT 'NCR_STATUS', 'CLOSED', '종결', 3 FROM DUAL
) s
ON (t.GROUP_CODE = s.G AND t.DETAIL_CODE = s.D)
WHEN NOT MATCHED THEN
  INSERT (GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY)
  VALUES (s.G, s.D, s.N, s.S, 'Y', '40', '1000', 'ncr-init', 'ncr-init')
/

-- 메뉴 권한 (메뉴 트리는 menuConfig.ts 가 단일 출처)
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER' ROLE_CODE, 'QC_NCR' MENU_CODE FROM DUAL UNION ALL
  SELECT 'OPERATOR', 'QC_NCR' FROM DUAL
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = '40' AND t.PLANT_CD = '1000')
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', '40', '1000')
/

COMMIT
/
