-- 2026-09-11 공정/설비 재고 수량 부동소수점 잔차 정리 (요청사항 17)
-- 원인: BOM 소수 소요량(0.67 등) 곱셈·차감 결과를 반올림 없이 저장해 0.5000000000000222 같은 잔차가 누적.
-- 코드 수정(qty-math roundQty 적용)과 함께 기존 오염 행을 소수 6자리로 정리한다.
-- 사전 실측(2026-09-11): WIP_MAT_STOCKS 5행, PROC_MAT_STOCKS 10행, MAT_STOCKS 1행.
UPDATE WIP_MAT_STOCKS
   SET QTY = ROUND(QTY, 6), AVAILABLE_QTY = ROUND(AVAILABLE_QTY, 6), UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND (QTY <> ROUND(QTY, 6) OR AVAILABLE_QTY <> ROUND(AVAILABLE_QTY, 6))
/
UPDATE PROC_MAT_STOCKS
   SET QTY = ROUND(QTY, 6), AVAILABLE_QTY = ROUND(AVAILABLE_QTY, 6), UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND (QTY <> ROUND(QTY, 6) OR AVAILABLE_QTY <> ROUND(AVAILABLE_QTY, 6))
/
UPDATE MAT_STOCKS
   SET QTY = ROUND(QTY, 6), AVAILABLE_QTY = ROUND(AVAILABLE_QTY, 6), UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND (QTY <> ROUND(QTY, 6) OR NVL(AVAILABLE_QTY, 0) <> ROUND(NVL(AVAILABLE_QTY, 0), 6))
/
COMMIT
/
