-- 2026-09-11 IQC 불합격자재 불량창고 수동입고 (요청사항 06)
-- 1) 시스템설정: IQC 불합격 재고 처리 모드 (MANUAL 기본 = 수동입고 화면에서 처리, AUTO = 종전 자동이동)
MERGE INTO SYS_CONFIGS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
   ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.CONFIG_KEY = 'IQC_FAIL_DEFECT_MOVE_MODE')
 WHEN NOT MATCHED THEN INSERT (CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, LABEL, DESCRIPTION, OPTIONS, SORT_ORDER, IS_ACTIVE, COMPANY, PLANT_CD, CREATED_BY, UPDATED_BY, CREATED_AT, UPDATED_AT)
      VALUES ('QUALITY', 'IQC_FAIL_DEFECT_MOVE_MODE', 'MANUAL', 'SELECT', 'IQC 불합격 재고 처리',
              'MANUAL: 불합격 LOT을 입하재고에 두고 「IQC불합격자재 불량창고입고」 화면에서 수동 입고 / AUTO: FAIL 저장 시 불량창고 자동이동',
              '[{"label":"수동입고(화면)","value":"MANUAL"},{"label":"자동이동","value":"AUTO"}]', 12, 'Y', '40', '1000', 'claude', 'claude', SYSTIMESTAMP, SYSTIMESTAMP)
/
-- 2) 메뉴: 자재관리 카테고리에 MAT_IQC_DEFECT_RECEIVE (자재입고이력 70 다음)
MERGE INTO MENU_CATEGORY_ITEMS t
USING (SELECT '40' COMPANY, '1000' PLANT_CD FROM DUAL) s
   ON (t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD AND t.MENU_CODE = 'MAT_IQC_DEFECT_RECEIVE')
 WHEN NOT MATCHED THEN INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
      VALUES ('MAT_IQC_DEFECT_RECEIVE', 'MATERIAL', 75, '40', '1000', SYSTIMESTAMP, 'claude', SYSTIMESTAMP, 'claude')
/
COMMIT
/
