-- 생산성분석 메뉴(PROD_PRODUCTIVITY) 등록
-- 메뉴 트리 자체는 apps/frontend/src/config/menuConfig.ts 가 단일 출처다(이 DB 에 MENUS 테이블은 없다).
-- 여기서는 역할별 접근 권한과 메뉴 카테고리 배치만 넣는다 — 같은 생산관리 조회 메뉴(PROD_RESULT_SUMMARY)와 동일하게 MANAGER/OPERATOR.
MERGE INTO ROLE_MENU_PERMISSIONS t
USING (
  SELECT 'MANAGER' ROLE_CODE, 'PROD_PRODUCTIVITY' MENU_CODE, '40' COMPANY, '1000' PLANT_CD FROM DUAL
  UNION ALL
  SELECT 'OPERATOR', 'PROD_PRODUCTIVITY', '40', '1000' FROM DUAL
) s
ON (t.ROLE_CODE = s.ROLE_CODE AND t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (ROLE_CODE, MENU_CODE, CAN_ACCESS, COMPANY, PLANT_CD)
  VALUES (s.ROLE_CODE, s.MENU_CODE, 'Y', s.COMPANY, s.PLANT_CD)
/
MERGE INTO MENU_CATEGORY_ITEMS t
USING (
  SELECT 'PROD_PRODUCTIVITY' MENU_CODE, 'PRODUCTION' CATEGORY_CODE, 95 SORT_ORDER, '40' COMPANY, '1000' PLANT_CD FROM DUAL
) s
ON (t.MENU_CODE = s.MENU_CODE AND t.COMPANY = s.COMPANY AND t.PLANT_CD = s.PLANT_CD)
WHEN NOT MATCHED THEN
  INSERT (MENU_CODE, CATEGORY_CODE, SORT_ORDER, COMPANY, PLANT_CD, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
  VALUES (s.MENU_CODE, s.CATEGORY_CODE, s.SORT_ORDER, s.COMPANY, s.PLANT_CD, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM')
/
COMMIT
/
