-- AI provider별 API 키 설정 (SYS_CONFIGS, AI 그룹) — UI 입력 대상
-- 값이 공백이면 .env(MISTRAL_API_KEY/OPENAI_API_KEY)로 폴백. Oracle ''=NULL 회피 위해 공백 1칸.
INSERT ALL
  INTO SYS_CONFIGS (CONFIG_KEY,CONFIG_GROUP,CONFIG_VALUE,CONFIG_TYPE,LABEL,DESCRIPTION,SORT_ORDER,IS_ACTIVE,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('AI_MISTRAL_KEY','AI',' ','TEXT','Mistral API 키','비우면 서버 .env의 MISTRAL_API_KEY 사용',4,'Y','40','1000','system')
  INTO SYS_CONFIGS (CONFIG_KEY,CONFIG_GROUP,CONFIG_VALUE,CONFIG_TYPE,LABEL,DESCRIPTION,SORT_ORDER,IS_ACTIVE,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('AI_OPENAI_KEY','AI',' ','TEXT','OpenAI API 키','비우면 서버 .env의 OPENAI_API_KEY 사용',5,'Y','40','1000','system')
SELECT 1 FROM DUAL;
/
