-- AI 채팅 설정 (SYS_CONFIGS, AI 그룹) — company=40, plant=1000
-- 키(MISTRAL_API_KEY)는 .env에만 저장. 여기엔 provider/model/활성화만.
INSERT ALL
  INTO SYS_CONFIGS (CONFIG_KEY,CONFIG_GROUP,CONFIG_VALUE,CONFIG_TYPE,LABEL,DESCRIPTION,SORT_ORDER,IS_ACTIVE,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('AI_ENABLED','AI','Y','BOOLEAN','AI 채팅 활성화','AI 채팅 기능 사용 여부',1,'Y','40','1000','system')
  INTO SYS_CONFIGS (CONFIG_KEY,CONFIG_GROUP,CONFIG_VALUE,CONFIG_TYPE,LABEL,DESCRIPTION,SORT_ORDER,IS_ACTIVE,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('AI_PROVIDER','AI','mistral','TEXT','AI 제공자','LLM 제공자 (현재 mistral 지원)',2,'Y','40','1000','system')
  INTO SYS_CONFIGS (CONFIG_KEY,CONFIG_GROUP,CONFIG_VALUE,CONFIG_TYPE,LABEL,DESCRIPTION,SORT_ORDER,IS_ACTIVE,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('AI_MODEL','AI','mistral-large-latest','TEXT','AI 모델','Mistral 모델명 (예: mistral-large-latest, mistral-small-latest)',3,'Y','40','1000','system')
SELECT 1 FROM DUAL;
/
