-- W001(원자재창고, 기본 RAW 창고)에 적재 로케이션 등록
-- company=40, plant_cd=1000. CREATED_AT/UPDATED_AT/USE_YN은 DB DEFAULT 사용.
INSERT ALL
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-A-01-01','원자재창고 A구역 1열 1단','A','01','01','1','Y','40','1000','system')
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-A-01-02','원자재창고 A구역 1열 2단','A','01','02','1','Y','40','1000','system')
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-A-02-01','원자재창고 A구역 2열 1단','A','02','01','1','Y','40','1000','system')
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-A-02-02','원자재창고 A구역 2열 2단','A','02','02','1','Y','40','1000','system')
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-B-01-01','원자재창고 B구역 1열 1단','B','01','01','1','Y','40','1000','system')
  INTO WAREHOUSE_LOCATIONS (WAREHOUSE_CODE,LOCATION_CODE,LOCATION_NAME,ZONE,ROW_NO,COL_NO,LEVEL_NO,USE_YN,COMPANY,PLANT_CD,CREATED_BY)
    VALUES ('W001','W001-B-01-02','원자재창고 B구역 1열 2단','B','01','02','1','Y','40','1000','system')
SELECT 1 FROM DUAL;
/
