-- Task: STOCK_TRANSACTIONS 계정(ACCOUNT) 컬럼 + 입고/재고보정 계정 공통코드
-- 용도: 입고계정(기타입고/정상입고), 재고보정계정을 수불 트랜잭션에 기록
-- 회사 '40' / 공장 '1000'

-- 1) STOCK_TRANSACTIONS.ACCOUNT 컬럼 추가
ALTER TABLE STOCK_TRANSACTIONS ADD (ACCOUNT VARCHAR2(20))
/

-- 2) 입고계정 공통코드 (RECEIPT_ACCOUNT) - 기본값: PROD(양산)
MERGE INTO COM_CODES t
USING (
  SELECT 'RECEIPT_ACCOUNT' GROUP_CODE, 'PROD'   DETAIL_CODE, '양산'        CODE_NAME, 1  SORT_ORDER FROM DUAL UNION ALL
  SELECT 'RECEIPT_ACCOUNT', 'MRO',    '소모품(MRO)', 2  FROM DUAL UNION ALL
  SELECT 'RECEIPT_ACCOUNT', 'SAMPLE', '샘플',        3  FROM DUAL UNION ALL
  SELECT 'RECEIPT_ACCOUNT', 'RND',    '연구개발',    4  FROM DUAL UNION ALL
  SELECT 'RECEIPT_ACCOUNT', 'ETC',    '기타',        99 FROM DUAL
) s ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_BY)
VALUES ('40', '1000', s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', 'SYSTEM')
/

-- 3) 재고보정계정 공통코드 (ADJUST_ACCOUNT) - 기본값: STOCK_ADJ(재고보정)
MERGE INTO COM_CODES t
USING (
  SELECT 'ADJUST_ACCOUNT' GROUP_CODE, 'STOCK_ADJ' DETAIL_CODE, '재고보정' CODE_NAME, 1  SORT_ORDER FROM DUAL UNION ALL
  SELECT 'ADJUST_ACCOUNT', 'LOSS', '감모/손실', 2  FROM DUAL UNION ALL
  SELECT 'ADJUST_ACCOUNT', 'GAIN', '과잉/이익', 3  FROM DUAL UNION ALL
  SELECT 'ADJUST_ACCOUNT', 'ETC',  '기타',      99 FROM DUAL
) s ON (t.COMPANY = '40' AND t.PLANT_CD = '1000' AND t.GROUP_CODE = s.GROUP_CODE AND t.DETAIL_CODE = s.DETAIL_CODE)
WHEN NOT MATCHED THEN INSERT (COMPANY, PLANT_CD, GROUP_CODE, DETAIL_CODE, CODE_NAME, SORT_ORDER, USE_YN, CREATED_BY)
VALUES ('40', '1000', s.GROUP_CODE, s.DETAIL_CODE, s.CODE_NAME, s.SORT_ORDER, 'Y', 'SYSTEM')
/
