-- Phase 1: IQC 계층 (자식 → 부모 순)
DELETE FROM IQC_PART_SPEC_ITEMS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM IQC_PART_SPECS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM IQC_PART_LINKS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM IQC_ITEM_MASTERS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/

-- Phase 2: 구매 PO
DELETE FROM PURCHASE_ORDER_ITEMS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM PURCHASE_ORDERS
WHERE PO_NO NOT IN (
  SELECT DISTINCT PO_ID FROM PURCHASE_ORDER_ITEMS
);
/

-- Phase 3: 영업 CO (전체 삭제)
DELETE FROM CUSTOMER_ORDER_ITEMS WHERE 1=1;
/
DELETE FROM CUSTOMER_ORDERS WHERE 1=1;
/

-- Phase 4: 작업지시 (전체 삭제)
DELETE FROM JOB_ORDERS WHERE 1=1;
/

-- Phase 5: 자재 LOT/재고 (고아 1건씩)
DELETE FROM STOCK_TRANSACTIONS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM MAT_STOCKS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM MAT_LOTS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/
DELETE FROM MAT_ARRIVALS
WHERE ITEM_CODE NOT IN (SELECT ITEM_CODE FROM ITEM_MASTERS);
/

-- Phase 6: 기타 (전체 삭제)
DELETE FROM FG_LABELS WHERE 1=1;
/
DELETE FROM SHIPMENT_ORDER_ITEMS WHERE 1=1;
/
DELETE FROM SHIPMENT_ORDERS WHERE 1=1;
/
DELETE FROM PHYSICAL_INV_COUNT_DETAILS WHERE 1=1;
/
DELETE FROM INV_ADJ_LOGS WHERE 1=1;
/

COMMIT;
/
