-- =============================================
-- Phase 2: 구매 발주 (PURCHASE_ORDERS + PURCHASE_ORDER_ITEMS)
-- =============================================

INSERT INTO PURCHASE_ORDERS (PO_NO,PARTNER_ID,PARTNER_NAME,STATUS,ORDER_DATE,DUE_DATE,USE_TYPE,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PO-2026-001','VND-001','한국단자공업','OPEN',DATE '2026-06-01',DATE '2026-06-30','PROD','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDERS (PO_NO,PARTNER_ID,PARTNER_NAME,STATUS,ORDER_DATE,DUE_DATE,USE_TYPE,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PO-2026-002','VND-002','대한전선','OPEN',DATE '2026-06-01',DATE '2026-06-30','PROD','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDERS (PO_NO,PARTNER_ID,PARTNER_NAME,STATUS,ORDER_DATE,DUE_DATE,USE_TYPE,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PO-2026-003','VND-003','삼화부자재','PARTIAL',DATE '2026-06-01',DATE '2026-06-20','PROD','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDERS (PO_NO,PARTNER_ID,PARTNER_NAME,STATUS,ORDER_DATE,DUE_DATE,USE_TYPE,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PO-2026-004','HS0001','유진플랫폼','PARTIAL',DATE '2026-05-20',DATE '2026-06-10','PROD','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDERS (PO_NO,PARTNER_ID,PARTNER_NAME,STATUS,ORDER_DATE,DUE_DATE,USE_TYPE,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('PO-2026-005','VND-001','한국단자공업','OPEN',DATE '2026-06-04',DATE '2026-07-31','MRO','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- PO-2026-001 (VND-001, 터미널류)
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-001','TMN-A',1000,0,'OPEN',1,10,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-001','TMN-B',800,0,'OPEN',2,20,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-001','TMN-C',600,0,'OPEN',3,30,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-001','TMN-SE1',500,0,'OPEN',4,40,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-001','CNTR001',500,0,'OPEN',5,50,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- PO-2026-002 (VND-002, 전선류)
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-002','CBL-A',5000,0,'OPEN',1,10,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-002','CBL-B',3000,0,'OPEN',2,20,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-002','CBL-SE',2000,0,'OPEN',3,30,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-002','TP0001',1000,0,'OPEN',4,40,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-002','TUB-A',500,0,'OPEN',5,50,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- PO-2026-003 (VND-003, 고무/홀더류) PARTIAL
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','RSL-A',300,200,'PARTIAL',1,10,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','RSL-B',300,200,'PARTIAL',2,20,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','RSL-T',200,100,'PARTIAL',3,30,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','HLD-01',200,0,'OPEN',4,40,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','CSH001',150,0,'OPEN',5,50,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-003','HSG0001',150,0,'OPEN',6,60,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- PO-2026-004 (HS0001, 기타 원자재) PARTIAL
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-004','NFT-A',100,100,'CLOSE',1,10,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-004','PHDL001',100,100,'CLOSE',2,20,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- PO-2026-005 (소모품)
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','CUTBL001',50,0,'OPEN',1,10,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','CUTBL002',50,0,'OPEN',2,20,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','CUTBL003',50,0,'OPEN',3,30,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','CUTBL004',50,0,'OPEN',4,40,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','CUTBL009',30,0,'OPEN',5,50,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','APPCT-A',20,0,'OPEN',6,60,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','APPCT-B',20,0,'OPEN',7,70,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','APPCT-SE',10,0,'OPEN',8,80,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','JIGHD-A',10,0,'OPEN',9,90,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','JIGHD-B',10,0,'OPEN',10,100,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','JIGHD-C',10,0,'OPEN',11,110,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO PURCHASE_ORDER_ITEMS (PO_ID,ITEM_CODE,ORDER_QTY,RECEIVED_QTY,LINE_STATUS,SEQ,LINE_NO,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT) VALUES ('PO-2026-005','JIGHD-D',10,0,'OPEN',12,120,'40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

COMMIT;
/
