-- =============================================
-- Phase 3: IQC 검사 기준 데이터
-- IQC_ITEM_MASTERS + IQC_PART_LINKS + IQC_PART_SPECS + IQC_PART_SPEC_ITEMS
-- =============================================

-- IQC_ITEM_MASTERS: 품목별 검사 항목 (레거시 구조)
-- CBL-A (전선A)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A','Electrical continuity check',0,1,'ohm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A','Wire outside diameter check',NULL,NULL,'mm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- CBL-B (전선B)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-B','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-B','Electrical continuity check',0,1,'ohm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- TMN-A (터미널A)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A','Terminal plating check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A','Terminal crimp dimension check',NULL,NULL,'mm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- TMN-B (터미널B)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-B','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-B','Terminal plating check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- RSL-A (고무씰A)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-A','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-A','Flexibility check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- RSL-B
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-B','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- CNTR001 (커넥터)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CNTR001','Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CNTR001','Connector lock function check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- IQC_PART_SPECS: 품목별 샘플링 기준
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-A',5,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-B',5,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-SE',3,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-A',5,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-B',5,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-C',3,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-A',3,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-B',3,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CNTR001',5,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPECS (COMPANY,PLANT_CD,ITEM_CODE,SAMPLE_QTY,IS_DEST,USE_YN,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','HLD-01',3,'N','Y','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- IQC_PART_SPEC_ITEMS: 품목별 검사 항목 (IQC_ITEM_POOL 참조)
-- CBL-A
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-A',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,LSL,USL,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-A',20,'IQC-CONTINUITY',0,1,'Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-A',30,'IQC-WIRE-OD','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- CBL-B
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-B',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,LSL,USL,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-B',20,'IQC-CONTINUITY',0,1,'Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-B',30,'IQC-WIRE-OD','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- CBL-SE
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-SE',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,LSL,USL,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CBL-SE',20,'IQC-CONTINUITY',0,1,'Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- TMN-A
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-A',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-A',20,'IQC-PLATING','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-A',30,'IQC-CRIMP-DIM','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-A',40,'IQC-LOCK','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- TMN-B
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-B',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-B',20,'IQC-PLATING','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-B',30,'IQC-CRIMP-DIM','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- TMN-C
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-C',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','TMN-C',20,'IQC-PLATING','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- RSL-A
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-A',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-A',20,'IQC-FLEX','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-A',30,'IQC-FIT','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- RSL-B
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-B',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','RSL-B',20,'IQC-FLEX','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- CNTR001
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CNTR001',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CNTR001',20,'IQC-LOCK','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','CNTR001',30,'IQC-CONN-DIM','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
-- HLD-01
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','HLD-01',10,'IQC-VISUAL','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_SPEC_ITEMS (COMPANY,PLANT_CD,ITEM_CODE,SEQ,INSP_ITEM_CODE,USE_YN,CREATED_AT,UPDATED_AT)
VALUES ('40','1000','HLD-01',20,'IQC-FIT','Y',SYSTIMESTAMP,SYSTIMESTAMP);
/

-- IQC_PART_LINKS: 품목+공급업체 연결
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A','VND-002','GRP-CBL','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('CBL-B','VND-002','GRP-CBL','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('CBL-SE','VND-002','GRP-CBL','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A','VND-001','GRP-TMN','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('TMN-B','VND-001','GRP-TMN','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('TMN-C','VND-001','GRP-TMN','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('RSL-A','VND-003','GRP-RSL','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('RSL-B','VND-003','GRP-RSL','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('CNTR001','VND-001','GRP-CNTR','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_PART_LINKS (ITEM_CODE,PARTNER_ID,GROUP_ID,USE_YN,COMPANY,PLANT_CD,CREATED_BY,CREATED_AT,UPDATED_AT)
VALUES ('HLD-01','VND-003','GRP-HLD','Y','40','1000','seed',SYSTIMESTAMP,SYSTIMESTAMP);
/

COMMIT;
/
