-- IQC_ITEM_MASTERS: 품목별 검사 항목 (SEQ 포함)
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A',20,'Electrical continuity check',0,1,'ohm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-A',30,'Wire outside diameter check',NULL,NULL,'mm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-B',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CBL-B',20,'Electrical continuity check',0,1,'ohm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A',20,'Terminal plating check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-A',30,'Terminal crimp dimension check',NULL,NULL,'mm','Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-B',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('TMN-B',20,'Terminal plating check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-A',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-A',20,'Flexibility check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('RSL-B',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CNTR001',10,'Appearance and damage check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/
INSERT INTO IQC_ITEM_MASTERS (ITEM_CODE,SEQ,INSPECT_ITEM,LSL,USL,UNIT,USE_YN,COMPANY,PLANT_CD,CREATED_AT,UPDATED_AT)
VALUES ('CNTR001',20,'Connector lock function check',NULL,NULL,NULL,'Y','40','1000',SYSTIMESTAMP,SYSTIMESTAMP);
/

COMMIT;
/
