-- =============================================================
-- 08 cleanup: 08_seed_monitoring_boards.sql 로 넣은 시드 전량 제거 + 마스터 원복
-- =============================================================
DELETE FROM DEFECT_LOGS WHERE PROD_RESULT_ID LIKE 'PRSEED-%'
/
DELETE FROM PROD_RESULTS WHERE RESULT_NO LIKE 'PRSEED-%'
/
DELETE FROM JOB_ORDERS WHERE ORDER_NO LIKE 'WOSEED-%'
/
DELETE FROM REPAIR_ORDERS WHERE SEQ BETWEEN 9001 AND 9008 AND CREATED_BY = 'SEED'
/
UPDATE EQUIP_MASTERS SET STATUS = 'NORMAL', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND EQUIP_CODE IN ('EQ-CRIMP-03', 'EQ-OINSP-02', 'EQ-PRC-STRIP-02', 'EQ-TINSP-02')
/
UPDATE ITEM_MASTERS SET SAFETY_STOCK = 0, UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND ITEM_CODE IN ('CRRKEB6167','CRRTEB3840','DLMLS6-3-3','HKEAN1W002FA','NBC3-5L','TKEG1WFSCD','6TBE11A000','VSFT1-201','6TPH1A0190','6TPP210190')
/
DELETE FROM MAT_STOCKS WHERE MAT_UID LIKE 'SEED-LOT-%'
/
DELETE FROM MAT_LOTS WHERE MAT_UID LIKE 'SEED-LOT-%'
/
DELETE FROM PRODUCT_STOCKS WHERE CREATED_BY = 'SEED' AND COMPANY = '40' AND PLANT_CD = '1000'
/
DELETE FROM STOCK_TRANSACTIONS WHERE TRANS_NO LIKE 'TXSEED-%'
/
COMMIT
/
