-- =============================================================
-- 08: 모니터링 보드 시연용 시드 (생산현황/품질/재고/작업지시/설비가동)
--   ⚠️ 운영(현장 사용 중) DB에 실행 금지 — 시연/데모 전용.
--      실행하면 실제 품목(MAG_ 계열 포함)에 SEED 작업지시/실적/LOT/재고가 생성되어
--      현장에서 "정체불명 데이터 자동 생성"으로 보고된 사례 있음 (2026-09-03 개선요청 10-a).
--      시연 후에는 반드시 08_cleanup_monitoring_seed.sql 로 전량 되돌릴 것.
--   - 모든 식별자에 SEED 접두어를 붙여 08_cleanup_monitoring_seed.sql 로 되돌릴 수 있다.
--   - "오늘" 기준은 DB 의 TRUNC(SYSDATE). 실행일 기준으로 지시일/실적시각이 잡힌다.
--   - 실행: python oracle_connector.py --site JSHANES --execute-file tools/seed/08_seed_monitoring_boards.sql
-- =============================================================

-- -------------------------------------------------------------
-- 1. 오늘 작업지시 16건: RUNNING 7 / HOLD 2 / WAITING 4 / DONE 3
--    GOOD/DEFECT 는 아래 PROD_RESULTS 합계로 뒤에서 채운다.
-- -------------------------------------------------------------
INSERT INTO JOB_ORDERS (ORDER_NO, ITEM_CODE, LINE_CODE, PROCESS_CODE, EQUIP_CODE, PLAN_QTY, GOOD_QTY, DEFECT_QTY, PRIORITY, STATUS, ERP_SYNC_YN, PLAN_DATE, START_TIME, COMPANY, PLANT_CD, CREATED_BY, REMARK)
SELECT ord, item, line, pc, eq, plan, 0, 0, pri, st, 'N', TRUNC(SYSDATE),
       CASE WHEN st IN ('RUNNING','HOLD','DONE') THEN TRUNC(SYSDATE) + 6/24 END,
       '40', '1000', 'SEED', '모니터링 시드'
FROM (
  SELECT 'WOSEED-01' ord, 'N91H00-X9800'           item, 'LINE-03' line, 'MASSY' pc, 'EQ-MASSY-01' eq, 1200 plan, 1 pri, 'RUNNING' st FROM DUAL UNION ALL
  SELECT 'WOSEED-02', 'N91H00-X9800-S',        'LINE-04', 'TUBHT', 'EQ-TUBHT-01',  800, 1, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-03', 'N91H00-X9800-S-A',      'LINE-02', 'CRMPB', 'EQ-CRMPB-01', 1500, 2, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-04', 'N91H00-X9800-C1',       'LINE-01', 'SHDRM', 'EQ-SHDRM-01',  600, 2, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-05', 'N91H00-X9800-S-AB',     'LINE-02', 'HEXCP', 'EQ-HEXCP-02', 1000, 3, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-06', 'N91H00-X9800-C2',       'LINE-01', 'ATCNS', 'EQ-ATCNS-02', 2000, 3, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-07', 'MAG_EAD65942601',       'LINE-05', 'AINSP', 'EQ-AINSP-01',  500, 4, 'RUNNING' FROM DUAL UNION ALL
  SELECT 'WOSEED-08', 'N91H00-X9800-C1-A',     'LINE-02', 'CRMPF', 'EQ-CRMPF-01',  700, 2, 'HOLD'    FROM DUAL UNION ALL
  SELECT 'WOSEED-09', 'N91H00-X9800-C2-A',     'LINE-02', 'WELDR', 'EQ-WELDR-01',  400, 4, 'HOLD'    FROM DUAL UNION ALL
  SELECT 'WOSEED-10', 'N91H00-X9800',          'LINE-03', 'MASSY', 'EQ-MASSY-01',  900, 3, 'WAITING' FROM DUAL UNION ALL
  SELECT 'WOSEED-11', 'N91H00-X9800-S-ABC',    'LINE-02', 'HEXCP', 'EQ-HEXCP-01', 1100, 4, 'WAITING' FROM DUAL UNION ALL
  SELECT 'WOSEED-12', 'N91H00-X9800-R',        'LINE-05', 'FINSP', NULL,           300, 5, 'WAITING' FROM DUAL UNION ALL
  SELECT 'WOSEED-13', 'MAG_EAD65942601-ABL001','LINE-01', 'ATCUT', 'EQ-ATCUT-01', 1600, 5, 'WAITING' FROM DUAL UNION ALL
  SELECT 'WOSEED-14', 'N91H00-X9800-S',        'LINE-04', 'TUBHT', 'EQ-TUBHT-01',  500, 1, 'DONE'    FROM DUAL UNION ALL
  SELECT 'WOSEED-15', 'N91H00-X9800-C1',       'LINE-01', 'STRPB', 'EQ-STRPB-01',  800, 1, 'DONE'    FROM DUAL UNION ALL
  SELECT 'WOSEED-16', 'N91H00-X9800_1',        'LINE-03', 'SASSY', 'EQ-SASSY-01',  350, 2, 'DONE'    FROM DUAL
)
/

-- -------------------------------------------------------------
-- 2. 오늘 시간대별 생산실적 (06~15시, 10슬롯) — RUNNING/HOLD/DONE 12건 × 10 = 120행
--    f = 달성률 목표, dr = 불량률, v = 시간대별 변동(1) / 균등(0, DONE 은 계획과 정확히 일치)
--    CREATED_AT 에 지시별 분(minute) 오프셋을 둬 DEFECT_LOGS PK(OCCUR_TIME) 충돌을 피한다.
-- -------------------------------------------------------------
INSERT INTO PROD_RESULTS (RESULT_NO, ORDER_NO, EQUIP_CODE, PROCESS_CODE, GOOD_QTY, DEFECT_QTY, START_TIME, END_TIME, STATUS, SHIFT_CODE, PRODUCTION_TYPE, COMPANY, PLANT_CD, CREATED_BY, CREATED_AT, UPDATED_AT)
SELECT 'PRSEED-T' || LPAD(o.k, 2, '0') || '-' || LPAD(h.n, 2, '0'),
       o.ord, o.eq, o.pc,
       ROUND(o.plan * o.f / 10 * (1 + o.v * (MOD(h.n * 7 + o.k, 5) - 2) / 10)),
       ROUND(o.plan * o.f / 10 * (1 + o.v * (MOD(h.n * 7 + o.k, 5) - 2) / 10) * o.dr),
       TRUNC(SYSDATE) + (5 + h.n) / 24 + o.k / 1440,
       TRUNC(SYSDATE) + (5 + h.n) / 24 + (50 + o.k) / 1440,
       'DONE', 'DAY', 'MASS', '40', '1000', 'SEED',
       TRUNC(SYSDATE) + (5 + h.n) / 24 + (30 + o.k) / 1440,
       TRUNC(SYSDATE) + (5 + h.n) / 24 + (30 + o.k) / 1440
FROM (
  SELECT  1 k, 'WOSEED-01' ord, 'EQ-MASSY-01' eq, 'MASSY' pc, 1200 plan, 0.65 f, 0.015 dr, 1 v FROM DUAL UNION ALL
  SELECT  2, 'WOSEED-02', 'EQ-TUBHT-01', 'TUBHT',  800, 0.80, 0.010, 1 FROM DUAL UNION ALL
  SELECT  3, 'WOSEED-03', 'EQ-CRMPB-01', 'CRMPB', 1500, 0.28, 0.040, 1 FROM DUAL UNION ALL
  SELECT  4, 'WOSEED-04', 'EQ-SHDRM-01', 'SHDRM',  600, 0.98, 0.008, 1 FROM DUAL UNION ALL
  SELECT  5, 'WOSEED-05', 'EQ-HEXCP-02', 'HEXCP', 1000, 0.31, 0.030, 1 FROM DUAL UNION ALL
  SELECT  6, 'WOSEED-06', 'EQ-ATCNS-02', 'ATCNS', 2000, 0.575, 0.020, 1 FROM DUAL UNION ALL
  SELECT  7, 'WOSEED-07', 'EQ-AINSP-01', 'AINSP',  500, 0.44, 0.012, 1 FROM DUAL UNION ALL
  SELECT  8, 'WOSEED-08', 'EQ-CRMPF-01', 'CRMPF',  700, 0.30, 0.160, 1 FROM DUAL UNION ALL
  SELECT  9, 'WOSEED-09', 'EQ-WELDR-01', 'WELDR',  400, 0.24, 0.070, 1 FROM DUAL UNION ALL
  SELECT 14, 'WOSEED-14', 'EQ-TUBHT-01', 'TUBHT',  500, 1.00, 0.010, 0 FROM DUAL UNION ALL
  SELECT 15, 'WOSEED-15', 'EQ-STRPB-01', 'STRPB',  800, 1.00, 0.014, 0 FROM DUAL UNION ALL
  SELECT 16, 'WOSEED-16', 'EQ-SASSY-01', 'SASSY',  350, 1.00, 0.006, 0 FROM DUAL
) o
CROSS JOIN (SELECT LEVEL n FROM DUAL CONNECT BY LEVEL <= 10) h
/

-- -------------------------------------------------------------
-- 3. 최근 6일 일별 실적 (품질 보드 7일 추이용) — 12지시 × 6일 = 72행, 불량률 1~5% 변동
-- -------------------------------------------------------------
INSERT INTO PROD_RESULTS (RESULT_NO, ORDER_NO, EQUIP_CODE, PROCESS_CODE, GOOD_QTY, DEFECT_QTY, START_TIME, END_TIME, STATUS, SHIFT_CODE, PRODUCTION_TYPE, COMPANY, PLANT_CD, CREATED_BY, CREATED_AT, UPDATED_AT)
SELECT 'PRSEED-D' || d.n || '-' || LPAD(o.k, 2, '0'),
       o.ord, o.eq, o.pc,
       ROUND(o.plan * 0.9 * (0.7 + MOD(d.n * 11 + o.k * 3, 7) / 10)),
       ROUND(o.plan * 0.9 * (0.7 + MOD(d.n * 11 + o.k * 3, 7) / 10) * (0.01 + MOD(d.n + o.k, 5) * 0.01)),
       TRUNC(SYSDATE) - d.n + 8 / 24, TRUNC(SYSDATE) - d.n + 17 / 24,
       'DONE', 'DAY', 'MASS', '40', '1000', 'SEED',
       TRUNC(SYSDATE) - d.n + 17 / 24 + o.k / 1440,
       TRUNC(SYSDATE) - d.n + 17 / 24 + o.k / 1440
FROM (
  SELECT  1 k, 'WOSEED-01' ord, 'EQ-MASSY-01' eq, 'MASSY' pc, 1200 plan FROM DUAL UNION ALL
  SELECT  2, 'WOSEED-02', 'EQ-TUBHT-01', 'TUBHT',  800 FROM DUAL UNION ALL
  SELECT  3, 'WOSEED-03', 'EQ-CRMPB-01', 'CRMPB', 1500 FROM DUAL UNION ALL
  SELECT  4, 'WOSEED-04', 'EQ-SHDRM-01', 'SHDRM',  600 FROM DUAL UNION ALL
  SELECT  5, 'WOSEED-05', 'EQ-HEXCP-02', 'HEXCP', 1000 FROM DUAL UNION ALL
  SELECT  6, 'WOSEED-06', 'EQ-ATCNS-02', 'ATCNS', 2000 FROM DUAL UNION ALL
  SELECT  7, 'WOSEED-07', 'EQ-AINSP-01', 'AINSP',  500 FROM DUAL UNION ALL
  SELECT  8, 'WOSEED-08', 'EQ-CRMPF-01', 'CRMPF',  700 FROM DUAL UNION ALL
  SELECT  9, 'WOSEED-09', 'EQ-WELDR-01', 'WELDR',  400 FROM DUAL UNION ALL
  SELECT 14, 'WOSEED-14', 'EQ-TUBHT-01', 'TUBHT',  500 FROM DUAL UNION ALL
  SELECT 15, 'WOSEED-15', 'EQ-STRPB-01', 'STRPB',  800 FROM DUAL UNION ALL
  SELECT 16, 'WOSEED-16', 'EQ-SASSY-01', 'SASSY',  350 FROM DUAL
) o
CROSS JOIN (SELECT LEVEL n FROM DUAL CONNECT BY LEVEL <= 6) d
/

-- 작업지시 실적 = 오늘 실적 합계 (DONE 은 균등분할이라 계획과 정확히 일치)
UPDATE JOB_ORDERS jo
   SET (GOOD_QTY, DEFECT_QTY) = (
         SELECT NVL(SUM(GOOD_QTY), 0), NVL(SUM(DEFECT_QTY), 0)
           FROM PROD_RESULTS pr
          WHERE pr.ORDER_NO = jo.ORDER_NO AND pr.RESULT_NO LIKE 'PRSEED-T%'),
       END_TIME = CASE WHEN jo.STATUS = 'DONE' THEN TRUNC(SYSDATE) + 16 / 24 END
 WHERE jo.ORDER_NO LIKE 'WOSEED-%' AND jo.STATUS <> 'WAITING'
/

-- -------------------------------------------------------------
-- 4. 오늘 불량 이력 — 실적별 불량수량을 불량코드 1~2건으로 분배 (품질 보드 TOP 불량유형용)
-- -------------------------------------------------------------
INSERT INTO DEFECT_LOGS (OCCUR_TIME, SEQ, PROD_RESULT_ID, DEFECT_CODE, DEFECT_NAME, QTY, STATUS, COMPANY, PLANT_CD, CREATED_BY)
SELECT pr.CREATED_AT, 1, pr.RESULT_NO, dc.DEFECT_CODE, dc.DEFECT_NAME,
       CASE WHEN pr.DEFECT_QTY >= 4 THEN CEIL(pr.DEFECT_QTY / 2) ELSE pr.DEFECT_QTY END,
       'WAIT', '40', '1000', 'SEED'
  FROM PROD_RESULTS pr
  JOIN DEFECT_CODE_MASTERS dc
    ON dc.COMPANY = '40'
   AND dc.DEFECT_CODE = CASE MOD(TO_NUMBER(SUBSTR(pr.RESULT_NO, 9, 2)) * 3 + TO_NUMBER(SUBSTR(pr.RESULT_NO, -2)), 8)
                          WHEN 0 THEN 'APP' WHEN 1 THEN 'ASM' WHEN 2 THEN 'CRACK' WHEN 3 THEN 'DIM'
                          WHEN 4 THEN 'FUNC' WHEN 5 THEN 'WELD' WHEN 6 THEN 'WORK' ELSE 'MAT' END
 WHERE pr.RESULT_NO LIKE 'PRSEED-T%' AND pr.DEFECT_QTY > 0
/
INSERT INTO DEFECT_LOGS (OCCUR_TIME, SEQ, PROD_RESULT_ID, DEFECT_CODE, DEFECT_NAME, QTY, STATUS, COMPANY, PLANT_CD, CREATED_BY)
SELECT pr.CREATED_AT, 2, pr.RESULT_NO, dc.DEFECT_CODE, dc.DEFECT_NAME,
       FLOOR(pr.DEFECT_QTY / 2), 'WAIT', '40', '1000', 'SEED'
  FROM PROD_RESULTS pr
  JOIN DEFECT_CODE_MASTERS dc
    ON dc.COMPANY = '40'
   AND dc.DEFECT_CODE = CASE MOD(TO_NUMBER(SUBSTR(pr.RESULT_NO, 9, 2)) * 3 + TO_NUMBER(SUBSTR(pr.RESULT_NO, -2)) + 3, 8)
                          WHEN 0 THEN 'APP' WHEN 1 THEN 'ASM' WHEN 2 THEN 'CRACK' WHEN 3 THEN 'DIM'
                          WHEN 4 THEN 'FUNC' WHEN 5 THEN 'WELD' WHEN 6 THEN 'WORK' ELSE 'MAT' END
 WHERE pr.RESULT_NO LIKE 'PRSEED-T%' AND pr.DEFECT_QTY >= 4
/

-- -------------------------------------------------------------
-- 5. 수리 현황 — 대기 3 / 수리중 2 / 금일 완료 3 (PK: REPAIR_DATE+SEQ, SEQ 9001~9008 사용)
-- -------------------------------------------------------------
INSERT INTO REPAIR_ORDERS (REPAIR_DATE, SEQ, STATUS, ITEM_CODE, ITEM_NAME, QTY, SOURCE_PROCESS, DEFECT_TYPE, RECEIVED_AT, COMPLETED_AT, REPAIR_RESULT, COMPANY, PLANT_CD, CREATED_BY, REMARK)
SELECT TRUNC(SYSDATE), 9000 + n, st, item, item, 1, pc, dt,
       TRUNC(SYSDATE) + (7 + n) / 24,
       CASE WHEN st = 'COMPLETED' THEN TRUNC(SYSDATE) + (9 + n) / 24 END,
       CASE WHEN st = 'COMPLETED' THEN 'REPAIRED' END,
       '40', '1000', 'SEED', '모니터링 시드'
FROM (
  SELECT 1 n, 'RECEIVED'  st, 'N91H00-X9800'    item, 'MASSY' pc, 'ASM'   dt FROM DUAL UNION ALL
  SELECT 2,   'RECEIVED',     'N91H00-X9800',        'AINSP',    'FUNC'  FROM DUAL UNION ALL
  SELECT 3,   'RECEIVED',     'N91H00-X9800_1',      'SASSY',    'APP'   FROM DUAL UNION ALL
  SELECT 4,   'IN_REPAIR',    'N91H00-X9800',        'MASSY',    'CRACK' FROM DUAL UNION ALL
  SELECT 5,   'IN_REPAIR',    'MAG_EAD65942601',     'AINSP',    'WELD'  FROM DUAL UNION ALL
  SELECT 6,   'COMPLETED',    'N91H00-X9800',        'MASSY',    'DIM'   FROM DUAL UNION ALL
  SELECT 7,   'COMPLETED',    'N91H00-X9800-R',      'FINSP',    'WORK'  FROM DUAL UNION ALL
  SELECT 8,   'COMPLETED',    'N91H00-X9800_1',      'SASSY',    'MAT'   FROM DUAL
)
/

-- -------------------------------------------------------------
-- 6. 설비 상태 다양화 — 정지 2대 / 점검 2대 (cleanup 에서 NORMAL 복귀)
-- -------------------------------------------------------------
UPDATE EQUIP_MASTERS SET STATUS = 'STOP', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000' AND EQUIP_CODE IN ('EQ-CRIMP-03', 'EQ-OINSP-02')
/
UPDATE EQUIP_MASTERS SET STATUS = 'MAINT', UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000' AND EQUIP_CODE IN ('EQ-PRC-STRIP-02', 'EQ-TINSP-02')
/

-- -------------------------------------------------------------
-- 7. 재고 보드 — 안전재고 (현재고 대비 미달 9품목 + 충족 1품목)
-- -------------------------------------------------------------
UPDATE ITEM_MASTERS SET SAFETY_STOCK = CASE ITEM_CODE
    WHEN 'CRRKEB6167' THEN 500  WHEN 'CRRTEB3840' THEN 500  WHEN 'DLMLS6-3-3' THEN 300
    WHEN 'HKEAN1W002FA' THEN 200 WHEN 'NBC3-5L' THEN 100    WHEN 'TKEG1WFSCD' THEN 1000
    WHEN '6TBE11A000' THEN 5000  WHEN 'VSFT1-201' THEN 250  WHEN '6TPH1A0190' THEN 2000
    WHEN '6TPP210190' THEN 1000  END,
    UPDATED_AT = SYSTIMESTAMP
 WHERE COMPANY = '40' AND PLANT_CD = '1000'
   AND ITEM_CODE IN ('CRRKEB6167','CRRTEB3840','DLMLS6-3-3','HKEAN1W002FA','NBC3-5L','TKEG1WFSCD','6TBE11A000','VSFT1-201','6TPH1A0190','6TPP210190')
/

-- 8. 유효기한 초과/임박 LOT 6 + 보류/IQC불합격/IQC보류 LOT 3 (+ 동일 수량의 MAT_STOCKS)
INSERT INTO MAT_LOTS (MAT_UID, ITEM_CODE, INIT_QTY, CURRENT_QTY, RECV_DATE, EXPIRE_DATE, VENDOR, IQC_STATUS, STATUS, COMPANY, PLANT_CD, CREATED_BY)
SELECT lot_uid, item, qty, qty, TRUNC(SYSDATE) - 40, TRUNC(SYSDATE) + exp_off, 'SEED-VENDOR', iqc, st, '40', '1000', 'SEED'
FROM (
  SELECT 'SEED-LOT-01' lot_uid, 'MAG_TAPE00008NA' item, 1200 qty, -12 exp_off, 'PASS' iqc, 'NORMAL' st FROM DUAL UNION ALL
  SELECT 'SEED-LOT-02', 'MAG_SELA00062NA', 3000,  -3, 'PASS', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-03', '6TPH1A0190',       400,   5, 'PASS', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-04', 'MAG_SELB00025NA', 2500,  14, 'PASS', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-05', 'MAG_CORX00151NA',  800,  21, 'PASS', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-06', 'MAG_CATX00082NA', 5000,  28, 'PASS', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-07', 'MAG_TERX00616NA', 4000, 180, 'PASS', 'HOLD'   FROM DUAL UNION ALL
  SELECT 'SEED-LOT-08', 'MAG_HOUX02086NA', 1500, 365, 'FAIL', 'NORMAL' FROM DUAL UNION ALL
  SELECT 'SEED-LOT-09', 'MAG_LDWX01563NA',  900, 300, 'HOLD', 'NORMAL' FROM DUAL
)
/
INSERT INTO MAT_STOCKS (WAREHOUSE_CODE, ITEM_CODE, MAT_UID, QTY, RESERVED_QTY, AVAILABLE_QTY, COMPANY, PLANT_CD, CREATED_BY)
SELECT 'W001', ITEM_CODE, MAT_UID, CURRENT_QTY, 0, CURRENT_QTY, '40', '1000', 'SEED'
  FROM MAT_LOTS WHERE MAT_UID LIKE 'SEED-LOT-%'
/

-- 9. 제품 보류/불량 재고 4건 (PK: COMPANY, PLANT_CD, WAREHOUSE_CODE, ITEM_CODE, QUALITY_STATUS)
INSERT INTO PRODUCT_STOCKS (WAREHOUSE_CODE, ITEM_CODE, ITEM_TYPE, QTY, RESERVED_QTY, AVAILABLE_QTY, STATUS, QUALITY_STATUS, HOLD_REASON, HOLD_AT, COMPANY, PLANT_CD, CREATED_BY)
SELECT wh, item, it, qty, 0, qty, st, qs, hr, CASE WHEN st = 'HOLD' THEN SYSTIMESTAMP END, '40', '1000', 'SEED'
FROM (
  SELECT 'DEFECT'   wh, 'N91H00-X9800'   item, 'FINISHED'     it,  35 qty, 'NORMAL' st, 'DEFECT' qs, NULL hr FROM DUAL UNION ALL
  SELECT 'DEFECT',      'N91H00-X9800-S',      'SEMI_PRODUCT',      60,     'NORMAL',    'DEFECT',    NULL    FROM DUAL UNION ALL
  SELECT 'FG_SHIP',     'N91H00-X9800_1',      'FINISHED',         120,     'HOLD',      'GOOD',      '고객 클레임 확인 대기' FROM DUAL UNION ALL
  SELECT 'WIP_MAIN',    'N91H00-X9800-C2',     'SEMI_PRODUCT',     240,     'HOLD',      'GOOD',      '치수 재검사 대기' FROM DUAL
)
/

-- 10. 금일 입출고 트랜잭션 20건 — 입고 12 / 출고 5 / 생산투입 3
INSERT INTO STOCK_TRANSACTIONS (TRANS_NO, TRANS_TYPE, TRANS_DATE, FROM_WAREHOUSE_ID, TO_WAREHOUSE_ID, ITEM_CODE, QTY, STATUS, COMPANY, PLANT_CD, CREATED_BY, REMARK)
SELECT 'TXSEED-' || LPAD(n, 2, '0'),
       CASE WHEN n <= 12 THEN 'MAT_IN' WHEN n <= 17 THEN 'MAT_OUT' ELSE 'PROD_CONSUME' END,
       TRUNC(SYSDATE) + (7 + MOD(n * 5, 9)) / 24 + n / 1440,
       CASE WHEN n <= 12 THEN NULL ELSE 'W001' END,
       CASE WHEN n <= 12 THEN 'W001' ELSE 'SFG_WIP' END,
       CASE MOD(n, 6) WHEN 0 THEN '6TPP210190' WHEN 1 THEN '6TPH1A0190' WHEN 2 THEN '6TBE11A000'
                      WHEN 3 THEN 'MAG_TERX00616NA' WHEN 4 THEN 'MAG_SELA00062NA' ELSE 'NBC3-5L' END,
       CASE WHEN n <= 12 THEN 100 * n ELSE -50 * n END,
       'DONE', '40', '1000', 'SEED', '모니터링 시드'
  FROM (SELECT LEVEL n FROM DUAL CONNECT BY LEVEL <= 20)
/

COMMIT
/
