ALTER TABLE IQC_PART_SPEC_ITEMS ADD (
  INSPECTION_TYPE VARCHAR2(12),
  SAMPLE_METHOD   VARCHAR2(8),
  SAMPLE_QTY      NUMBER
);
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.INSPECTION_TYPE IS '검사유형 AQL/DESTRUCTIVE/FULL (IQC_INSPECT_TYPE)';
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.SAMPLE_METHOD IS '샘플방식 AQL(자동)/FIXED(고정) (IQC_SAMPLE_METHOD)';
/
COMMENT ON COLUMN IQC_PART_SPEC_ITEMS.SAMPLE_QTY IS 'FIXED/DESTRUCTIVE 고정 샘플수(LOT당)';
/
