-- ============================================
-- HANES MES 마이그레이션 SQL
-- 실행일: 2026-02-24
-- ============================================

-- 1. PART_MASTERS 테이블 컬럼 추가
-- 마이그레이션: 1771882101037-AddToleranceRateToPartMaster.ts
ALTER TABLE PART_MASTERS ADD (
    TOLERANCE_RATE NUMBER(5,2) DEFAULT 5.0
);
COMMENT ON COLUMN PART_MASTERS.TOLERANCE_RATE IS 'PO 수량 오차 허용률 (%)';

-- 2. PART_MASTERS 추가 컬럼
-- 마이그레이션: 1771882552632-AddPartMasterFields.ts
ALTER TABLE PART_MASTERS ADD (
    IS_SPLITTABLE VARCHAR2(1) DEFAULT 'Y',
    SAMPLE_QTY NUMBER(10)
);
COMMENT ON COLUMN PART_MASTERS.IS_SPLITTABLE IS '자재 분할 가능 여부 (Y/N)';
COMMENT ON COLUMN PART_MASTERS.SAMPLE_QTY IS '샘플검사 수량';

-- 3. TRACE_LOGS 부모-자식 관계 추가
-- 마이그레이션: 1771882596757-AddTraceLogParentId.ts
ALTER TABLE TRACE_LOGS ADD (
    PARENT_ID VARCHAR2(36)
);
COMMENT ON COLUMN TRACE_LOGS.PARENT_ID IS '부모 시리얼 ID (반제품→완제품 연결)';

CREATE INDEX IDX_TRACE_LOGS_PARENT_ID ON TRACE_LOGS(PARENT_ID);

-- 4. MAT_ISSUES 생산실적 연결 추가
-- 마이그레이션: 1771882748530-AddMatIssueProdResultId.ts
ALTER TABLE MAT_ISSUES ADD (
    PROD_RESULT_ID VARCHAR2(36)
);
COMMENT ON COLUMN MAT_ISSUES.PROD_RESULT_ID IS '생산실적 ID (자재 투입 이력 연결)';

CREATE INDEX IDX_MAT_ISSUES_PROD_RESULT_ID ON MAT_ISSUES(PROD_RESULT_ID);

-- ============================================
-- 롤백 SQL (필요시 사용)
-- ============================================
/*
-- 롤백 4
DROP INDEX IDX_MAT_ISSUES_PROD_RESULT_ID;
ALTER TABLE MAT_ISSUES DROP COLUMN PROD_RESULT_ID;

-- 롤백 3
DROP INDEX IDX_TRACE_LOGS_PARENT_ID;
ALTER TABLE TRACE_LOGS DROP COLUMN PARENT_ID;

-- 롤백 2
ALTER TABLE PART_MASTERS DROP COLUMN IS_SPLITTABLE;
ALTER TABLE PART_MASTERS DROP COLUMN SAMPLE_QTY;

-- 롤백 1
ALTER TABLE PART_MASTERS DROP COLUMN TOLERANCE_RATE;
*/
